### ISSUE TITLE
make all plots support generic data types

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#103]
Right now only doubles and double arrays can be plotted. Let's expand ScottPlot to work with generic types.

### Performance
Switching to generic types has the potential to reduce performance. Most graph types don't require performance (scatter plots, text, axis lines, and bar graphs). The only two graph types where performance really matters are:

* `PlotSignal`
  *  Used to display arrays that change often (e.g., the audio monitor app)
  * It must load data fast
  * It must render fast
* `PlotSignalConst`
  * Used to interactively display extremely large (but unchanging) data. 
  * It can load data slowly (and process it with trees)
  * It must render fast

As long as performance of these features is preserved, I think _all_ Plottables can switch to accepting generic types. `PlotSignalConst` already accepts generic types (#100) so really the only consideration is preserving performance of `PlotSignal`.

**Comment by StendProg** [comment]
This can be not easy task for other types and speed redusing may be more then 10-50%.
I spend some time on investigation how generics works. My summary on generics to save time:
- Generics don't allow any operations like +,-, > etc.
- it's posible make constrain for interface like IComparable, and compiler allow to call it for T, but no interface for operations.
- using T.ConvertTo(T) drop performance by more then 2 times comparable to '>' operator.
- other simple way is to convert T to specified type like Convert.ToDouble() and make operations. But it also may be very slow (don't measure that). I use it, but not on critical for performance sections.
- One hack from jon Skeet is to use compiled at runtime lambda expressions. At runtime type of T already can be taken, and you can manualy compile it to high performance IL code and call it. Thats make code complex and unreadable, and compiler cant check for errors. But using lambda reduce performance drop to only 10-30% compare to nongeneric implementation.
- native .net way make operations for generic is implement realization for all posible types. and switch on them at runtime. Thats allow compiler make checks for type errors. But it make code unreadable and hard to support because a lots of code duplicates for each type.

**Comment by swharden** [comment]
> This can be not easy task for other types and speed reducing may be more then 10-50%. I spend some time on investigation how generics works. My summary on generics to save time

Thank you for your summary! It seems the use of generics is more complicated than I originally thought. 

> native .net way make operations for generic is implement realization for all possible types and switch on them at runtime. Thats allow compiler make checks for type errors. But it make code unreadable and hard to support because a lots of code duplicates for each type.

This makes sense, but is a lot of code to maintain. I'm happy to leave things as they are for now.

Thank you for this useful information!

**Comment by swharden** [comment]
For now we will continue to require users to supply double arrays for most plots.

However I added some tools to make it a little easier to do the conversion:
```cs
int[] xs = ScottPlot.DataGen.RandomInts(rand, 100, 10);
int[] ys = ScottPlot.DataGen.RandomInts(rand, 100, 20, -10);

formsPlot1.plt.PlotScatter(ScottPlot.Tools.DoubleArray(xs), ScottPlot.Tools.DoubleArray(ys));
```

This way it is obvious to the user when data is being copied.

https://github.com/swharden/ScottPlot/blob/2816ea6ff377c77d6ef1ff02b9803868154d7d41/src/ScottPlot/Tools.cs#L143-L164
