### ISSUE TITLE
ScottPlot crashes application if Windows OS scaling changed to 125% from default 100%

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#125]
Config: using ScottPlot.FormsPlot in WinForm project, Windows 7 x64 pro, VS 2019 Community edition.

Both IDE and standalone executable project crashes if Windows resolution scaling set to 125%. Setting back to 100% default, IDE starts to show the Plot control in the designer without error msg, and also runs it. Same for the exe release.

**Comment by swharden** [comment]
Thanks for reporting this! I noted this in https://github.com/swharden/ScottPlot/issues/111 but couldn't reproduce the error on my home computer so I didn't get to fix it.

Since you're able to reproduce it, do you have a suggestion for a fix? 

This might be harder than it sounds, because mouse-tracking (click-drag panning and zooming) is calculated based on mouse pixel coordinates... so even if it stops crashing, mouse interaction might be pretty messed-up...

**Comment by bukkideme** [comment]
I think this is a rare scenario when we need to change default scaling above 100%. That is why I did not face this bug so far. Actually the solution was simply placing closer the monitor to the user, I told them not to use higher scale value :)
And yep, mouse tracking is important, better not to mess with it...

**Comment by swharden** [comment]
> I think this is a rare scenario

I thought this too, which is why I dismissed https://github.com/swharden/ScottPlot/issues/111 ... but it's interesting that we both experienced this "rare scenario" independently. Maybe it's not as rare as we thought?

Something we could to to prevent a hard crash is to detect if we are in visual studio using 

```cs
bool InDesignerMode = (System.Diagnostics.Process.GetCurrentProcess().ProcessName == "devenv");
```

Then wrap the render function in a try/catch _only if we are in designer mode_.

https://github.com/swharden/ScottPlot/blob/020d0aed5521c46cb190fd2cc20f1baadb9ee837/src/ScottPlot/UserControls/FormsPlot.cs#L40-L53

**Comment by bukkideme** [comment]
Ok, but the crash also happens from running standalone exe built. Maybe as a kind of precaution, could we detect actual screen scaling? And give a warning to the user that ScottPlot should not be run/used beside custom scaling values...?

**Comment by swharden** [comment]
> Ok, but the crash also happens from running standalone exe built. Maybe as a kind of precaution, could we detect actual screen scaling? And give a warning to the user that ScottPlot should not be run/used beside custom scaling values...?

I looked into this about a year ago. I think the answer I came up with was "not easily" because detecting display scaling is different on different version of Windows (9X, ME, XP, 7, 8, 10), there there are complexities like "compatibility mode", and I didn't feel like supporting all those different conditions...

Maybe in response to a crash the ScottPlot could render a simple label which indicates it crashed and suggest disabling display scaling?

I still don't understand why it _crashes_. I'd understand if mouse tracking were off, but why a hard crash?

**Comment by ab-tools** [comment]
Just adding my two cents regarding this issue here as I was fighting with Windows font scaling for another project some time ago and can share my experience:
Microsoft implemented font scaling probably starting from Windows 8 and I would be very surprised if somebody would be able to reproduce this crash with Windows 8 or 10 (also this report here relates to Windows 7).

Initially I did an attempt to support Windows 7 font scaling and older, but as you wrote already, there are just too many different modes and all make you new problems.

Therefore, I just used a similar approach than you suggested already:
If font scaling is enabled and you are not using Windows 8 or 10, just tell the user that this is not a good idea! :-)

For detecting I use this function - if it does not return `true` I would recommend to stop rendering and just show a label to the user that font scaling with Windows 7 and older is not supported:
```
public static bool isFontScalingValid()
{
    // we don't have any problems if it's Windows 8 or newer
    if (Environment.OSVersion.Version.Major > 6 ||
        Environment.OSVersion.Version.Major == 6 &&
        Environment.OSVersion.Version.Minor > 1)
        return true;

    var dpiX = 0;
    var dpiY = 0;
    using (var graphics = Graphics.FromHwnd(IntPtr.Zero))
    {
        dpiX = (int)Math.Round(graphics.DpiX);
        dpiY = (int)Math.Round(graphics.DpiY);
    }

    return dpiX == 96 && dpiY == 96;
}
```

As hopefully Windows 7 dies at some point anyway, this will not hurt too many people anymore. ;-)

**Comment by swharden** [comment]
A previous issue about crashing with DPI scaling (#111) was on Windows 10, so there may be more to it than just a Windows version issue. Interestingly one of my Win10 machines doesn't crash but the other does. Look how the scaling checkbox is disabled on the box that crashes. This might have to do with .NET version too...

Win10 box that crashes | Win10 box that doesn't crash
---|---
![image](https://user-images.githubusercontent.com/4165489/65391386-a48a2480-dd36-11e9-99db-777fc1191d99.png) | ![image](https://user-images.githubusercontent.com/4165489/65391498-f2535c80-dd37-11e9-9921-3ced130f5e27.png)

In any case, thanks for sharing the DPI detection code! I simplified it a bit and added a label that displays a DPI-related error message when applicable. This seems to fix the crashing! Thanks for the tip

![image](https://user-images.githubusercontent.com/4165489/65391633-5591be80-dd39-11e9-9269-07657bbefae7.png)
