### ISSUE TITLE
surface plot - feature request

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#129]
Hi!
I wonder how easy or difficult would be to implement some basic 3D surface plotting feature in ScottPlot? Something like Excel surface chart which input's is a 2D matrix, but with mouse rotation option.

![3DplotExcel](https://user-images.githubusercontent.com/51174971/65253808-913f4500-dafb-11e9-99b7-16007e08cff4.png)

**Comment by swharden** [comment]
> I wonder how easy or difficult would be to implement 3D plotting

difficult 😜 

![image](https://user-images.githubusercontent.com/4165489/65282513-11b57400-db03-11e9-8cf2-57559bf353c4.png)

... but possible! I'd probably start by experimenting outside of ScottPlot. ScottPlot uses only GDI+ to render images. It looks like somebody wrote a 3D engine for GDI https://github.com/oeshiro/gdi-3d-renderer which might be a useful starting point, but I think this task is bigger than I'd like to undertake!

Wouldn't a heatmap be better for representing 2D data anyway? Looking at the excel plot I can't tell where the bounds of the gray (peak) area are. I have an idea, but a 2D headmap / contour plot seems much more accurate. 

Matplotlib does this very well: https://jakevdp.github.io/PythonDataScienceHandbook/04.04-density-and-contour-plots.html

![image](https://user-images.githubusercontent.com/4165489/65282682-7bce1900-db03-11e9-91e9-4f5dbc44f430.png)

**Comment by bukkideme** [comment]
Yes, in certain cases a heatmap would be just fine to use. Actually what was in my mind, to have a kind of animation. I have for example a series of surface map data blocks, and I would like to visualize in time how the surface evolves. A heatmap could also work in such way, but I thought a 3D object would look cool. But of course, it is only useful, if you have the option to zoom in/out, and rotate the 3D object. In the past I used as I remember, an OpenGL control from LabWindows CVI (NI), maybe I should search for an easy to use OpenGL animation API for C#....

Anyway, thanks for the feedback! :)

**Comment by swharden** [comment]
An OpenGL-based 3D rendering engine for plotting would be an excellent tool and quite an undertaking... but I think this is outside the scope of the core design philosophy of ScottPlot which values a dependency-free library with strives for minimal code size and complexity.

I'll close this issue because I think 3D rendering is outside the scope of ScottPlot, but such a system would be a cool thing to explore as its own project!

Note that I have been working on an OpenGL-based (hardware-accelerated, not 3D) plotting library https://github.com/swharden/QuickPlot but I'm about to abandon these efforts because it's really hard to support advanced rendering libraries on all systems. GDI+ is slow, but it works everywhere https://github.com/swharden/QuickPlot/issues/1 so I'm inclined to keep using it...
