### ISSUE TITLE
horizontal multiplier gets cut-off when horizontal axis label is not shown

### ISSUE THREAD

**Issue by ab-tools** [swharden/ScottPlot#130]
I just tried this library and I'm a bit confused about the automated X axis label generation in this very simple example here:
```
var testData = new SortedDictionary<double, double>();
testData.Add(0, 1);
testData.Add(6000, 5);
testData.Add(11000, 1);

var plot = new ScottPlot.Plot(600, 400);
plot.PlotScatter(testData.Keys.ToArray(), testData.Values.ToArray());
plot.AxisAuto(0 , 0);
plot.SaveFig("test.png");
```

The result looks like this
![test](https://user-images.githubusercontent.com/1347603/65390026-b16d3f00-dd5b-11e9-9f58-584207434783.png)

What's the reason that the X axis labels got divided by 1000 (although there would be enough space) and what's this interesting cropped number in the bottom right? :-)

Thanks in advance
Andreas

**Comment by swharden** [comment]
> What's the reason that the X axis labels got divided by 1000

On the bottom right it should say "e3" (indicating the X axis is multiplied by 1000), but it's getting cut off because there is a layout bug. I actually fixed this within the last couple weeks but I haven't pushed the updated source to NuGet yet. I'll do this today and close this issue when I do. 

If you want to give it a shot with the current version of the source code in this repo, I bet it would render properly. Here's what your figure looks like in my test application.

![image](https://user-images.githubusercontent.com/4165489/65390429-c2eb2280-dd2c-11e9-8fb7-ed9a170d5e96.png)

**Comment by swharden** [comment]
... note that this bug only affects graphs which don't have the extra spacing from a horizontal axis label. You might fix your problem just by adding

```cs
plot.XLabel("Horizontal Axis");
plot.YLabel("Vertical Axis");
```

**Comment by ab-tools** [comment]
That's great, thanks a lot for your really quick reply, Scott! :-)

Is there a parameter then to let it show the full numbers in the axis labels instead of divided by 1000?

There is enough space for it and I would prefer to have them fully displayed.

Thanks again
Andreas

**Comment by swharden** [comment]
> Is there a parameter then to let it show the full numbers in the axis labels instead of divided by 1000?

```cs
plot.Ticks(useOffsetNotation: false, useMultiplierNotation: false);
```

Cookbook example:
https://github.com/swharden/ScottPlot/tree/master/cookbook#multiplier-notation-disabled

There's a chance those advanced features aren't in the NuGet package yet, but I'll release the latest build on NuGet shortly.

Hope this helps! Glad you enjoy ScottPlot =]

**Comment by ab-tools** [comment]
Thanks a lot, Scott! :-)

**Comment by swharden** [comment]
Just published it on NuGet - it should be processed and ready to update within a half hour.

https://www.nuget.org/packages/ScottPlot

Best,
Scott
