### ISSUE TITLE
DPI Setting for Saving Plot Image to File

### ISSUE THREAD

**Issue by ab-tools** [swharden/ScottPlot#135]
Is there a way to set a certain DPI when saving a plot image to a file?

I want to use some plots in a document which will be printed, so I need a certain DPI/resolution of the plot images.

I could, of course, just increase the plot pixel width/height, but this would make all the texts basically unreadable.

Probably it's simple and I just missed an option for this, but maybe you could point me into the right direction, thanks! :-)

Maybe it's also possible to save the plot in a vector format which would be even better, of course?

**Comment by swharden** [comment]
> Is there a way to set a certain DPI when saving a plot image to a file?

Unfortunately, no. This library was created primarily with screen rendering in mind. As such, display items (line widths and font sizes) are exclusively sized in pixels. For example, an axis tick mark is always 1 pixel wide.

> I could just increase the plot pixel width/height, but this makes all the texts basically unreadable.

As you discovered, you can create an image of any size (e.g., [cookbook#very-large-images](https://github.com/swharden/ScottPlot/tree/master/cookbook#very-large-images)), but fonts and lines will always render the same pixel size. As you increase the image size, the components of the image appear relatively smaller.

> Maybe it's also possible to save the plot in a vector format which would be even better, of course?

All drawing uses GDI+ to add lines and text to a Bitmap, so vector rendering isn't really an option given the present method.

### hack solution: resize the bitmap

Medium-sized images aren't unreasonably poorly laid out. What if you created an image at 600x800 resolution as a Bitmap, then resized the bitmap to your final size with bicubic antialiasing? It wouldn't be perfect, but I doubt it would look bad.

### best solution: universal size multiplier

The best way to fix this problem is to find every call to `DrawLine()`, `DrawLines()`, `DrawRectangle()`, `FillRectangle()` `DrawEllipse()`, `FillEllipse()`, and `DrawString()`, and multiply the width by a universal size multiplier. For pixel-based screen rendering this number would always be `1.0`, but for large DPI image renders this multiplier would be increased to effectively increase all the sizes (of lines and fonts) without changing their locations. This would create the desired output, but is a large undertaking considering there are numerous drawing calls throughout this library.

Let me take a few more days to consider this option. It would be a very large code change, but would be a great improvement for users who desire to create plots for documents.

**Comment by swharden** [comment]
After considering this issue in more detail, I realized the fix is even more complex than I thought because the whole layout system is pixel-based too. This means all code related to drawing and all code related to layout must be modified to accomodate DPI scaling.

To summarize, all drawing uses GDI+ which exclusively deals with pixels, so scaling is not easily achievable. Interestingly this is also what makes supporting displays which use DPI scaling so difficult. A workaround (a global pixel multiplier) may be possible, but is such a large undertaking I'm not going to attack it at this time. 

I'll keep this topic in my mind for the next time I write a plotting engine! Perhaps ScottPlot V4 (not sure when), or [QuickPlot](https://github.com/swharden/QuickPlot).
