### ISSUE TITLE
PlotText() custom rotation

### ISSUE THREAD

**Issue by gwilson9** [swharden/ScottPlot#160]
In addition to alignment, would also be nice to be able to change the orientation that the text is displayed. 

Thanks,

G

**Comment by swharden** [comment]
Thanks for the suggestion @gwilson9, I'll add this in soon.

## Text Rotation

An argument for rotation is straightforward:

```cs
plt.PlotText("sample", 10, 20, rotate: -90);
```

... although this will be a challenge to implement with GDI since I can't rotate the text - I must rotate the _canvas_, draw text (at new coordinates), then rotate the canvas back. I haven't confirmed this can be easily done for non-90º multiples yet.

## Text Alignment

I could create a `TextAnchor` enum so you'd pass something like:

```cs
plt.PlotText("sample", 10, 20, anchor: TextAnchor.NorthWest);
```

Or I could request strings like:

```cs
plt.PlotText("sample", 10, 20, hAlign: "right", vAlign: "top");
```

**Comment by gwilson9** [comment]
90º multiples would work for me for my current application but I agree that more options would be preferable.

**Comment by swharden** [comment]
Ha! It seems `plt.PlotText()` _already_ has an alignment argument. Let me know if you think it's broken for some reason. Otherwise, I'll assume that issue is solved.

I'll keep working on rotation.

**Comment by swharden** [comment]
Drawing rotated text is surprisingly difficult with System.Drawing because you can't rotate text - you can only rotate the _canvas_, then draw text at a location. Rotating the canvas changes the pixel coordinates of where you wanted your text to go.

Rather than using trig to figure out where rotated text should go, I translated the canvas so the text position would be (0, 0), then rotated an arbitrary amount, then drew the text at (0, 0), then reset everything. It's a bit of a hack but it seems to work.

I'll release this on NuGet this weekend! Thanks for the suggestion.

```cs
int pointCount = 50;
double[] dataXs = ScottPlot.DataGen.Consecutive(pointCount);
double[] dataSin = ScottPlot.DataGen.Sin(pointCount);
double[] dataCos = ScottPlot.DataGen.Cos(pointCount);

var plt = new ScottPlot.Plot(width, height);
plt.PlotScatter(dataXs, dataSin);
plt.PlotScatter(dataXs, dataCos);

plt.PlotPoint(25, 0.8, color: Color.Green);
plt.PlotText(" important point", 25, 0.8, 
	color: Color.Green);

plt.PlotPoint(30, 0.3, color: Color.Black, markerSize: 15);
plt.PlotText(" default alignment", 30, 0.3, 
	fontSize: 16, bold: true, color: Color.Magenta);

plt.PlotPoint(30, 0, color: Color.Black, markerSize: 15);
plt.PlotText("middle center", 30, 0, 
	fontSize: 16, bold: true, color: Color.Magenta,
	alignment: ScottPlot.TextAlignment.middleCenter);

plt.PlotPoint(30, -0.3, color: Color.Black, markerSize: 15);
plt.PlotText("upper left", 30, -0.3,
	fontSize: 16, bold: true, color: Color.Magenta,
	alignment: ScottPlot.TextAlignment.upperLeft);

plt.PlotPoint(5, -.5, color: Color.Blue, markerSize: 15);
plt.PlotText(" Rotated Text", 5, -.5, 
	fontSize: 16, color: Color.Blue, bold: true, rotation: -30);

if (outputPath != null) plt.SaveFig(fileName); else Console.WriteLine(plt.GetHashCode());
Console.WriteLine($"Saved: {fileName}");
```

![image](https://user-images.githubusercontent.com/4165489/68350629-fd3b3400-00ce-11ea-9c85-cb19c1cbd671.png)

**Comment by swharden** [comment]
this feature is now in the latest NuGet package
https://github.com/swharden/ScottPlot/releases
