### ISSUE TITLE
Candlechart - Remove weekends and holidays

### ISSUE THREAD

**Issue by satyat110** [swharden/ScottPlot#186]
Over the weekends and holidays, market is closed and we don't have any data to display in the charts from the data source in the daily charts. Also the same applies for the hourly charts after market hours. Is there a way to skip, if we don't have data from the data source.
Currently it shows a blank space for those no data days (refer attached chart)

![Chartimage](https://user-images.githubusercontent.com/58095701/69770703-e40e2c00-113e-11ea-85be-cd182731c008.JPG)

**Comment by swharden** [comment]
Consider these two statements:

* Daily stock price data is not uniformly spaced in time since weekends and holidays have no data
* ScottPlot plots data on a linear horizontal axes

To display stock prices over time but not display weekends and holidays, you need a non-linear horizontal axis (an axis that literally skips numbers). ScottPlot is not designed to be able to do this. All of the axis, grid, and tick code assumes linear axes.

The only way to do this with ScottPlot is to stop using the DateTime features and plot data with a simple ascending series of numbers as the time points. Perhaps we could add an extra property to OHLC to store DateTime to keep track of this even though it would not be used to determine the position on the plot. 

Plotting data on an arbitrary horizontal time axis which skips days is a different enough task that I think it would warrant its own library (one made for only plotting financial data).

I wish I had a better answer! Hope it helps.

**Comment by satyat110** [comment]
Thanks Scott... I will try your alternate if needed...

**Comment by swharden** [comment]
Anticipating this is may be a common question, I added an example of this to the cookbook:
https://github.com/swharden/ScottPlot/tree/master/cookbook#candlestick-days-evenly-spaced

**Comment by gdszljl** [comment]
https://github.com/ScottPlot/ScottPlot/tree/main/cookbook#candlestick-days-evenly-spaced      url was broke

**Comment by some1new** [comment]
Well I'm interested in a solution for this, too.

**Comment by swharden** [comment]
Hi @gdszljl and @some1new, thanks for pointing out the broken URL! This is the new cookbook URL demonstrating how to skip weekends:

https://scottplot.net/cookbook/4.1/category/plottable-finance/#candlesticks-with-custom-tick-labels

![image](https://user-images.githubusercontent.com/4165489/229014458-52092d72-1bca-48d3-bc7a-f54e62e1832a.png)
