### ISSUE TITLE
add notes to readme comparing ScottPlot to similar libraries

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#193]
Similar open-source libraries to be compared are:
* [LiveCharts](https://github.com/Live-Charts/Live-Charts)
* [OxyPlot](https://github.com/oxyplot/oxyplot)
* [ZedGraph](https://github.com/ZedGraph/ZedGraph)

**Comment by swharden** [comment]
I'm working on a graphics video series for YouTube. After I post the section about this topic (with code examples), I'll link to it in the main readme.

**Comment by kirsan31** [comment]
Any news about this?

**Comment by swharden** [comment]
Great question! I started working on a little YouTube mini-series about this topic but I ran out of steam... although I hope to come back to it shortly.

Some good news is that I did pretty well on making markdown notes as sort of a script for the videos. Although the videos aren't ready, the code and comments are pretty useful in in their unfinished/unpolished state.

https://swharden.com/CsharpDataVis/#plotting-data-with-c

Hope it helps!
Scott

**Comment by kirsan31** [comment]
I briefly looked to this articles and found no comparison between libraries :(
I think this (performance / functionality / ease of use comparison) is important when ppl want to migrate to some thing new.
For example, we consider go away from [winforms-datavisualization](https://github.com/dotnet/winforms-datavisualization) because it's discontinues and probably will have no new .NET designer support. We think about ScottPlot and OxyPlot for now.
May be some comparison with winforms-datavisualization?
