### ISSUE TITLE
WPF SaveFig() fails when called before OnResize event

### ISSUE THREAD

**Issue by karimshams** [swharden/ScottPlot#196]
I tried to save  the figure using different ways but I always get empty file.

**Comment by StendProg** [comment]
Hi @karimshams , thanks for your feedback.
I tried to reproduce you problem on latest version of ScottPlot, and SaveFig() in WPF application works correct.

1. Can you reproduce problem on latest version of ScottPlot 4.0.9?
2. Can you provide code example to reproduce you problem?

**Comment by karimshams** [comment]
I still have the same issue, herein the code example:

C# code:

            List<double> dataX = new List<double>();
            List<double> dataY = new List<double>();
            foreach (var Node in NodesEnvelopes)
            {
                dataX.Add(Node.Value.Key.Item2);
                dataY.Add(Node.Value.Key.Item3);

            }

            wpfPlot1.plt.PlotScatter(dataX.ToArray() , dataY.ToArray());

            wpfPlot1.plt.Title("ScottPlot WPF Quickstart");
            wpfPlot1.Render();
            wpfPlot1.plt.SaveFig(@"C:\Temp\wpftest.png");

XML:
<Grid>
        <ScottPlot:WpfPlot Name="wpfPlot1"/>
    </Grid>
- I have the plot figure with the correct data but the issue when I try to save it.

**Comment by StendProg** [comment]
Thanks for provided code, i get the same empty file.
This happens because at constructor time ScottPlot does not render correct.
Canvas have (0,0) size at constructor time.
After constructor time, canvas rise up to actual size, and ScottPlot rerender correct on OnResize event.

If you still want to run SaveFig from constructor, you can do the trick with awaiting of canvas rising:
```c#
...
wpfPlot1.plt.PlotScatter(dataX.ToArray() , dataY.ToArray());
wpfPlot1.plt.Title("ScottPlot WPF Quickstart");
wpfPlot1.Render();
Task.Run(() =>
{
    while (wpfPlot1.plt.GetSettings().gfxData == null)
        Thread.Sleep(100);
     wpfPlot1.plt.SaveFig(@"C:\Temp\wpftest.png");
});
```

Possible more general solutions of this issue:
- Add `Init` flag indicating that ScottPlot get correct render.
- Add event to ScottPlot, that rises on correct render.

**Comment by swharden** [comment]
@StendProg thank you for solving @karimshams problem!

Perhaps I should make SaveFig() throw an exception is a save is attempted when the size is 0,0 to make this problem easier to identify in the future 🤔
