### ISSUE TITLE
MatchAxis with vertical:false not scaling

### ISSUE THREAD

**Issue by ckovamees** [swharden/ScottPlot#217]
Thanks for a great project, I'm just starting to use it.

I'm using `MultiPlot` (in lieu of QuickPlot's `secondY: true`) and want to have similar X-axis (dates), but let the Y-axis represent different data, with different scale. 

I'm use 'Cookbook.Figure_73_Multiplot()' to reproduce and illustrate here.
If I add `vertical:false`, like this 
`plt.subplots[2].MatchAxis(plt.subplots[3], vertical:false);`
Then the X-axis adapts to the source plot's X-axis, but the Y-axis is left empty.
![keep_multiplot](https://user-images.githubusercontent.com/9557072/72942150-c0332500-3d40-11ea-9994-04dcbf2e7057.png)

**Comment by StendProg** [comment]
Hi @ckovamees.
It looks like you want to call `MatchAxis()` for  `X` axis only, and get `AutoSize()` for `Y` axis only.(Don't clearly understand).
You can add to your code:
```c#
plt.subplots[2].MatchAxis(plt.subplots[3], vertical:false);
plt.subplots[2].AxisAutoY();
```
And some investigation shows what it actualy call `Settings.AxisAuto()` with correct `yExpandOnly = true`

Problem is that using this `xExpandOnly` or `yExpandOnly` params not implemented in `Settings.AxisAuto()`.
https://github.com/swharden/ScottPlot/blob/9a43b0cf77c09fa764a1414c3041e34da14acefd/src/ScottPlot/Settings.cs#L136
So we have correct API with no implementation at the end.
To fix this, `Axes.Expand()` method must be expanded to get additional `xExpandOnly` and `yExpandOnly` params. And then called from `Settings.AxisAuto()` with this `ExpandOnly` params.
https://github.com/swharden/ScottPlot/blob/9a43b0cf77c09fa764a1414c3041e34da14acefd/src/ScottPlot/Config/Axes.cs#L56
https://github.com/swharden/ScottPlot/blob/9a43b0cf77c09fa764a1414c3041e34da14acefd/src/ScottPlot/Settings.cs#L151

**Comment by ckovamees** [comment]
Thanks for your clarification @StendProg. I'm still trying to catch up on the code and don't completely get everything you mention.

So the call `MatchAxis(otherplot, vertical:false)` isn't supposed to make the vertical axis auto size? I didn't understand that and that I had to call `AutoY()` explicitly. 

When I was playing with this I also noticed that if I called `Ticks()` before `MatchAxis(otherplot, vertical:false)` it worked. But it didn't work when I called `Ticks()` after `MatchAxis`.

**Comment by StendProg** [comment]
```c#
plt.subplots[2].AutoAxis();
plt.subplots[2].MatchAxis(plt.subplots[3], vertical:false);
```
Can solve this issue without any source changes. 

For every plot `AutoAxis()` called automatic before render if axises not set manual. This issue because `MatchAxis()` set axis limits manual, and `AutoAxis()` not called.

Possible improvement of library:
 - `AutoAxis()` must check each axis manual setup separate, and rescale axis with no manual setup (`Y`  in this issue example).

Anyway not implemented `ExpandOnly` params should be fixed.

**Comment by swharden** [comment]
Hi @ckovamees thanks for reporting this!

@StendProg, thank you for your excellent suggestion as well! Your idea to manually call `AutoAxis()` _before asking to match the axis_ solves this problem.

The simplest way to fix this is for me to add code to `MatchAxis()` to determine if the axis has been set previously, and if not it will call `AutoAxis()` automatically before attempting to match the axis limits.

I created a failing test to demonstrate this issue:

https://github.com/swharden/ScottPlot/blob/461c65ee57017521d5f4ffa64501d802be54de0d/tests/Multiplot.cs#L73-L79

```
Subplot index 0 xSpan=1.07, ySpan=1.1
Subplot index 1 xSpan=0, ySpan=17.38
Subplot index 2 xSpan=16.44, ySpan=0
Subplot index 3 xSpan=16.44, ySpan=17.38
```

![image](https://user-images.githubusercontent.com/4165489/73036270-05c32100-3e19-11ea-8b43-e7c34a110436.png)

**Comment by swharden** [comment]
It looks like that did the trick! a4d5df2c4e2c867078179849313ad28148b3ddd0

I'll publish this on NuGet then close this issue. Thanks again for both of your help!

![image](https://user-images.githubusercontent.com/4165489/73036725-7a4a8f80-3e1a-11ea-887c-b05276c5d512.png)

**Comment by swharden** [comment]
> Possible improvement of library: `AutoAxis()` must check each axis manual setup separate, and rescale axis with no manual setup (`Y`  in this issue example).

@StendProg this is an interesting suggestion! Instead of adding multiple arguments to `AxisAuto()`, would `AutoAxisX()` and `AutoAxisY()` be simpler?

---

Also, I don't have your email address so I'll mention a couple topics here I thought you'd find interesting. If you have questions you are welcome to email me (swharden@gmail.com) or we can continue to converse here.

* I'm working to fully replace the ScottPlot axis management system with a new system which will make it easier for two plots to share axes in real time (panning one pans the other) and also allow the addition of a second vertical axis. The change should be invisible to existing users and produce no change in output (strict tests will confirm this).

* I'm experimenting with creating a `ScottPlot.Drawing` namespace which contains classes like `text`, `line`, `rectangle`, `circle`, etc... The goal is to remove all `System.Drawing` calls out of ScottPlot, and have the `ScottPlot.Plot` object just create a collection of drawing objects in memory but not actually render a bitmap. I can then render plots with different drawing systems, such as `RenderWithGDI(bmp, plt)` or `RenderWithSkia(canvas, plt)`. I'd really like to be able to benefit from Skia/OpengGL, and adding support to ScottPlot (rather than developing QuickPlot) is probably the best solution.

Thank you for your encouragement on both of these topics!
-Scott
