### ISSUE TITLE
horizontal bar charts

### ISSUE THREAD

**Issue by bonzaiferroni** [swharden/ScottPlot#277]
Any plans to implement horizontal bar charts? It might improve readability for charts like the one attached. 

![guess_news_Catagorical](https://user-images.githubusercontent.com/10502552/75462680-d59ffe00-5941-11ea-8add-1a1cbdbace2a.png)

Labels are too long to have as tick labels, so they are added as text and rotated. However, there's no inherent advantage to arranging them horizontally, and a vertical arrangement would allow a similar approach without any neck injuries. I believe this is the more common approach to bar charts.

I'd be happy to take a stab at it if you can give an overview on how you'd approach it.

**Comment by swharden** [comment]
Hey @bonzaiferroni,

I plan to refactor the bar chart module to add support for stacked bar charts (#260) so now's a good time to go ahead and support horizontal orientation. Thanks for the suggestion!

I'll start working on this as soon as I'm done with the new demo application (#271). I'll leave this ticket open until this features is added.

Your question, "how do I experiment making custom new plot objects?" is a good one! I've been meaning to write a quickstart guide just for this topic (#249). If you _really_ want to give it a stab in the mean time you can modify [plottables/PlottableBar.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableBar.cs), but be aware I'm going to start actively working on that module any day now so it might not be a good idea to do anything serious because it'll be a bit of a moving target.

**Comment by swharden** [comment]
I'll close this issue and track progress toward this goal in #315

**Comment by swharden** [comment]
I added a `horizontal` argument to `PlotBar()` and will publish this on NuGet tonight.

I'm still working on refactoring the box plot module to allow advanced things like stacked plots and displaying scatter plots next to the boxes & error bars (#315) but this is a good stopping point for this ticket.

![image](https://user-images.githubusercontent.com/4165489/77807698-ffdafd80-705e-11ea-9a0a-0cc631164f6d.png)

**Comment by swharden** [comment]
following up, ScottPlot 4.0.25 has some new related features. Check out the cookbooks to see what's possible now:

### Bar Plot
This is a relatively simple plot type. It's just for bar plots, and it does not display population details (like scatter plots of individual data points).
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Bar_Quickstart

### Box and Whisker Plot
This has extensive options, including displaying as bar plots, and rendering population data points next to the box/bar plot.
http://swharden.com/scottplot/cookbooks/4.0.25/#PlotTypes_Populations_PlotPopulationSeriesUnique

**Comment by bonzaiferroni** [comment]
These look fantastic.
