### ISSUE TITLE
add "open in new window" to right-click menu

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#280]
Feature request.

So I have a grid of plots and want to examine one or more of them more closely. Possible options:

1. Clicking on the plot could pop up a modal window. Closing with Esc key or Spacebar would be nice.

2. Mouse-hovering would enlarge the plot while the mouse remains hovered. This limits the size of the enlarged window, or require positioning so that it doesn't interfere with the mouse pointer.

**Comment by swharden** [comment]
I like this idea! What about adding an item to the right-click menu, "open plot in new window" and it would open a secondary window that the user can make any size they want?

**Comment by Resonanz** [comment]
Hi Scott, the plotting stuff is working well after a little help from yourself and another. Re this thread... I'm not such a fan of right-click to show an enlargement as it requires a non-left mouse click + another mouse click, then another mouse movement and click to close. Thus I would vote for a mouse hover. That said, I'm not sure how this would work... it could be annoying to have things popping up all over the place, and left click is already used. An alternative would be to have a optional icon(?) on the plot that pops the plot out and enlarges it, then a click-anywhere to close it (thus modal I guess). Anyways, just some ideas.

**Comment by swharden** [comment]
> I'm not such a fan of right-click to show an enlargement as it requires a non-left mouse click + another mouse click, then another mouse movement and click to close. Thus I would vote for a mouse hover. That said, I'm not sure how this would work... it could be annoying to have things popping up all over the place, and left click is already used. An alternative would be to have a optional icon(?) on the plot that pops the plot out and enlarges it, then a click-anywhere to close it (thus modal I guess). Anyways, just some ideas.

Hi @Resonanz, I'll add the "open in new window" option to the existing right-click menu and it won't be disruptive to your application. It will be useful for some of my applications which show really tiny graphs, and rather than have the user interact with them I'll disable pan/zoom and have the user right-click/new window if they want to interact with the graph.

For your application, perhaps you could code something similar to a picture viewer that has a strip of photos at the top with a horizontal scroll bar, and a big image area that displays the selected photo at full-size. Maybe something like:

![image](https://user-images.githubusercontent.com/4165489/78041560-d8c24b80-733e-11ea-8f8c-9b8f15151187.png)
