### ISSUE TITLE
plotting data in lists (instead of arrays)

### ISSUE THREAD

**Issue by Resonanz** [swharden/ScottPlot#285]
Hey there Scott, wondering if there are any technical reasons for using arrays rather than lists for plot data. Is it currently possible to use lists, or is this something you would consider implementing? Wondering because lists have some benefits over arrays in terms of dynamically appending elements which is useful in my case at least :-) 

I know that I can use .ToArray().

**Comment by swharden** [comment]
Hey @Resonanz, right now all functions are written only to support double arrays. To understand why I'll restate your question in a way that makes the answer a bit more obvious: Instead of just supporting `double[]`, why not also support `float[]`, `short[]`, `int[]`, `long[]`, `byte[]`, `decimal[]`, `List<double>`, etc... 

The simple answer is that it's a lot more code (and function overloads) to support, so strictly supporting `double[]` seemed to be the best compromise.

There is a WinForms demo has a "live data" tab (#163) which shows how to plot incoming data (which I think is from a list that grows as data comes in). You may find this useful if your application does something similar.

Support for genetics (`<T>`) was discussed at one point (#103) but due to some complicated reasons this wasn't implemented. One exception is `SignalConst<T>()` which does support plotting of generics. @StendProg did some excellent research on this topic and wrote conclusions here: https://github.com/swharden/ScottPlot/issues/103#issuecomment-522262826
