### ISSUE TITLE
WinForms transparent background

### ISSUE THREAD

**Issue by envine** [swharden/ScottPlot#286]
Is it possible to set transparent background on formsPlot control in WinForms?
```
formsPlot.plt.Style(figBg: Color.Transparent); 
formsPlot.plt.Style(dataBg: Color.Transparent);
```
This makes blue background as we see in the designer.
It seems that bitmap can be generated with transparency, but I need it in WinForms control.

**Comment by StendProg** [comment]
Hi @envine.
Your problem turned out to be more complicated than it seems at first glance.
Winforms have poor transparency support.
There is possible to simulate transparency for `UserControl` by some tricks:
1. Add in `UserControl` constructor 
```c#
    SetStyle(ControlStyles.SupportsTransparentBackColor, true);
    SetStyle(ControlStyles.Opaque, true);
    this.BackColor = Color.Transparent;
```
2. Override `UserControl` `CreateParams` method
```c#
 protected override CreateParams CreateParams
    {
        get
        {
            CreateParams cp = base.CreateParams;
            cp.ExStyle = cp.ExStyle | 0x20;
            return cp;
        }
    }
```
Main problem is PictureBox which has it own implementation. I try to apply this tricks on it too, but unsuccessfully.

It's possible to remake `FormsPlot` control to not use `PictureBox`. `plt.GetBitmap()` manualy draw to control canvas in `OnPaint` method. @swharden can reveal the reasons why `PictureBox` is used now.

Anyway, there is no true transparency solution for `Winforms`. Can you describe a bit more about
problem which you actually want to solve. Do you want to place `FormsPlot` over another controls and see them, or something else?

**Comment by envine** [comment]
Thanks @StendProg .
I just want to put `FormsPlot` on my main `Form` (System.Windows.Forms.Form) of the WinForm application.
The main `Form` has a `BackgoundImage` on it, and I want to make this image visible even over `FormsPlot` by setting the background of `FormsPlot` transparent.

**Comment by StendProg** [comment]
If you need transparency only over `Form` `BackgroundImage`:
```c#
formsPlot.plt.Style(figBg: Color.Transparent); 
formsPlot.plt.Style(dataBg: Color.Transparent);
...
formsPlot.BackColor = Color.Transparent;
```
This will be possible after PR #287 will be merged. This PR set internal `pbPlt.BackColor` together with `FormsPlot.BackColor`.

It will look something like this.
![image](https://user-images.githubusercontent.com/53831487/76144802-e57fb680-6094-11ea-83bf-7b0b69afc73b.png)

**Comment by envine** [comment]
Thank you very much @StendProg .
I have tested your PR, and it works perfectly!

Overriding `BackColor` property of `PictureBox` used for `FormPlot` is enough for my use.
Thank you again.

**Comment by swharden** [comment]
> I just want to put `FormsPlot` on my main `Form` (System.Windows.Forms.Form) of the WinForm application. The main `Form` has a `BackgoundImage` on it, and I want to make this image visible even over `FormsPlot` by setting the background of `FormsPlot` transparent.

Hi @envine, I think @StendProg is right: my understanding is that a truly transparent background is not possible in windows forms. This limitation of Windows Forms is why you also cannot add a `Label` with a transparent background that will allow your background image to show through. The closest you can get is to make your background and ScottPlot the same solid color.

Perhaps you could simulate transparency by getting a transparent Bitmap with `plt.GetBitmap()` then drawing it onto your background in a way that preserves the transparency. The plot would not be interactive though.

To make this topic easier to explore I created a transparent background winforms demo. Note that this new demo isn't finished yet, and I'm actively working on it (#271)

![image](https://user-images.githubusercontent.com/4165489/76146255-370d4e80-605f-11ea-9e62-f626d2bb1812.png)

> It's possible to remake FormsPlot control to not use PictureBox. plt.GetBitmap() manualy draw to control canvas in OnPaint method. @swharden can reveal the reasons why PictureBox is used now.

@StendProg I think the reason I did this is because `PictureBox` has simple and robust support for double buffering. Drawing directly on the control may produce flickering. This is my understanding, but I haven't explored this topic in a while - if you are aware of a better way let me know!

**Comment by swharden** [comment]
@StendProg and @envine sorry about my confusing initial response. @StendProg described the solution very well. I updated the example, and the code explains itself:
```cs
formsPlot1.plt.Style(figBg: Color.Transparent, dataBg: Color.Transparent);
formsPlot1.BackColor = Color.Transparent;
```

![image](https://user-images.githubusercontent.com/4165489/76146604-0bd82e80-6062-11ea-8bcb-adfb7c9ea6c0.png)

**Comment by StendProg** [comment]
This solution works only for `Form` background, any control hide under `FormsPlot`. As you explained there is only flicker ploblem you see in `OnPaint` render implementation. Maybe i will test this implementation later.

**Comment by envine** [comment]
Thanks for your comment @swharden .
I understand the issue on complete transparency is not the matter of ScottPlot implementation.
And, thank you for merging the latest PR by @StendProg and adding nice demo for that.
It works as I expected.

**Comment by swharden** [comment]
For what it's worth, I added support (and a demo) for the WpfPlot control too.

![image](https://user-images.githubusercontent.com/4165489/76147511-f4ea0a00-606a-11ea-9404-ede6ae7b0d01.png)

It was hard to track down, but the only change needed was to modify the encoder for `bmp.Save`:

https://github.com/swharden/ScottPlot/blob/22e7e23e4a6bb8877a0a801ce1a9557e620ceba8/src/ScottPlot.WPF/WpfPlot.xaml.cs#L82-L92
