### ISSUE TITLE
Support for scatter plots with polar coordinates?

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#292]

**Comment by Benny121221** [comment]
#295

**Comment by StendProg** [comment]
Converting polar coordinates is a simple task. Not so hard manual convert coordinates to decart and pass them to ScottPlot. Helper method for conversion will be usefull.

There is possible to make special `PolarPlot` type with different axises. Something like circles for `R`, and Rays for `Angle`. To do this, you need to write a lot of new code that does not rely on existing.
A large amount of work. Is it worth it?

**Comment by Benny121221** [comment]
I ain't a fan of the graphics-ey stuff, so I probably wouldn't be the best person to implement a circular axis. However, it does seem like a good idea and I could look at that down the road

**Comment by swharden** [comment]
Hey @Benny121221, thanks for this PR!

The topic of plotting data on non-linear coordinates comes up every once and a while. #41 #207 #29

Since ScottPlot renders on Bitmaps using pixel coordinates, all math assumes Cartesian coordinates. The best way to display non-Cartesian data with ScottPlot's Cartesian coordinate system is to convert the data to Cartesian coordinates before plotting it. It is probably best if the user does this conversion.

If you want to write a tool to simplify conversions between Polar and Cartesian coordinates, a function which accepts a polar data and returns Cartesian data would be ideal. You can model your function after `ScottPlot.Tools.Log10()` which performs a similar conversion for plotting log data.

https://github.com/swharden/ScottPlot/blob/3a652b4d1bf4f8c2bbece862e949597ae7ee5ce0/src/ScottPlot/Tools.cs#L221-L227

If you make such a function, it's a good opportunity to make a new PR based on the master branch.

**Comment by Benny121221** [comment]
#298
