### ISSUE TITLE
EqualAxis for Plot

### ISSUE THREAD

**Issue by StendProg** [swharden/ScottPlot#306]
I make PR but get problems with `ScottPlot` main repository.
Here PR in my fork https://github.com/StendProg/ScottPlot/pull/2.
If you are interested you can manual grab it, before I will solve git problem.

**Comment by swharden** [comment]
The problems were caused by me modifying the git history. I'm really sorry to have made this PR difficult! I don't intend to rewrite history anymore. #305

I'll manually apply your changes from https://github.com/StendProg/ScottPlot/pull/2 into master. Sorry for the inconvenience the history modification caused you!

This modification looks excellent, thank you for working on this!
