### ISSUE TITLE
Absolute Text Positioning

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#321]
Hi,

i want, additionally to the legend, position a PlotText relative to the legend or plot-frame, and not to the grid. So i want to set an anchor from which the coordinates are counted.

e.G. the "normal" mode counts the coordinates relative to x/y zero, and i wnat to set it to being relative to the top left corner of the legend, or the bottom right corner of the plot.

You think this is can be done?

**Comment by swharden** [comment]
> I want to position a PlotText relative [in pixel units, not plot coordinates] ... You think this is can be done?

Hi @SeidChr, there's not an easy way to do this currently. 


Some type of "annotation" text object which draws on the image itself (rather than the coordinate system) may be useful 🤔 I'll try implementing this a few different ways and see what it looks like! I'll leave this issue ticket open until I explore this topic further.

---

Technically you can do it (even in WinForms) by making a Bitmap, drawing on the Bitmap, then applying the Bitmap to a picturebox. The downside here is that it's not mouse interactive. Something like:

```cs
var plt = ScottPlot.Plot(pictureBox1.Width, pictureBox1.Height);
plt.PlotScatter(xs, ys);

Bitmap bmp = plt.GetBitmap();
/* draw text on this bitmap using System.Drawing */

pictureBox1.Image = bmp;
```

**Comment by swharden** [comment]
> So i want to set an anchor from which the coordinates are counted.

I suppose there is another way you could do this with the current implementation. Say you want to draw text in the top right corner. You can use `plt.Axis()` to get the top right corner coordinate (x2 and y2), then plot the text at that coordinate (being careful to set the right alignment).

If the graph is resized, you can move the position of the text (or clear the graph of all text objects and add them again).

**Comment by swharden** [comment]
@SeidChr created new methods which let the user accomplish what you suggested in your original post. I'm using "annotation" to describe text fixed to the _figure_ instead of the _data area_, and as you drag the plot around the annotations stay fixed.

To be able to edit the annotation once it's plotted, save the `PlottableAnnotation` object returned by `PlotAnnotation()` and write to its `label` property. If doing this in a user control you'll always want to call `Render()` after editing the label to force a redraw.

I think this is looking great! I'll release it on NuGet shortly.

![image](https://user-images.githubusercontent.com/4165489/78505845-1f9bb100-7744-11ea-9dce-69868895127b.png)


```cs
var plt = new ScottPlot.Plot(600, 400);

double[] xs = DataGen.Range(0, 5, .1);
plt.PlotScatter(xs, DataGen.Sin(xs));
plt.PlotScatter(xs, DataGen.Cos(xs));

// negative coordinates snap text to the lower or right edges
plt.PlotAnnotation("Top Left", 10, 10);
plt.PlotAnnotation("Lower Left", 10, -10);
plt.PlotAnnotation("Top Right", -10, 10);
plt.PlotAnnotation("Lower Right", -10, -10);

// arguments allow customization of style
plt.PlotAnnotation("Fancy Annotation", 10, 40,
    fontSize: 24, fontName: "Impact", fontColor: Color.Red, shadow: true,
    fill: true, fillColor: Color.White, fillAlpha: 1, lineWidth: 2);
```

**Comment by SeidChr** [comment]
Hi, thx!
Is there a way to fetch the size of the legend, so i can put the label right next to it?

**Comment by swharden** [comment]
This might need a little tweaking but it's a good start. If you want something more custom it might require modifying the source code of the legend (or creating a custom legend plottable). That said, this outcome is pretty close to what you're seeking

This code is live on NuGet now btw

![image](https://user-images.githubusercontent.com/4165489/78512078-a31ec780-776f-11ea-9a49-afc42ca5265f.png)

```cs
Random rand = new Random();
double[] dataA = ScottPlot.DataGen.RandomNormal(rand, 50);
double[] dataB = ScottPlot.DataGen.RandomNormal(rand, 50);

var plt = new ScottPlot.Plot(400, 300);
plt.PlotSignal(dataA, label: "data A");
plt.PlotSignal(dataB, label: "data B");
plt.Legend();

plt.GetBitmap(true); // force a render to force drawing/placing the legend

double legendLocationX = plt.GetSettings(false).legend.rect.Location.X;
double legendDistanceFromRightEdge = plt.GetSettings(false).dataSize.Width - legendLocationX;
plt.PlotAnnotation("text beside\nthe legend", 
		xPixel: -legendDistanceFromRightEdge - 5, 
		yPixel: -13,
		fillColor: Color.White,
		fillAlpha: 1,
		lineWidth: 1
	);
```

**Comment by SeidChr** [comment]
Looks good! Sufficient for my needs :)
Thx again!
