### ISSUE TITLE
Fill Area between Signals or Signal & Zero

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#328]
Hi,

i would like to make a plot where a range of possible outcomes is marked. this range has a upper and lower signal, and preferably a filling color.

One other type of Charts you could enable with the same technique is the Area Chart:
![image](https://user-images.githubusercontent.com/1927076/77898722-dfd45580-727b-11ea-87ba-df163b184517.png)
which uses only one signal and shows the area between the signal and the zero-line.

I haven't found a way to do this in your current Cookbook. Probably also a duplicate of #255. Feel free to merge or close if so.

**Comment by swharden** [comment]
Hi @SeidChr, thanks for suggesting this! I'm indeed working on this functionality as part of #255, so I'll close this issue and leave that one open.

I've been pretty behind on this feature because I've been woking on #315 for the last couple weeks. Now that it's complete, this is next on the docket!
