### ISSUE TITLE
Difference between Linux and Windows rendering

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#340]
Using windows for development and linux via github workflows, it seems that there are a couple of differences in the rendered output, you may want to address, so the output becomes more reliable.

![plot-germany-linux](https://user-images.githubusercontent.com/1927076/78986751-4e42ce80-7b2c-11ea-908b-0958922ebd40.png)
![plot-germany-windows](https://user-images.githubusercontent.com/1927076/78986756-50a52880-7b2c-11ea-8895-e6df8d3ddc2c.png)

Main issues for me are the differences in spacing around the subtitle (xlabel) and the fill-colors in the legend, which are 2 squares on linux and correct rectangles on windows.

the code used to generate these plots is here:
https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/blob/master/src/Plotting/Plotter.cs

**Comment by swharden** [comment]
Thanks for pointing this out @SeidChr! Aside from ensuring things compile and basic tests pass on Linux and MacOS I don't often get to directly visualize the output so your images are very useful.

**You didn't specifiy which is Linux and which is Windows** but I'm guessing the top one is Linux because it's the most messed up 😅 

First, I think all the problems are because the default font is different on Linux. It's more dramatic than I'd expect it to be though.

* I suspect [System.Drawing.Common.Graphics.MeasureString()](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.measurestring?view=netframework-4.8) is returning very different vertical dimensions for tick labels between Linux and Windows. This is what gives the lower ticks too little padding, and the left ticks too high of a density. 
* I suspect your Linux font does not support bold which explains why the title looks different.

### Potential Quick Fix
Do different fonts improve the situation? Title(), XLabel, and Ticks() all accept font settings. Try setting Ticks() with a few different fonts and see if any of them give you the effect you're looking for.

```cs
plt.Ticks(fontName: "DejaVu Sans Mono");
```

### Deeper Fix
Since I suspect `Graphics.MeasureString()` is producing different outputs on different platforms, I probably have to create a `ScottPlot.MeasureString()`, make all current measurements use the new version, and add an if statement to multiply the vertical dimension by 2 if on Linux.

I have no idea why the legend looks like that! It's just a 10px high line. Perhaps I can fix it by intercepting fat legend lines and drawing them as rectangles. I can add alpha support while I'm in there, partially addressing concerns raised by #344 

It would be great if `System.Drawing.Common` worked more reliably, but it looks like these are the cards we've been dealt by Microsoft. Frankly I'm largely happy it works on Linux at all.

Thanks again for sharing these images @SeidChr!

**Comment by SeidChr** [comment]
Morning.
It was in the file name and is now in the alt text. U guessed correctly. The first is Linux 😊
Will see what changing the font does later today 😊

**Comment by SeidChr** [comment]
I assume the difference in vertical ticks comes through the different heights of the diagrams themselves. But maybe also partially be caused by different font sizes

**Comment by SeidChr** [comment]
Changing the font did not have an effect on the label or tix. Though im not applying this now.

**Comment by swharden** [comment]
I created a new test to let me inspect how `Graphics.MeasureString()` works on different operating as it runs in my Azure build pipeline. Vertical dimensions for size-14 default fonts on Mac/Linux/Win are 20/22/27 px. Doesn't seem hugely different, but I still think enough to be causing your differences. I'll keep working on this...

```
Unix 19.4.0.0 (MacOS)
The string 'ScottPlot' with font 'Helvetica' (size 14) measures: 72px x 20px
```

```
Unix 5.0.0.1035 (Linux)
The string 'ScottPlot' with font 'DejaVu Sans' (size 14) measures: 81px x 22px
```

```
Microsoft Windows NT 10.0.17763.0
The string 'ScottPlot' with font 'Segoe UI' (size 14) measures: 82.82116px x 27.16145px
```

> Using ... linux via github workflows

I've been doing all my development with Azure Pipelines. On every GitHub commit it regenerates the entire cookbook and saves the output as PNG files, but I'm not sure if these files are accessible 🤔 I'll take a deeper look, because it would be a great help to be able to visually inspect the output on Linux and MacOS (since it's already generating/saving it as it runs the tests). Not sure if this is possible with the free version though. I might need to take a closer look at GitHub Workflows. I started an issue to track this #345 thanks for mentioning it!

**Comment by swharden** [comment]
Thanks to the new build system #345 we can see what the output looks like on different operating systems. This will help a lot toward troubleshooting moving forward.

I think all the differences between platforms are simply differences in available fonts. Since font measurements determine a lot of elements of the layout, the effect of different fonts ripples into differently-placed components.

I still think the best solution here is to use a central `MeasureString()` function and apply an OS-specific scale factor to stabilize these measurements.

![Test_Plot_WithOsInfo (2)](https://user-images.githubusercontent.com/4165489/79049011-f9b45780-7bee-11ea-96d4-702c6dcf807b.png)

![Test_Plot_WithOsInfo (1)](https://user-images.githubusercontent.com/4165489/79049008-f7ea9400-7bee-11ea-8dbf-45d03ec9d399.png)

![Test_Plot_WithOsInfo](https://user-images.githubusercontent.com/4165489/79048961-b3f78f00-7bee-11ea-8d55-b00b3543f439.png)

**Comment by swharden** [comment]
Wow, what a rabbit hole this has been!

It seems System.Drawing.Common can't render bold fonts on Linux, so the default title style will look different. 

Otherwise, we are getting a lot closer now. Maybe a few pixels away from ideal...

![Test_Plot_WithOsInfo (8)](https://user-images.githubusercontent.com/4165489/79054043-d8b02e80-7c0f-11ea-9e99-50c47a2857c1.png)

![Test_Plot_WithOsInfo (9)](https://user-images.githubusercontent.com/4165489/79054058-ea91d180-7c0f-11ea-9441-f5a794e80cbb.png)

![Test_Plot_WithOsInfo (10)](https://user-images.githubusercontent.com/4165489/79054082-144af880-7c10-11ea-8cfe-50fefcad9666.png)

**Comment by swharden** [comment]
I added some pixel-level tweaks for Linux and MacOS. I'll release this in a new NuGet package in a few minutes. 

Awesome improvement @SeidChr, thanks again!

![Test_Plot_WithOsInfo (11)](https://user-images.githubusercontent.com/4165489/79054346-06967280-7c12-11ea-8129-454126c80de6.png)

**Comment by SeidChr** [comment]
You have noticed that the dots are not correctly positioned on the curves, right? 😁

**Comment by swharden** [comment]
> You have noticed that the dots are not correctly positioned on the curves, right? 😁

💀

**Comment by swharden** [comment]
Actually after a bunch of testing I realized this is an obscure bug that only affects low density Signal (not scatter) plots. It probably has a very low impact. Either way, it's fixed now. Thanks for pointing it out!
