### ISSUE TITLE
Define order of legend items

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#344]
**What can we do to make ScottPlot better?**

When i want to draw something OVER something else, i need to add it to the plott later, which will move the legend-entry after the other entry.
Now i have no way of saying i want that thing to be on top of the list, which would be helpful in some circumstances.

Sample:
![image](https://user-images.githubusercontent.com/1927076/79008560-ef964880-7b5d-11ea-8587-b4b4878f56ae.png)

Would be great to define a sort order property on the drawn elements (e.G. labelSortOrder = 50) and order the labels according to the sortorder instead of the drawing order. 

Another idea is to set a priority of some kind, where default elements have normal priority for legend, but you can increase the prio in order to move the entry up.

I prefer tha latter, because the logic supports to have a default value as prio, whereas sortorder implies a unique number on every element.
So internal ordering of the legend by priority first, by the order in which they have been added later would be the ideal soultion i guess.

**Comment by swharden** [comment]
Hey @SeidChr, thanks for this useful suggestion! This will take some serious effort to accomplish (see below) and may take some time to fully implement. However, I just added a new argument which may help you out:

```cs
plt.Legend(reverseOrder: true);
```

Does this get you sufficiently close to your goal?

## big picture / new direction for this issue 

The legend is drawn differently than almost every other item in ScottPlot, so unfortunately changing its behavior can get a bit complex. However, this may indicate it's a good time to refactor the Legend module to make it easier to work with in the future. I actually think we would do well if we make the Legend a type of Plottable, similar to a PlottableAnnotation. In doing so I could add advanced options, like the ability to specify the order of its items, customize the look of the lines/markers/rectangles in the key for each item, or even create custom items in the legend that don't correlate directly with existing plot objects. This could all be done while preserving the current `Legend()` method, so it wouldn't break anyone's code out there.

I'll leave this issue open to track progress toward this, but focus on some of the other issues first because this is likely to be a pretty significant refactor.

**Comment by SeidChr** [comment]
Reverse order should be fine in my case!

**Comment by swharden** [comment]
> Reverse order should be fine in my case!

Awesome! I'll release this on NuGet some time this weekend.

Rather than bend this issue to accomodate a new topic, I'll close it and open a new one later to address refactoring of the Legend module to make it a Plottable.
