### ISSUE TITLE
XAxis for Financial plots must allow overlay of candlestick and technical indicators such as SMA or Bollinger bands

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#348]
Financial charts normally use date time for xAxis. Scottplot does not support xAxis of type Datetime for plotFill/plotPolygon.
overly of different time interval on same chart with their corespondent indicators also require xAxis with Datetime with ability to eliminate none trading times.
Many new libraries support unixtimestamp for date.

**Comment by swharden** [comment]
To plot OHLCs with `DateTime` units next to other plottables (like scatter plots) which use double arrays for the horizontal axis, use `DateTime.ToOADate()` to convert all of your dates to doubles before making the scatter plot.

ScottPlot uses OADate instead of unix time. Interestingly, .NET doesn't support unix time. If you want to convert a `DateTime` to/from unix time, you have to write your own function to do this. Since `OADate` is natively supported by .NET, ScottPlot uses it instead of unix time. `OADate` is the number of days since the OLE Automation Date (midnight, 30 December 1899), and is more commonly in .NET environments than unix timestamp / epoch format. 
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tooadate
