### ISSUE TITLE
Is it possible to change key binds

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#352]
Is there an option to customize the keyboard/mouse controls? For example, use left click to zoom and right click to pan, alt+left click to rectangle zoom etc.

**Comment by swharden** [comment]
Aside from being able to customize the right-click menu and disable zooming and/or dragging, I don't think it's possible to re-wire events in the FormsPlot and WpfPlot controls to significantly change their interactive behavior like that.

Users who would benefit from a highly customized user control are encouraged to copy FormsPlot.cs and modify it to create their own control that meets their needs. There's relatively little code in there, and by deleting chunks that aren't useful to your application you can thin it down a lot further. Then you have total control over the mouse and keyboard interactive behavior.

https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot.WinForms/FormsPlot.cs

Good question @LogDogg, I hope my answer helps somewhat!

**Comment by LogDogg** [comment]
Yes, @swharden, it's very helpful, thank you!

**Comment by EmanuelFeru** [comment]
Hi Scott @swharden,

I was actually also considering to customize the mouse bottons slightly. I wanted to actually:
- Move the Zoom box from Middle button drag -> Left button drag
- Move the Pan from Left button grad -> Middle button drag

Because it would feel more natural to me due to the software I used in the past. The rest can stay default because I like it. If I understand correctly, it is not possible to customize this at the moment, right? Unless I recreate the `FormsPlot.cs` and change it to my needs?

**Comment by swharden** [comment]
Hi @EmanuelFeru,

This is closer to easy than it used to be, but it still requires modification of the source code. You identified the correct files! You can probably achieve your desired behavior just by modifying the logic inside the `if` statements in the `MouseMove()` and `MouseUp()` methods:

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Control/Backend.cs#L460-L491

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Control/Backend.cs#L553-L578

I added an item to the triage list #1028 to create a demo or document this eventually 👍
