### ISSUE TITLE
Chart Control (alternative to FormsPlot)

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#358]
It would be nice if there was an option to enable scrollbars. Something like:
`formsPlot.Configure(verticalScrollbar: true, horizontalScrollbar: true);`
For the actual values on the axes that the scrollbars would scroll from and to, I see 3 different options:
1. Define them through a function, like `formsPlot.plt.ScrollbarLimits()` or something similar (I like this option because it gives developers the most freedom)
2. Use values from `AutoAxis()`
3. If you end up implementing what I suggested in #349 those values would fit really well, but then the users are forced to set them and maybe they don't want to

Thank you in advance, amazing work on the library!

**Comment by swharden** [comment]
> It would be nice if there was an option to enable scrollbars.

I think I understand this request. Do you have a sample screenshot of a dataset or graph that would benefit from scrollbars? It's kind of hard to picture.

![image](https://user-images.githubusercontent.com/4165489/79804253-b1551200-8331-11ea-9a9a-3840f71f1434.png)

Here's a mock-up I made in PowerPoint. Is this what you had in mind?

> Thank you in advance, amazing work on the library!

You bet! I'm a bit distracted at the moment on a couple other projects, but I'll definitely swing back to ScottPlot and close out the open issues before much longer.

**Comment by LogDogg** [comment]
That's pretty much what I meant, plus the little arrow buttons on the top and bottom that you usually see on a scrollbar. I'll try to provide some screenshots tomorrow (it's 1 AM here currently). 
The scrollbars would be useful for a number of reasons, primarily for the horizontal axis. If you want to stay zoomed in the same amount, they allow you to quickly observe parts of data that are far apart (when you have tens of thousands of points) without the trouble of zooming out first and then zooming in on a different area. They are also really helpful for laptop users, since panning with a touchpad is a bit harder. The little arrows on the ends also help with that. Scrollbars also give you a general idea of what part of the data you're observing currently, which is a nice detail.

**Comment by swharden** [comment]
There's a science program called ClampFit for exploring biological electrical signals. It uses a simple system to do many of the things you're suggesting. In this screen capture I don't demonstrate the scrollbars, but they do what you'd expect.

![clampfit-interaction](https://user-images.githubusercontent.com/4165489/63170189-c17c5b00-c006-11e9-91c2-f6d07a63dd5f.gif)

Instead of continuing to hack features onto the `FormsPlot`, maybe it would be a good idea to add a `StripChart` control which has a more traditional zooming/panning system. It would also let the end user have control over what the left-click and right-click actions do since they're not required for zooming and panning. A hidden benefit is that there's never "live" panning or zooming, so if the chart has a little lag between renders due to large datasets it probably won't be noticed.

It will be a bit of work to implement this type of control (2x if done for Windows Forms and WPF), but it might prove to be really useful...

**Comment by swharden** [comment]
I added this to the [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) for inclusion a future release. I'll close this issue now while I tackle some of the pore pressing topics, then re-open it when I start actively developing this feature. 

Thanks again for the suggestion @LogDogg
