### ISSUE TITLE
Scaling while zooming

### ISSUE THREAD

**Issue by FadyDev** [swharden/ScottPlot#360]
Hello, 
As you see in the attached screenshot, I found that when zooming the scaling of the grid shows strange behavior, in which, the point is divided into a value on the left of the grid and the rest of it above.

Is it possible to enhance the scaling to show the number as a whole on both axis?

Thanks in advance for your help.
BR
Fady

**Comment by swharden** [comment]
Hi @FadyDev, this post doesn't have a screenshot. Can you add one or post a code sample to help me reproduce this behavior? Thanks!

**Comment by FadyDev** [comment]
Hi,

Sorry, I think I had some connection problems while uploading. Here is the screenshot :)

![ScottPlott_Scale_Issue](https://user-images.githubusercontent.com/21091471/80070219-ea180580-8542-11ea-8ebd-cb505379a484.jpg)

**Comment by FadyDev** [comment]
Hallo @swharden 

I added the screenshot right after your reminder. I hope you could find a solution for that problem.

**Comment by swharden** [comment]
Hi @FadyDev, thanks for the screenshot. I'm still a little confused what the problem is though...

Are you asking why this numbers is here?
![image](https://user-images.githubusercontent.com/4165489/80927532-6a710e80-8d6c-11ea-8cfd-2c9a4cbfddc6.png)

That number is _offset notation_. 
http://swharden.com/scottplot/cookbooks/4.0.29/#customize-ticks-offset-notation

Offset notation is disabled by default in ScottPlot 4.0.29. You can manually disable it like this:

```cs
plt.Ticks(useOffsetNotation: false);
```

Does this answer your question?
