### ISSUE TITLE
Legend covers plot

### ISSUE THREAD

**Issue by jbhak4** [swharden/ScottPlot#388]
I was trying to show a legend, but I could have data that will be covered up by the legend. Is there a way to prevent this from happening, either by showing the legend in the padding or by having the data scale adjusted to give the legend extra room?

**Comment by swharden** [comment]
Currently the only two options are:

* Use `plt.Axis()` or `plt.AxisAuto()` (with the proper arguments) to create extra padding on the part of the graph the legend is displayed

* Get the legend as an independent `Bitmap` by calling `plt.GetLegendBitmap()`. You then then apply it to a `Picturebox` or something. I'll leave this issue open to remind me to create a demo program demonstrating this.

However I like the idea of being able to display the legend in the padding area. I'll leave this issue open to remind me to explore options for this behavior. Thanks for the question @jbhak4!

**Comment by swharden** [comment]
Hey @jbhak4, since this requires some heavy refactoring I added it to the [ScottPlot roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) and will re-open this issue when I start working on it. In the interim I'm going to focus on closing-out some of the smaller issues between here and there. Thanks again for your question! Once implemented this will be a very nice feature.
