### ISSUE TITLE
Sequential mode to ignore Xs and plot Ys sequentially

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#393]
Eliminating gaps by not plotting Xs[] values but using the sequence is useful in PlotFills and Scatters and may be many more.

Important note: All Plottables must be considered when Sequential is applied.(Whole set of Xs[] sorted)
Ideally defining ticks label as numeric, string or Datetime using Xs[] values can be extremely helpful.

**Comment by swharden** [comment]
Hi @Minu476, let me see if I understand your suggestion.

Currently, users must supply their own Xs, even if they're just a consecutive list of numbers:
```cs
double[] xs = {1, 2, 3, 4, 5};
double[] ys = {1, 4, 9, 16, 25};
plt.PlotScatter(xs, ys);
```

You'd like users to be able to plot Y data without specifying Xs, and doing so would automatically make the data sequential (consecutive Xs). You'd like to see this supported for all plot types.
```cs
double[] ys = {1, 4, 9, 16, 25};
plt.PlotScatter(ys);
```

Currently the best way to achieve this is to create an array of sequential X values using `DataGen.Consecutive()` which has arguments to define the starting point and the point spacing. Perhaps this method could be improved by adding an overload where start value is a `DateTime` and the spacing is a `TimeSpan`.
```cs
double[] ys = {1, 4, 9, 16, 25};
double[] xs = DataGen.Consecutive(ys.Length);
plt.PlotScatter(xs, ys);
```

@Minu476 did I properly capture your question? What do you think about the use of `DataGen.Consecutive()` as a potential answer to this challenge? If you'd like to try creating an overload designed for `DateTime`, that method lives here:

https://github.com/swharden/ScottPlot/blob/0c1196c3a6eaab80ee6479ee917fb472011112e4/src/ScottPlot/DataGen.cs#L12-L18

**Comment by Minu476** [comment]
Generating X will cause problem, as in most cases we have a useful Xs Value that can be used to create ticks, or be used to toggle with show gap spacing.

**Comment by swharden** [comment]
> Eliminating gaps by not plotting Xs[] values but using the sequence is useful in PlotFills and Scatters and may be many more.

I'm guessing the primary application here is plotting data on financial charts. What if we made new plottables for financial charting? These plottables would only take Y values (not X values) and would always plot in sequential mode. Maybe instead of `PlotScatter` and `PlotFill` we could make something like `TechnicalIndicatorLine` and `TechnicalIndicatorFill`? If we wanted to get specific, we could even make `BollingerBands` a plot type, and it would handle the Xs and Ys under the hood 🤔

**Comment by Minu476** [comment]
I like to keep X values! when you want to see where the gaps are you need
those x coordinate to show the not trading hours! Then you want to see
proper curves in indicator you switch to no gap mode.

**Comment by Minu476** [comment]
I like your x generated be used behind the seen and forget x at no gap mode

**Comment by swharden** [comment]
If we created financial charting objects, every point would have an X position (sequential) ***and*** a DateTime (and perhaps a TimeSpan). The X positions could be generated behind the scenes. This way the user could rapidly switch between a sequential view and a time view. It would also let the user plot sequentially, but OnHover could display the DateTime of the object under the mouse. 

Rather than try to add sequential modes into all existing plottables, I think the best long-term solution here is to create plottables specifically designed for financial charting (and perhaps even a user control specifically designed for displaying these financial objects). This topic is listed in the [ScottPlot roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) so I'll close this issue for now but definitely keep this a near-term priority.

Thanks for your suggestion @Minu476!

**Comment by swharden** [comment]
I started a GitHub team to make discussion/experimentation in this direction easier. I haven't used teams before, but if you want to try extending this conversation there I'm interested in exploring this topic further! https://github.com/orgs/ScottPlot/teams/active-contributors/discussions/1
