### ISSUE TITLE
Wilkinson’s Algorithm for Positioning Tick Labels on Axes.

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#394]
I am planning to implement  Wilkinson’s Algorithm for Positioning Tick Labels on Axes if you like I will try to do it as contributor. It's not high a priority now.

- [x] @swharden will make an experimental `VerticalAxis` plottable. It will let you define its position which could be outside the plotting area. This way we can have it _in addition_ to the current tick system, making it easier to experiment with without modifying ScottPlot's existing tick code. This might get a little bit complicated since the tick-deciding code also determines where grid lines are placed.

- [ ] @Minu476 will then implement [Wilkinson’s algorithm](http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf) as a custom `VerticalAxis` for experimentation.

- [ ] If/when the experimental axis works better than the default axis, ScottPlot can switch to using it by default

**Comment by swharden** [comment]
Hi @Minu476, this sounds excellent to me! The current tick positioning system works, but it's one of the weaker components in the ScottPlot library at the moment. In a previous issue we discussed [An Extension of Wilkinson’s Algorithm for Positioning Tick Labels on Axes](http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf) (Talbot et al.) which may be a useful resource.

Before you begin work on this, give me a few more days to refactor the tick code a bit. I'll leave this issue open to track progress toward this end.

I am currently working to make ticks and legends `Plottable` objects (or something similar). My goal is to decouple these systems from the render loop, and make it easy to swap between different tick systems like linear or log axes (#207, #29, #41), or display multiple axes (#180), or develop new systems like these without having to modify the rendering portion of ScottPlot. I think this will make development easier, as we can keep the current tick system in the code but create an option to switch to new experimental tick systems as they evolve.

**Comment by swharden** [comment]
@Minu476 I edited your original comment to contain a checklist. I think this is the sequence we can use to approach this task. I added this topic to the [ScottPlot roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) and will re-open this issue when I start actively working on this topic. I look forward to helping you implement this soon!

**Comment by Minu476** [comment]
This morning I searched the github and I found this:
https://github.com/jtalbot/Labeling  which looks a decent implementation!
let me know what you think.

**Comment by swharden** [comment]
> This morning I searched the github and I found this:
> https://github.com/jtalbot/Labeling which looks a decent implementation!
> let me know what you think.

Hey @Minu476 this is a good find! What I found interesting is how that repo has source code for multiple axis labelers (https://github.com/jtalbot/Labeling/tree/master/Layout/AxisLabelers). I noticed one for matplotlib in there. 

I think matplotlib is one of the best plotting libraries in the world, and it's open source, so I dove into the (Python) code to try to figure out where its tick detection system is implemented. Found that here: [ticker.py#L1985-L2207](https://github.com/matplotlib/matplotlib/blob/f4f365f4bce2e6c42cb32bd19891034e1c5696f9/lib/matplotlib/ticker.py#L1985-L2207) (documentation: [matplotlib.ticker.MaxNLocator](https://matplotlib.org/3.2.1/api/ticker_api.html#matplotlib.ticker.MaxNLocator))

These are some great resources!

A note about the current state of the code: I think the reason the tick module in ScottPlot is so difficult to work with is because it has to do so many things: It measures tick font size (based on a predicted tick string) to estimate how many ticks will fit on the axis, then it runs the tick finder to find those best N ticks, then it has to measure the actual ticks to find the largest one, then it resizes the graph area to accomodate the actual ticks. In other words, the tick module is complicated for reasons beyond "What are the N best ticks between A and B". Although DateTime tick placement is extremely difficult.

If you want to start poking around, the function that initiates the tick placement calculation is here:
https://github.com/swharden/ScottPlot/blob/2ab1c29297dc04db8f57c40ed726b9aab5216982/src/ScottPlot/Config/TickCollection.cs#L50-L67

**Comment by swharden** [comment]
Hey @Minu476, I made an `ExperimentalTicks` type of plottable object to demonstrate how you can begin experimenting with new tick systems _without modifying any existing code_. That last point is an important one, because I'd much rather invite contributors to bring in some fresh ideas rather than have to deeply study the current implementation to get started.

![ticktester](https://user-images.githubusercontent.com/4165489/84582852-8c27d180-adbf-11ea-88e2-fe3eb83bc3ae.gif)


### Experimental Tick Developer Application

The code underlying the demo application is very simple. It also shows how you can customize render options externally (e.g., from the GUI). This will be useful when testing things like user-defined tick density.

https://github.com/swharden/ScottPlot/blob/c73d93ff97a0cb4300145aa7dd5b1f37b1ee3ea7/dev/FormsPlotSandbox/FormExperimentalTick.cs#L1-L39

### Experimental Tick `Plottable`

This example class was made for maximum readability, and it produces some pretty dumb ticks. I'm thinking you can fully implement a really intelligent tick system just by modifying this class. Probably the simplest thing to do is _duplicate_ this class, name it something that sounds good to you, then we can compare/contrast different tick systems as development progresses.

https://github.com/swharden/ScottPlot/blob/c73d93ff97a0cb4300145aa7dd5b1f37b1ee3ea7/src/ScottPlot/plottables/ExperimentalTicks.cs#L1-L67

### My current effort

I'm currently focusing on some low-level refactoring of the rendering system. It won't affect your experimentation with the tick system, but that large amount of work is why I'm not free to help more directly with this topic at this time.

### Collaboration?

I noticed at the same time #456 was opened by @Orace and #394 was opened by @Minu476, so I wanted to connect these dots in case your goals may be aligned on this one!

**Comment by swharden** [comment]
Also @Padanian wrote some pretty interesting code a while back in #68. It ended-up being too complex to maintain at the time (it didn't work perfectly, and I found it to complex to debug confidently) but now that ScottPlot is beginning to mature and I have more C# experience, perhaps this code is more feasible to work with now that it was last year.

Something special it does is intelligently place ticks for DateTime objects, which can be particularly difficult to get right. Not sure how it relates to Wilkinson’s Algorithm, but I wanted to note it here in case it's useful. I know @Padanian put a lot of work into this at the time, and @Padanian made several other excellent contributions to this project early on.

https://github.com/swharden/ScottPlot/blob/927454787e7681d628dd3a2015b724f988f65d2f/dev/code/TickExperimental.cs

**Comment by Minu476** [comment]
Hi Scott,
Thanks for drafting a guideline for how to implement tick strategy, for
sure this is helpful. I noticed this is now a high priority ToDo item!
Unfortunately I am very busy now in my project and can not work on in until
next month.

Best regards,
Nasser

**Comment by swharden** [comment]
Hey @Minu476, no worries! This will give me some time to work on the layout system between now and then, and this issue and resources will remain here when you're ready to pick up the torch again. 

I think implementing Wilinson's Algorithm is an excellent goal, and I'm happy to have these notes and resources collected here for when you or me or someone else decides to give it a go 👍 

I'll close the issue for now, but we can re-open it if/when activity resumes

**Comment by Minu476** [comment]
Great! I am glad to be active in Scottplot  soon and we get some of the
TradingView features implemented as well together!
