### ISSUE TITLE
Financial plots with growing data

### ISSUE THREAD

**Issue by Minu476** [swharden/ScottPlot#403]
after plotting this code:
```cs
Random rand = new Random(0);
double[] xs = DataGen.Consecutive(150);
OHLC[] ohlcs = DataGen.RandomStockPrices(rand, xs.Length);
(var sma, var bolL, var bolU) = ScottPlot.Statistics.Finance.Bollinger(ohlcs);

// replace timestamps with a series of numbers starting at 0xs
for (int i = 0; i < ohlcs.Length; i++)
    ohlcs[i].time = i;

var plt = new ScottPlot.Plot(600, 400);
plt.PlotCandlestick(ohlcs);
plt.PlotFill(xs, bolU, xs, bolL, "bollinger", 1, Color.Black, true, Color.Aqua, 0.3);
plt.PlotScatter(xs, sma, color: Color.Blue, markerSize: 0, lineStyle: LineStyle.Dash);
```

How we update it by adding one new candle and corresponding bollinger bands values?

**Comment by swharden** [comment]
### Answer: new candles require clear and replot
Since everything is arrays (which cannot grow) the plot must be cleared and re-created whenever a candle is added, so the new array (containing the new candle) can be displayed.

```cs
plt.Clear();
```

### Idea

We could modify the OHLC plottable to accept a `List<OHLC>` instead of `OHLC[]` to make it easier to add new data. 🤔

Perhaps an overload for scatter plot could also accept `List<double>` to make it easier for that data to grow too. This is a pretty fundamental change to ScottPlot though so I'd want to think about it a bit. Related: #103 

### Task: create a demo for financial data
The [ScottPlot roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) has a point about making a better demo for financial plots. Maybe now is a good time to start working on this, and I can demonstrate how to add live incoming price data.

**Comment by swharden** [comment]
This is now in the list of upcoming changes (#412) so I'll work toward this issue there and close it here 👍
