### ISSUE TITLE
What does lowQualityWhileDragging do? 

### ISSUE THREAD

**Issue by LogDogg** [swharden/ScottPlot#404]
Does it only turn off anti-aliasing while dragging, or does it do something else too?

Oh and 1 more question - how to disable anti-aliasing entirely? I forgot how to do it and I can't seem to find it in the cookbook.

**Comment by swharden** [comment]
Since turning anti-aliasing off makes plots render faster, the user control automatically turns anti-aliasing off during click-and-drag zooming and panning to make them feel more responsive to the mouse. You can control this behavior with

```cs
formsPlot1.Configure(lowQualityWhileDragging: false);
```

You can disable anti-aliasing entirely with:
```cs
plt.AntiAlias(false, false, false);
```

You're right it's not in the cookbook! I'll make an anti-alias cookbook example now
