### ISSUE TITLE
Arbitrary non-orthogonal axis

### ISSUE THREAD

**Issue by Padanian** [swharden/ScottPlot#41]
Like in the example below, it would be great to have additional non-orthogonal axis, for functions z=f(x,y) where x,y are horizontal and vertical axis

![psy](https://user-images.githubusercontent.com/7769348/61295561-95d43e00-a7d8-11e9-92c8-312d4e0c4d5c.jpg)

**Comment by swharden** [comment]
YES! While I don't have a personal use case for non-orthogonal axes (maybe [smith charts](https://en.wikipedia.org/wiki/Smith_chart)?), I have wanted to implement logarithmic axes for a while (#29). I did some preliminary work toward implementing this and it was _not_ easy because so many systems rely on on the current coordinate system (mouse click-dragging, tick spacing, grid line rendering, etc). The fix would require some refactoring, but I'd love to do work on it with you.

A better place to start would be to code a proof-of-concept demo as a standalone application. I created a Cartesian plotting demo easily within 100 lines (https://github.com/swharden/Csharp-Data-Visualization/blob/master/examples/2019-06-03-coordinate-system) and I think something like this could be expanded to support nonlinear / non-orthogonal axes. Once we get a handle on how to do it technically (and provide a good interface for it), we can then figure out how to refactor ScottPlot to accomodate it. What do you think of this idea?

A good place to start would be to create a similar app which:
* has a way to draw _points_ on the graph. This is easiest in my experience. 
* has a way to draw _lines_ on the graph. This is where I keep getting overwhelmed with complexity. Grid lines will be unevenly spaced and may curve.
* allows the user select which coordinate system to use
  * perhaps we would make a `CoordinateSystem` class and provide some pre-made ones like `cartesian` and `logarithmic`, `polar`, but let the user make their own with custom formulas if desired.
  * I'm guessing functions like coordinate-to-pixel, drawing of lines, and generation of ticks would all be handled inside these classes

@Padanian I'm looking forward to hearing your thoughts

**Comment by Padanian** [comment]
A coordinate class is the way to go. Any non orthogonal axis (suppose
a y' axis with some arbitrary clockwise angle t and intercept k with
respect to X-axis) can be resolved with the formula y'=-x sin(t) +y
cos(t) + k.Therefore all standard stuff apply, up until actual
representation on the rotated axis.Imagine the example demo
double[] xs = new double[] {0, 1, 2, 3, 4, 5};
double[] ys = new double[] {0, 1, 4, 9, 16, 25};

supposing a rotated clockwise y-axis angle of 30° (#pi/6), the angle
with respect x axis is 60° (#pi/3), and supposing k = 2, the rotated
y' axis would have:double[] yfirsts = new double[] {0,-0.866+0.5+2,
-2*0.866+0.5*4+2, -3*0.866+0.5*9+2, -4*0.866+0.5*16+2,
-5*0.866+0.5*25+2};
or
double[] yfirsts = new double[] {2, 1.634, 2.268, 3.902, 6.536,
16.706};

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Tue, 16 Jul 2019 13:39:10 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] Arbitrary non-orthogonal axis (#41)

	YES! While I don't have a personal use case for non-orthogonal axes
(maybe smith charts [1]?), I have wanted to implement logarithmic axes
for a while (#29 [2]). I did some preliminary work toward implementing
this and it was _not_ easy because so many systems rely on on the
current coordinate system (mouse click-dragging, tick spacing, grid
line rendering, etc). The fix would require some refactoring, but I'd
love to do work on it with you. 

	A better place to start would be to code a proof-of-concept demo as a
standalone application. I created a Cartesian plotting demo easily
within 100 lines
(https://github.com/swharden/Csharp-Data-Visualization/blob/master/examples/2019-06-03-coordinate-system
[3]) and I think something like this could be expanded to support
nonlinear / non-orthogonal axes. Once we get a handle on how to do it
technically (and provide a good interface for it), we can then figure
out how to refactor ScottPlot to accomodate it. What do you think of
this idea? 

	A good place to start would be to create a similar app which: 

	* has a way to draw _points_ on the graph. This is easiest in my
experience.
 	* has a way to draw _lines_ on the graph. This is where I keep
getting overwhelmed with complexity. Grid lines will be unevenly
spaced and may curve.

	* allows the user select which coordinate system to use 

	* perhaps we would make a CoordinateSystem class and provide some
pre-made ones like cartesian and logarithmic, polar, but let the user
make their own with custom formulas if desired.
 	* I'm guessing functions like coordinate-to-pixel, drawing of lines,
and generation of ticks would all be handled inside these classes

	@Padanian [4] I'm looking forward to hearing your thoughts 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [5], or mute the
thread [6]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/41?email_source=notificationsu0026email_token=AB3I2BHCQQPFKTFKFR3PNXDP7XFPNA5CNFSM4IEASAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2A4AFA#issuecomment-511819796",
"url":
"https://github.com/swharden/ScottPlot/issues/41?email_source=notificationsu0026email_token=AB3I2BHCQQPFKTFKFR3PNXDP7XFPNA5CNFSM4IEASAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2A4AFA#issuecomment-511819796",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://en.wikipedia.org/wiki/Smith_chart
[2] https://github.com/swharden/ScottPlot/issues/29
[3]
https://github.com/swharden/Csharp-Data-Visualization/blob/master/examples/2019-06-03-coordinate-system
[4] https://github.com/Padanian
[5]
https://github.com/swharden/ScottPlot/issues/41?email_source=notifications&amp;email_token=AB3I2BHCQQPFKTFKFR3PNXDP7XFPNA5CNFSM4IEASAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2A4AFA#issuecomment-511819796
[6]

**Comment by Padanian** [comment]
![immagine](https://user-images.githubusercontent.com/7769348/61368520-5536fc00-a88e-11e9-9462-5dcf93fd85df.png)

Example of XYScatter with Y-axis rotated CW by 60°. I don't know how to rotate the frame axis thouh

**Comment by swharden** [comment]
This topic is a can of worms and attempts at implementation must snake through a lot of ScottPlot modules. For example, consider how we would draw grid lines and tick marks using polar coordinates...

![image](https://user-images.githubusercontent.com/4165489/62093937-3733a900-b249-11e9-938a-777e5ac09f3e.png)

Because of this, I think the best place to start is with a very simple sandbox application. It makes sense to try to add these features to ScottPlot only after plotting, grid lines, and tick marks work well in the sandbox application. An example sandbox application (currently configured for 2D Cartesian coordinates) is here:
https://github.com/swharden/Csharp-Data-Visualization/tree/master/examples/2019-06-03-coordinate-system

We can continue to explore this topic, but I'm going to close this issue until a working sandbox application demonstrates all the functionality we want to bring to ScottPlot. At that point we can re-open it and this issue will track its implementation.

**Comment by Padanian** [comment]
With the cartesian coordinates of grid lines endpoints, I could apply a matrix calculation to apply rototraslation of the grid. I think I can do that.

**Comment by swharden** [comment]
I added a cookbook example showing how to plot log-scale data:
https://github.com/swharden/ScottPlot/tree/master/cookbook#log-axis

![image](https://user-images.githubusercontent.com/4165489/72669139-5e02b900-39fc-11ea-90c2-10c336322635.png)
