### ISSUE TITLE
Heatmaps (Categorized and Continuous)

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#420]
**What can we do to make ScottPlot better?**
Perhaps a new plottable for heatmaps.

Including continuous heatmaps: 
![image](https://user-images.githubusercontent.com/8635304/82717485-9f7ccc80-9c59-11ea-9058-2228855dfd03.png)
As well as categorical heamaps:
![image](https://user-images.githubusercontent.com/8635304/82717491-ab688e80-9c59-11ea-9dfa-30688aeb89b9.png)

```cs
var heatmap = plt.PlotHeatmap(xs, ys, values, colourmap);
```

My experience with these plottables primarily comes from matplotlib.pyplot, both are implemented with `imshow`. However, in my opinion, categorical heatmaps are just tables with added colours, so perhaps continuous heatmaps ought to be their own plottable, and a new table plottable is created, which can optionally take a colourmap argument?

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by swharden** [comment]
@Benny121221 I'm really interested in this idea! I would definitely like to achieve this because right now I have a spectrogram library https://github.com/swharden/Spectrogram that doesn't have axis labels or interactivity, and supporting heatmaps in ScottPlot would make tasks like this achievable. Here are a few thoughts...

* I'm not entirely sure the best way to draw this
  * System.Drawing doesn't always render rectangles perfectly if they touch edge to edge. With anti-aliasing on you can see through them a bit.
  * Maybe the solution here is to render a totally new `Bitmap`, populate pixels based on the colormap, then the plottable could `Graphics.DrawImage()` to render that image onto the plot?
  * Optimal rendering might involve marshaled memory, and you may find some useful code there in my spectrogram demo 
* The scalebar could be a separate plottable, related to #388
* Let's support multiple colormaps with viridis being the default https://www.youtube.com/watch?v=xAoljeRJ3lU (good talk!)

Due to all the stuff I'm working on (#412) it might take me a while to move on this... do you want to give this one a shot? As long as we can keep it in the "experimental" category we could make it a real plottable, include it in the demo program, and incrementally improve upon it over time

**Comment by Benny121221** [comment]
I suspect a new bitmap is the simplest, from what I understand that's how matplotlib does it. As for the colourmaps I will look into yoinking viridis once I've got it sorted out, but for early development I'll probably have everything in grayscale, just because it's simple.

**Comment by Benny121221** [comment]
UC Berkeley has very kindly put several colourmaps (including viridis) over here: https://github.com/BIDS/colormap

Viridis is here: https://github.com/BIDS/colormap/blob/master/colormaps.py#L788
The only thing to do is multiply all of them by 255. Plus, most of the colourmaps are under a very friendly license (CC0). https://creativecommons.org/publicdomain/zero/1.0/legalcode

In my understanding these colourmaps: magma, inferno, plasma, and viridis are placed in the public domain in jurisdictions where copyright allows. In jurisdictions where this is not allowed, they are granted under a public license which grants all the rights of clause 1, should those rights be recognized by the jurisdiction in question.

i.e. Anyone can yoink those four colourmaps without so much as crediting them (although I suggest that we do)

**Comment by Benny121221** [comment]
Note to self, overflows can be beautiful:
![image](https://user-images.githubusercontent.com/8635304/82725689-d70c6880-9c9b-11ea-9188-5ae5b7fb646f.png)

**Comment by swharden** [comment]
@Benny121221 #424 is looking cool!

I think we should use a 2D array `double[,]` rather than `double[][]`. This constrains data to be rectangular, but I think this is a good constraint. What do you think?

> UC Berkeley has very kindly put several colourmaps (including viridis) over here: https://github.com/BIDS/colormap
> 
> Viridis is here: https://github.com/BIDS/colormap/blob/master/colormaps.py#L788
> The only thing to do is multiply all of them by 255. Plus, most of the colourmaps are under a very friendly license (CC0). https://creativecommons.org/publicdomain/zero/1.0/legalcode

In your research you may find colormap packages on NuGet, but I think we should avoid those to keep ScottPlot dependency-free.

I have a handful of colormaps here in C# you can probably modify to suit your needs:
https://github.com/swharden/Spectrogram/tree/master/src/Spectrogram/Colormaps

Once you figure out how you want to implement colormaps (as a C# class), we could write a python script to convert all matplotlib colormaps into C# classes. Assuming this is fine by matplotlib's license, it would be really convenient to use colormaps identical in color and name to those already used in an established plotting library. They have so many too https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html and I'm very impressed with their _perceptually uniform sequential colormaps_.

> In my understanding these colourmaps: magma, inferno, plasma, and viridis are placed in the public domain in jurisdictions where copyright allows. In jurisdictions where this is not allowed, they are granted under a public license which grants all the rights of clause 1, should those rights be recognized by the jurisdiction in question.
> 
> i.e. Anyone can yoink those four colourmaps without so much as crediting them (although I suggest that we do)

I'm fine with that, and a source code link to the source is useful as a reference as well as credit. I do something similar for the default plot colors.
https://github.com/swharden/ScottPlot/blob/463fc3e0c9345454b513c78d714f148fafad76ce/src/ScottPlot/Config/Colors.cs#L12-L15

**Comment by Benny121221** [comment]
> I think we should use a 2D array double[,] rather than double[][]. This constrains data to be rectangular, but I think this is a good constraint.

Yeah sure thing, I completely forgot that C# `T[][]` were jagged.

>  Assuming this is fine by matplotlib's license, it would be really convenient to use colormaps identical in color and name to those already used in an established plotting library.

matplotlibs license is complicated, as different parts of the project are under different licenses: https://github.com/matplotlib/matplotlib/tree/master/LICENSE, but I'll have a look

**Comment by Benny121221** [comment]
Google's Turbo is under Apache 2.0: https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html

https://gist.github.com/mikhailov-work/ee72ba4191942acecc03fe6da94fc73f

Turbo is very similar to Jet, but it doesn't seem to have some of the problems that Jet has.

The conditions of the license are pretty standard, you can do as you please with it as long as you don't use their trademarks, you list prominently any changes made, and you keep a copy of the original license.

**Comment by swharden** [comment]
Heatmaps are progressing nicely! Let's shift our conversation to #424 and I'll close this issue

**Comment by swharden** [comment]
We have some experimental code merged in the master branch now (#424)

There may be some utility in expanding the colormap module to let those colormaps also be used to color line plots to produce graphs like this:

![image](https://user-images.githubusercontent.com/4165489/83372829-4f99b600-a37b-11ea-8116-93889cbbbcd1.png)

**Comment by Benny121221** [comment]
> There may be some utility in expanding the colormap module to let those colormaps also be used to color line plots to produce graphs like this:

I don't know how applicable it is to line plots? But for vector fields I definitely think it's a good feature, since the magnitude of the vectors is scaled down it's helpful to represent it with colour

**Comment by swharden** [comment]
> I don't know how applicable it is to line plots? 

I use this a lot when I represent how a wave changes over time, so it might get some good use out there in the wild. Here are some recent examples of things I've worked on in matplotlib:

![image](https://user-images.githubusercontent.com/4165489/83376222-8386d280-a39f-11ea-94b3-ccd9e564c1c1.png)

![image](https://user-images.githubusercontent.com/4165489/83376235-8da8d100-a39f-11ea-9383-1b05b2afa06a.png)

**Comment by Benny121221** [comment]
I see, it seems like this should be a function akin to `ScottPlot.Config.GetColor` instead of something exclusive to line plots?

**Comment by swharden** [comment]
> I see, it seems like this should be a function akin to `ScottPlot.Config.GetColor` instead of something exclusive to line plots?

Actually I was thinking something similar. Maybe an `IColormap` could have methods to make it easier to pull RGB values.

```cs
(byte r, byte g, byte b) Lookup(byte value); // 0-255
(byte r, byte g, byte b) Lookup(double fraction); // 0-1.0
```

**Comment by swharden** [comment]
Maybe methods like those belong here?

https://github.com/swharden/ScottPlot/blob/01a2621d5e19b9dfad6f9768199f3dcf07d5509f/src/ScottPlot/Config/ColorMaps/Colormap.cs#L7-L15

**Comment by swharden** [comment]
I refactored the colormap module for my spectrogram project the other day. It's in the `1.1` branch. I haven't landed on an architecture I really like yet, but it might offer some ideas.
https://github.com/swharden/Spectrogram/tree/1.1/src/Spectrogram/Colormaps

**Comment by Benny121221** [comment]
#442 Adds the lookup functions.

I generally prefer interfaces to abstract classes, however interfaces do not allow default implementations in C#7. You can achieve this by having it inherit from another class which has the default implementations, as well as implement the interface, but it is perhaps overkill

**Comment by swharden** [comment]
> i.e. Anyone can yoink those four colourmaps without so much as crediting them (although I suggest that we do)

I found this question asked in 2007:
https://discourse.matplotlib.org/t/steeling-some-of-you-colormaps/7560

The response from John Hunter (the original author or matplotlib who died in 2012) essentially says it's okay to copy matplotlib colormaps as long as you check the source code to verify they aren't licensed by another group

**Comment by swharden** [comment]
I'll close this issue as the most recent conversation is happening in the issue #457 and PR #458
