### ISSUE TITLE
Scatter Plot data validation only occurs in the constructor

### ISSUE THREAD

**Issue by lefi7z** [swharden/ScottPlot#443]
When setting the `PlotScatter.xs' and '.ys' properties to `double[0]`, an initially well behaved `PlotScatter` instance crashes with said Exception when calling `PlotScatter.AxisAuto()` method, complaining about some "sequence without elements". 

I guess, the error originates in a call to `Linq.IEnumerable.Min()`. 

Setting the data fields to an empty array is an allowed operation and should not invalidate the instance. Therefore, this is definitely not the intended behaviour.

see #309

**Comment by swharden** [comment]
Hi @lefi7z, thanks for pointing this out! To re-state this problem, after plotting the user can assign to a scatter plot's `xs` and `ys` in such a way as to cause an exception (because validation only occurs when these data are provided in the constructor).

This topic (externally modifying `xs` and `ys` to produce a bad state) was recently discussed in #145, so I think it deserves some attention. 

A good solution here may be to intercept assignments to these two properties and perform error checking to ensure they are not null, they contain elements, and they contain the same number of elements. Perhaps a better solution is to make these properties private and add methods to update them and perform validation (like `SignalConst`). These rules should also apply to errorbar data.

Thanks again for raising this issue @lefi7z, I'll see what I can do here...

**Comment by lefi7z** [comment]
Hi @swharden, thanks for the quick answer. I just read #415 and like the idea of a `ScatterList()` plotitem. I see two use cases where someone might be tempted to set the `.xs` property in the first place:

1. (fast) update data in a `ConstSignal()` plot (like an oscilloscope does).
2. append data one point at a time to a time-series plot.

For point 1. I don't know if it actually makes it any faster setting the property than simply creating a new `ScatterPlot()` instance. I remember that point 2. has been discussed before and that there is another solution to this. But adding elements to a `List<>` would be a very language-compliant way to achieve this.

**Comment by swharden** [comment]
The jump from ScottPlot 4.0 to 4.1 will introduce breaking changes, and I think the best way to handle plottable data mutability is to make all plottable data arrays private and have `UpdateData()` methods which perform validation. SignalConst already does this, albeit for advanced reasons.

Validation could be done on the existing code by intercepting the assignments to public properties, but I think requiring the user to call a method is a better opportunity to provide documentation (in the form of argument names and summary strings) and will result in more readable code in the long run.

I'll close this issue for now, but this topic will be in the forefront of my mind as I internally begin to refactor the plottable modules 👍
