### ISSUE TITLE
legend shadow

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#45]
@Padanian you did an awesome job adding legend location functionality (#39). Do you think a shadow would be good to have too? We are already drawing a solid frame so it doesn't seem like it would be hard to implement... maybe just a bool to turn it on and off?

Let's make the shadow fall to the lower right so we don't have to go through the trouble of making a shadowLocation object :see_no_evil:

If you think it's over the top we can probably let it go. I just thought it might be a nice touch! It would take a few lines here:
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L167-L172

Some examples:
https://www.google.com/search?q=matplotlib+legend+shadow&tbm=isch

**Comment by Padanian** [comment]
Sure! Not that complicated.  I'll give it a look

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Mon, 22 Jul 2019 22:25:59 +0000 (UTC)
Oggetto:[swharden/ScottPlot] legend shadow (#45)

	@Padanian [1] do you think this is worth implementing? We are already
drawing a solid frame so it doesn't seem like it would be hard to
implement... maybe just a bool to turn it on and off? 

	Let's make the shadow fall to the lower right so we don't have to go
through the trouble of making a shadowLocation object 🙈 

	If you think it's over the top we can probably let it go. I just
thought it might be a nice touch! It would take a few lines here:
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L167-L172
[2] 

	Some examples:
https://www.google.com/search?q=matplotlib+legend+shadow&tbm=isch [3] 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [4], or mute the
thread [5]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/45?email_source=notificationsu0026email_token=AB3I2BGB2V446OYY4ZMLZN3QAYXW7A5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HAYPOYQ",
"url":
"https://github.com/swharden/ScottPlot/issues/45?email_source=notificationsu0026email_token=AB3I2BGB2V446OYY4ZMLZN3QAYXW7A5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HAYPOYQ",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/Padanian
[2]
https://github.com/swharden/ScottPlot/blob/dba76dd07a61f910c9d034b8b42474068733670a/src/ScottPlot/Renderer.cs#L167-L172
[3]
https://www.google.com/search?q=matplotlib+legend+shadow&amp;tbm=isch
[4]
https://github.com/swharden/ScottPlot/issues/45?email_source=notifications&amp;email_token=AB3I2BGB2V446OYY4ZMLZN3QAYXW7A5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HAYPOYQ
[5]

**Comment by Padanian** [comment]
Pull request submitted.

**Comment by swharden** [comment]
referencing pull https://github.com/swharden/ScottPlot/pull/46 - Thanks @Padanian you work so fast!

I glanced over it and it it looks perfect. I lol'd when I saw you implemented dropShadowDirection - icing on the cake! I'll review and merge in the next day or two. Thanks again!

**Comment by swharden** [comment]
This shadow looks great! Totally worth it. Should it be on by default?

with shadow | without shadow
---|---
![image](https://user-images.githubusercontent.com/4165489/61748644-c3882c80-ad6e-11e9-9420-03a6d18cadfc.png) | ![image](https://user-images.githubusercontent.com/4165489/61748635-bff4a580-ad6e-11e9-8289-412ee65bc057.png)

**Comment by swharden** [comment]
Thanks again @Padanian this looks great https://github.com/swharden/ScottPlot/pull/46

**Comment by Padanian** [comment]
Thanks. Your appreciation is valuable to me. 

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Tue, 23 Jul 2019 21:25:14 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] legend shadow (#45)

	This shadow looks great! Totally worth it. Should it be on by
default? 

		WITH SHADOW
 		WITHOUT SHADOW

		 [1]
 		 [2]

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [3], or mute the
thread [4]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/45?email_source=notificationsu0026email_token=AB3I2BGDUW4TTMJ3U2OWHPLQA5ZLFA5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2UPNYQ#issuecomment-514389730",
"url":
"https://github.com/swharden/ScottPlot/issues/45?email_source=notificationsu0026email_token=AB3I2BGDUW4TTMJ3U2OWHPLQA5ZLFA5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2UPNYQ#issuecomment-514389730",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1]
https://user-images.githubusercontent.com/4165489/61748644-c3882c80-ad6e-11e9-9420-03a6d18cadfc.png
[2]
https://user-images.githubusercontent.com/4165489/61748635-bff4a580-ad6e-11e9-8289-412ee65bc057.png
[3]
https://github.com/swharden/ScottPlot/issues/45?email_source=notifications&amp;email_token=AB3I2BGDUW4TTMJ3U2OWHPLQA5ZLFA5CNFSM4IF5QOKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2UPNYQ#issuecomment-514389730
[4]

**Comment by fraengers** [comment]
The setting is there, with a default value, but besides that nothing is done with it:
https://github.com/swharden/ScottPlot/blob/4b48e577ed30436657c76a812c07bfb452471016/src/ScottPlot/Plot/Plot.Legend.cs#L19

I noticed this while setting the background of the legend (semi)transparent. Then you see the shadow rectangle and cannot turn it off:
![grafik](https://user-images.githubusercontent.com/65356940/96363730-4183e080-1136-11eb-8441-8253ee03faaf.png)
