### ISSUE TITLE
Ticking strategy

### ISSUE THREAD

**Issue by Orace** [swharden/ScottPlot#456]
In linear scale, around 0 (for clarity), the current ticking strategy give steps size of 10x10<sup>k</sup>, 5x10<sup>k</sup>, _2.5x10<sup>k</sup>_, 1x10<sup>k</sup>.
With a constant minor sub-division count of 5 (4 minor ticks).

The algorithm is straightforward: while you can add ticks, add them by dividing by 2, 2, 2.5 the step size.

It's hard-coded in a private method :

https://github.com/swharden/ScottPlot/blob/08d42d0447a2cf0097f86c19969f973b0a71fa44/src/ScottPlot/Config/TickCollection.cs#L191-L211

My proposition is to open this feature by creating a new interface `ITickSpacingStrategy` that expose a single method `double GetIdealTickSpacing(double low, double high, int maxTickCount)`.

The `TickSpacingStrategy` will be passed in the `Settings` and the current strategy will be used to implement `DefaultTickSpacingStrategy` witch is a singleton.

IMO, the _2.5_ step size is ugly. 10 is divisible by 10, 5, 2, 1. And those step size should be used.
The algorithm is a little bit less intuitive:

![2020-06-10_19h48_06](https://user-images.githubusercontent.com/9695349/84300978-554d8380-ab53-11ea-9b9c-fd328dbbf1b8.png)

The subdivision count is:
 - 10 for steps of size 10x10<sup>k</sup>
 - 5 for steps of size 5x10<sup>k</sup>
 - 2 for steps of size 2x10<sup>k</sup>

This can be implemented as a new `OneTwoFiveTickSpacingStrategy` (I'm open for good class names).

**Comment by Orace** [comment]
[Here](https://github.com/Orace/ScottPlot/tree/ITickSpacingStrategy) an example of introduction of `ITickSpacingStrategy` and a WpfDemo with 2 different strategy (the second is dumb, I don't have the time right now). Did it in 2 hours don't be afraid to put in in the garbage.

**Comment by swharden** [comment]
Hey @Orace, I made an `ExperimentalTicks` type of plottable object to demonstrate how you can begin experimenting with new tick systems _without modifying any existing code_. That last point is an important one, because I'd much rather invite contributors to bring in some fresh ideas rather than have to deeply study the current implementation to get started.

![ticktester](https://user-images.githubusercontent.com/4165489/84582852-8c27d180-adbf-11ea-88e2-fe3eb83bc3ae.gif)


### Experimental Tick Developer Application

The code underlying the demo application is very simple. It also shows how you can customize render options externally (e.g., from the GUI). This will be useful when testing things like user-defined tick density.

https://github.com/swharden/ScottPlot/blob/c73d93ff97a0cb4300145aa7dd5b1f37b1ee3ea7/dev/FormsPlotSandbox/FormExperimentalTick.cs#L1-L39

### Experimental Tick `Plottable`

This example class was made for maximum readability, and it produces some pretty dumb ticks. I'm thinking you can fully implement a really intelligent tick system just by modifying this class. Probably the simplest thing to do is _duplicate_ this class, name it something that sounds good to you, then we can compare/contrast different tick systems as development progresses.

https://github.com/swharden/ScottPlot/blob/c73d93ff97a0cb4300145aa7dd5b1f37b1ee3ea7/src/ScottPlot/plottables/ExperimentalTicks.cs#L1-L67

### My current effort

I'm currently focusing on some low-level refactoring of the rendering system. It won't affect your experimentation with the tick system, but that large amount of work is why I'm not free to help more directly with this topic at this time.

### Collaboration?

I noticed at the same time #456 was opened by @Orace and #394 was opened by @Minu476, so I wanted to connect these dots in case your goals may be aligned on this one!

**Comment by swharden** [comment]
I think this is in a pretty good spot now in that anyone who wants to can experiment with an alternative tick algorithm. Once demonstrated to be superior to the existing one, we can modify the existing tick system to use the new one.

I'll close this issue for now, but if you decide give it a go feel free to create an experimental tick system and make a pull request and I'll take a look! 👍
