### ISSUE TITLE
axis label gets overlapped when tick labels increase in length

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#47]
I am experiencing overlapping of the axis labels with the axis markers/numbers at certain zoom levels (when zoomed in).
I wonder if it is possible to fix this problem, like auto increase the gap between axis and its label based on the axis markers' length...? I attach two screenshots, the first showing no zoom, the second the zoomed state.
Thanks!
Best Regards,

edit: using Winform, ScottPlot 3.0.6

![ScottPlot_axis_label_ok](https://user-images.githubusercontent.com/51174971/61712888-99774000-ad57-11e9-8435-3cbc7372f0b3.png)
![ScottPlot_axis_label_Overlaps](https://user-images.githubusercontent.com/51174971/61712899-a005b780-ad57-11e9-8faa-8e189b594aac.png)

**Comment by swharden** [comment]
Hi @bukkideme thanks for letting me know about this issue!

You can get the extra space you need with something like:

```cs
plt.TightenLayout(padding: 20)
```

This is demonstrated in the cookbook: https://github.com/swharden/ScottPlot/tree/master/doc/cookbook#extra-padding

... however I'd certainly call this a bug! I'll update the code to automatically detect this problem and correct it when it arises. I'll issue this release on NuGet probably this weekend. Thanks again for bringing this issue to my attention!

**Comment by bukkideme** [comment]
Thanks for the workaround info and the later modification!

**Comment by Padanian** [comment]
Scott, once fixed, I'll pull it and start working on the
non-orthogonal axis (#41)

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Subscribed" 
Inviato:Tue, 23 Jul 2019 12:58:45 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] Axis label overlaps with axis markers
(#47)

	Hi @bukkideme [1] thanks for letting me know about this issue! 

	You can get the extra space you need with something like:
plt.TightenLayout(padding: 20) 

	This is demonstrated in the cookbook:
https://github.com/swharden/ScottPlot/tree/master/doc/cookbook#extra-padding
[2] 

	... however I'd certainly call this a bug! I'll update the code to
automatically detect this problem and correct it when it arises. I'll
issue this release on NuGet probably this weekend. Thanks again for
bringing this issue to my attention! 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [3], or mute the
thread [4]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/47?email_source=notificationsu0026email_token=AB3I2BCLCM6J2MLPAI6I6S3QA3577A5CNFSM4IGD42Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TAYQA#issuecomment-514198592",
"url":
"https://github.com/swharden/ScottPlot/issues/47?email_source=notificationsu0026email_token=AB3I2BCLCM6J2MLPAI6I6S3QA3577A5CNFSM4IGD42Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TAYQA#issuecomment-514198592",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/bukkideme
[2]
https://github.com/swharden/ScottPlot/tree/master/doc/cookbook#extra-padding
[3]
https://github.com/swharden/ScottPlot/issues/47?email_source=notifications&amp;email_token=AB3I2BCLCM6J2MLPAI6I6S3QA3577A5CNFSM4IGD42Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TAYQA#issuecomment-514198592
[4]

**Comment by bukkideme** [comment]
Another problem, somewhat related to this. After zooming, the xaxis tick labels can also become overlapped. I imagine, when you fix the yaxis bug, you could do similar fix for the xaxis?
I imagine, in this case an automatic re-adjusting of the plotting frequency of the tick labels could do the fix...? 
Screenshot:
![xaxis_overlapped](https://user-images.githubusercontent.com/51174971/61714831-173d4a80-ad5c-11e9-839f-0d16af0d669b.png)

**Comment by swharden** [comment]
The easiest way to recreate this bug is to zoom out like crazy

![image](https://user-images.githubusercontent.com/4165489/61749688-54f89e00-ad71-11e9-9b89-1c5ca7f44d9a.png)

**Comment by Padanian** [comment]
I can fix this "labels too wide problem" if that's ok for Scott.
And will add up the scaling factor label as requested in #54

**Comment by Padanian** [comment]
![immagine](https://user-images.githubusercontent.com/7769348/61997326-3e6b8300-b0a0-11e9-9cef-97f2dd955272.png)

This is what I came up with

**Comment by swharden** [comment]
Interesting concept! For scientific publications I often set the tick font size to the minimum allowed by a journal (usually 8pt). For this reason I'm less inclined to use more than one tick font size, and especially one smaller than the regular ticks.

I'm still thinking that an ideal solution would be more similar to the matplotlib style (touched on in #54). I also think it will produce more consistent label widths than trying to stick exponential notation in the labels themselves...

![image](https://user-images.githubusercontent.com/4165489/61997521-9e4a3580-b070-11e9-94ff-06c857aaa51c.png)

**Comment by swharden** [comment]
this issue will be corrected when the tick module is refactored (issue #57)
