### ISSUE TITLE
How to recover the space between X scale and lower border when the X label is empty

### ISSUE THREAD

**Issue by dprevato** [swharden/ScottPlot#486]
I've made a demo project, [https://github.com/dprevato/WinformScottPlotMultiChart](url), to explain why I have such a curiosity... and many others too :). 
In short: I have a chart, with the X axis label empty. However, I notice that the space between the X scale and the lower border of the chart is still there. My question is: is there a way to recover the unused space between the X scale and the lower border of the chart?

**Comment by swharden** [comment]
Hey @dprevato 

You can tweak the layout with the `Layout()` method. Be sure to call `Render()` after these adjustments to ensure the latest layout gets redrawn on the screen.

```
formsPlot1.plt.Layout(yScaleWidth: 80, titleHeight: 50, xLabelHeight: 20, y2LabelWidth: 20);
formsPlot1.Render();
```

I suspect if you set `xLabelHeight` to `0` you can recover the space below the graph. You may find other arguments useful too. Let me know if this does the trick!

**Comment by swharden** [comment]
... oh wow, it looks like https://github.com/dprevato/WinformScottPlotMultiChart is pretty advanced! I'll review this project soon when I have a bit more time to study it in detail. Thanks for creating it and documenting it! I look forward to reviewing it soon 👍

**Comment by dprevato** [comment]
@swharden I applied `Layout()` method like you told me, and it works like a charm! I reduced also the value for titleHeight to 10 when the chart has no title. I'm trying to realize a Winforms template, for putting a variable number of charts, taking the data from a database...  I'm very happy that you appreciate it :)

**Comment by swharden** [comment]
Hey @dprevato,

I had a chance to take an even closer look today at your repo. It's very interesting and raises a lot of good ideas and thoughts for directions I can improve ScottPlot by adding a similar multi-plot chart control.

As an aside, I found this modification helpful:

```cs
      private void GetAllReadings()
      {
          string filePathSameFolder = @"Readings.txt";
          string filePathRepo = @"../../Readings.txt";

          if (File.Exists(filePathSameFolder))
              AllData = File.ReadAllLines(filePathSameFolder).Select(FromTsv).ToList();
          else if (File.Exists(filePathRepo))
              AllData = File.ReadAllLines(filePathRepo).Select(FromTsv).ToList();
          else
              throw new FileNotFoundException("cannot locate data file");
      }
```

I think my large scale impression is that something like this is a direction I'd indeed like to go. A user control specifically for charting has been on my wish list for some time. I often reference ClampFit, a scientific signal recording package, as a model I'd like to design a charting control after e.g., https://github.com/swharden/ScottPlot/issues/358. Sometimes this is called a strip chart.

However, building complex GUI code that depends on core ScottPlot code may be a bit risky... The more I write high-level code that depends on fixed ScottPlot behavior, the less flexible the core ScottPlot library becomes. The are still some deep changes I'd like to make to ScottPlot (e.g., #412) especially related to layouts, multi-plots, and axis manipulations which would break the charting controls if I make those too early...

I think my plan here will be to try to clear out the urgent issues and core feature requests (luckily they seem to be slowing down), then focus on refactoring ScottPlot's internals (#412), then work upward and start making higher-level controls with advanced features. Among these are strip charting (and programmatic creation of multiple charts, taking inspiration from your repo) and improved controls for financial charting. 

Thanks again for creating and sharing your repo! I found it really thought-provoking, and I look forward to being able to loop back around and incorporate these higher-level design ideas before too long. I'll close this issue because it looks like your pressing issue was solved with `Layout()`, but I'm happy to have https://github.com/dprevato/WinformScottPlotMultiChart (and now https://github.com/swharden/WinformScottPlotMultiChart) as a reference for future work!
