### ISSUE TITLE
customizable mouse functions

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#49]
My question is that, would it be difficult to add a new method to the ScottPlotUC User Control, which could give us access to disable/modify the pre-programmed mouse bindings?
In some cases, I would like to program additional features with mouse events for these very handy controls, but the existing mouse events do not let it happen.
Second question, what is the most simple workaround to custom handle for example mouse left double clicks?
thanks!

**Comment by Padanian** [comment]
In C#

```
        this.scottPlotUC1 = new ScottPlot.ScottPlotUC();

        public Form1()
        {
            this.scottPlotUC1.DoubleClick += new System.EventHandler(this.ScottPlotUC1_DoubleClick);
        }

        private void ScottPlotUC1_DoubleClick(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }
```

In vb.net
```
    Public Sub New()
        AddHandler Me.scottPlotUC1.DoubleClick, New System.EventHandler(AddressOf Me.ScottPlotUC1_DoubleClick)
    End Sub

    Private Sub ScottPlotUC1_DoubleClick(ByVal sender As Object, ByVal e As EventArgs)
        Throw New NotImplementedException()
    End Sub
```

or even easier in vb.net (I love vb.net)
```
    Public WithEvents ScottPlotUC1 As New ScottPlot.ScottPlotUC

    Public Sub ScottPlotUC1_DoubleClick(ByVal sender As Object, ByVal e As EventArgs) Handles ScottPlotUC1.DoubleClick
        Throw New NotImplementedException()
    End Sub
```

**Comment by swharden** [comment]
> would it be difficult to add a new method to the ScottPlotUC User Control, which could give us access to disable/modify the pre-programmed mouse bindings?
> In some cases, I would like to program additional features with mouse events for these very handy controls, but the existing mouse events do not let it happen.

@bukkideme I'm just about to refactor the user control (https://github.com/swharden/ScottPlot/issues/43) so this would be a good time to add this functionality. I'm personally unhappy with how the right-click menu isn't easy to extend.

What functionality would you like to be able to disable or change? What type of functionality are you trying to add? Getting an idea of your use case may help me design something more versatile. 

> Second question, what is the most simple workaround to custom handle for example mouse left double clicks?

@Padanian nailed it! The user control itself itself has a list of events you can attach functions to.

**Comment by AteCoder** [comment]
would it make sense to implement handlers, such as PbPlot_MouseMove, entirely in Overridable/virtual methods such as OnMouseMove or OnChartMouseMove? this would enable the implementation of new behavior while, optionally, keeping existing behavior intact.

**Comment by Padanian** [comment]
I can't see the scenario that otherwise wouldn't be satisfied with
existing Methods or inherited Event handlers. 
The only thing useful on a chart is zooming and panning on it, and
this is already possible.

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Wed, 24 Jul 2019 23:40:37 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] customizable mouse functions (#49)

	would it make sense to implement handlers, such as PbPlot_MouseMove,
entirely in Overridable/virtual methods such as OnMouseMove or
OnChartMouseMove? this would enable the implementation of new behavior
while, optionally, keeping existing behavior intact. 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/49?email_source=notificationsu0026email_token=AB3I2BHVNSIWOIXLHPBYGI3QBDR63A5CNFSM4IGO5UH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2X5BMY#issuecomment-514838707",
"url":
"https://github.com/swharden/ScottPlot/issues/49?email_source=notificationsu0026email_token=AB3I2BHVNSIWOIXLHPBYGI3QBDR63A5CNFSM4IGO5UH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2X5BMY#issuecomment-514838707",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1]
https://github.com/swharden/ScottPlot/issues/49?email_source=notifications&amp;email_token=AB3I2BHVNSIWOIXLHPBYGI3QBDR63A5CNFSM4IGO5UH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2X5BMY#issuecomment-514838707
[2]

**Comment by bukkideme** [comment]
> @bukkideme I'm just about to refactor the user control (#43) so this would be a good time to add this functionality. I'm personally unhappy with how the right-click menu isn't easy to extend.
> 
> What functionality would you like to be able to disable or change? What type of functionality are you trying to add? Getting an idea of your use case may help me design something more versatile.
> 
> > Second question, what is the most simple workaround to custom handle for example mouse left double clicks?
> 
> @Padanian nailed it! The user control itself itself has a list of events you can attach functions to.

Thanks @Padanian  for the suggestion!
@swharden : well, for example I wanted to add a simple XY coordinate value readout feature by mouse double click. 
Another thing which comes to my mind now as extra function, that lots of software solution for Graphs/Charts use the so called cursor approach. Cursor can be a horizontal/vertical line or also an XY point which we can drag/move by the mouse. Ever considered adding such functionality? But I think it is also important to keep the package simple and lightweight? So might be not a good idea to put every single idea into it, but keep possibility to program it as an extra for it :)

**Comment by AteCoder** [comment]
Implementing PbPlot_MouseMove event handler using overridable/virtual methods is the 'correct' framework way of implementing events. For example, rather than implementing form_load or form_show, in an inherited form, the framework calls for overriding onload and onshown.
________________________________

**Comment by Padanian** [comment]
How would that add anything useful for the user?

**Comment by swharden** [comment]
> Another thing which comes to my mind now as extra function, that lots of software solution for Graphs/Charts use the so called cursor approach. Cursor can be a horizontal/vertical line or also an XY point which we can drag/move by the mouse.

Let's say you had a crazy graph and you wanted to figure out exactly where a point was in X/Y coordinates - turning the cursor into cross-hairs with a location readout could be helpful.

... but this could be implemented without changing any of the current mouse functionality: We could add a "display cursor coordinates" checkbox to the right-click menu, and when it's enabled the cursor always has cross hairs and displays coordinates. I guess this wouldn't be something the user would override to control, but rather a feature we could add to ScottPlot.

I am working toward keeping the [user control](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/ScottPlotUC.cs) as thin an light as possible. My emerging philosophy is that if we keep it simple enough, users who want custom functionality can just to create their own user control (rather than trying to override methods in the current one).

**Comment by Padanian** [comment]
It's easy to provide a tooltip with the X/Y values, and it is possible
to change Cursor to crosshair when MouseHover over the instance
programmatically.

**Comment by bukkideme** [comment]
Just a thought regarding to the right-click menu. What about implementing a built-in data export feature? Simply exporting XY curve(s) data column-wise into a TAB delimited ASCII file. If we already have a "Save Image" option, why not the raw data as well?

**Comment by swharden** [comment]
While we make it possible to override methods in the user control, the user control is being actively developed isn't really stable yet. Therefore, I wouldn't recommend developing an application around the current user control.

On the other hand, the user control is fewer than 150 lines:
https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/ScottPlotUC.cs

If you desire functionality other than left-click-drag pan, right-click-drag zoom, I'd suggesting creating your own version of this control. This way you'll have full control over its functionality, and you'll know it will continue to work even as the ScottPlot user control changes as it matures.
