### ISSUE TITLE
Avalonia Support?

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#496]
**Issue to be solved:**
Supporting Avalonia would allow interactive plots on Linux and Mac. If you're not familiar, Avalonia feels very similar to WPF, but with a few features absent. Avalonia is in pre-release, so that could well change.
* If this issue relates to an existing pull request, link to it here.

I have a branch on my fork with a working Avalonia UserControl. Because of the aforementioned absent features, as well as the interest in cross-platform compatibility, not all the same features that WPF and WinForms enjoy are present.

The branch is available here: https://github.com/Benny121221/ScottPlot/tree/avalonia

I can understand that you may be hesitant to support another platform, but I personally believe there is merit in being available on Linux and Mac. Plus, Avalonia feels *very* similar to WPF, most code can be copy-pasted and then find-and-replaced.

Let me know if you want me to open a PR. If you don't want to enhance your maintenance burden, then I'm happy to release an unofficial Avalonia UserControl, as I have a personal need for Linux support.
* If this issue relates to a patch, paste the contents of the patch here.

New contributors should review CONTRIBUTING.md:
https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md

**Comment by Benny121221** [comment]
It turns out that Avalonia is more similar to WPF than I had thought, the codename for WPF was Avalon. Wild.

**Comment by swharden** [comment]
Hey @Benny121221! 

I want to study this topic in a little more detail before I give a thorough response, but perhaps I'll outline my thinking at this point and get your reflection of my thought process. I'm lightly aware of Avalonia (https://avaloniaui.net/), and understand it is already being used to write cross-platform UIs for .NET applications. However, I'm also aware that later this year Microsoft is officially releasing MAUI (https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) which will be used to write cross-platform UIs for .NET applications. It looks to be a lot like Xamarin.Forms, which in my head I treat as "WPF for mobile".

Knowing MAUI is around the corner, I was planning on pursuing support for it when it's released. It looks like MAUI preview 1 is scheduled for late 2020, with a full release targeted at 2021. https://github.com/dotnet/maui/wiki/Roadmap 

What do you think about the future of Avalonia balanced with the emergence of MAUI?

All that said, if you have an isolated user control that supports Avalonia without modifying the rest of the code base, which it seems like you do (https://github.com/Benny121221/ScottPlot/tree/avalonia/src/ScottPlot.Avalonia), perhaps adding this into the ScottPlot NuGet package is a no-cost way to support Avalonia now, leaving the door open to support MAUI later as it matures?

Interested in hearing your thoughts!

**Comment by Benny121221** [comment]
> What do you think about the future of Avalonia balanced with the emergence of MAUI?

I think Avalonia will stick around, it already has a userbase, but I don't think it will ever compete on features with MAUI. Avalanonia is *still* in prerelease after many years, whereas MAUI is targeting an aggressive GA release for November 2021.

> All that said, if you have an isolated user control that supports Avalonia without modifying the rest of the code base, which it seems like you do (https://github.com/Benny121221/ScottPlot/tree/avalonia/src/ScottPlot.Avalonia), perhaps adding this into the ScottPlot NuGet package is a no-cost way to support Avalonia now, leaving the door open to support MAUI later as it matures?

I do have a control, some features are unfortunately absent, but nothing I would consider critical. It may make sense to create an Avalonia demo, but I haven't gotten round to that. I think supporting Avalonia and MAUI when it comes out is a good idea, and it was surprisingly easy to port this to Avalonia. Fingers crossed it's as easy when MAUI comes around.

From a maintenance point of view, Avalonia and MAUI obviously place more of a burden than there would be before, especially as Avalonia is in prerelease. But at least I'm not suggesting you go full OxyPlot and support 20 different platforms including SilverLight.

**Comment by Benny121221** [comment]
Also, should I take this as an invitation to open a PR, or should I wait?

**Comment by FoggyFinder** [comment]
> What do you think about the future of Avalonia balanced with the emergence of MAUI?

I suppose MAUI won't have support for Linux. MAUI is just evolution of XF.

Avalonia is a totally OS project that obviously doesn't have such good financial support.

Nevertheless Avalonia is getting better and better with every version.

Also, supporting Avalonia won't cost much: as you could see it's really easy to convert to Avalonia.

**Comment by Benny121221** [comment]
Oof, I had assumed that they would support Linux, given that the whole point seems to be multiplatform comparability. But no, it seems like just Windows and MacOS (plus the mobile OSes). Maybe Linux is in a later release.

I know this library is targeted a lot towards the scientific community, so @swharden might be able to weigh in on how valuable Mac support is. I know personally that Windows and Linux (and not just Linux on CLI) see a lot of use. I don't expect that mobile platforms are a high priority, but I don't see harm in supporting them if we get it for free.

Even if Mac isn't a platform worth targeting and Linux support isn't added, provided MAUI proves to be a good platform for Windows development it may be worth pursuing. ScottPlot already maintains two Windows-only platforms, if it looked like MAUI were to overtake WinForms or WPF it would likely make sense to support the new platform, even if only to support more Windows developers.

**Comment by swharden** [comment]
Hey @FoggyFinder thanks for your insight here!

It seems like the core message is that Avalonia is more or less usable now, and if it's low cost to support it's worth exploring. Same thing with MAUI, when it comes online. @Benny121221 I'll study your branch in more detail this weekend! A potential concern is how to test it. I use Azure pipelines which gets the job done with NUnit tests from a console application, but cross-platform GUI testing seems a bit more hairy. What do you think?

With regard to MAUI support on Linux, word on the street is that Microsoft isn't going to micro-manage that project. It'll be left to the Linux community to provide platform support for MAUI. This sort of makes sense, since there's not an official or uniform window manager for Linux, but my impression is that the fact Microsoft isn't making it doesn't mean that it won't get made. I agree this is a wildcard though, so I like the idea of supporting Avalonia and exploring MAUI as it matures. Same for WinUI, which we haven't even talked about yet...

While we're at it, a control for UWP seems practical, testable, and immediately usable, so perhaps we could consider this in parallel too 🤔

**Comment by swharden** [comment]
I'm definitely thinking out loud with this one, but before this project explodes into supporting a bunch of different GUI frameworks (like OxyPlot), maybe we should take a step back and consider if a facade control module should be created now to make it easier to develop all these new controls, and also to support changes across all these as ScottPlot matures. Issues like display scaling can be pretty thorny, but it may be nice to isolate that logic into a GUI-platform-independent module so we can solve the problem once and all controls benefit from it. Same thing goes with mouse tracking. There seems to be more logic than necessary in the WinForms and WPF controls, which is fine for now, but will really scale-up in complexity as we add support for more platforms 🤔

**Comment by Benny121221** [comment]
> cross-platform GUI testing seems a bit more hairy. What do you think?

I think the closest thing to the automated sort of routine you can have is a checklist, something like this:

- [ ] Displays correctly on Windows
    - [ ] Pan and zoom works correctly
- [ ] Displays correctly on Linux
    - [ ] Pan and zoom works correctly
- [ ] Displays correctly on MacOS
    - [ ] Pan and zoom works correctly

Have that be required on any PR which touches the Avalonia controls. Now actually testing on each platform could be fun, Windows and Linux both play nicely in VMs for people who don't have a machine with them installed. Mac... plays its own game. I don't have a Mac, and I can take a look at shoehorning it into a VM, but it could be difficult.

In principle, the point of a cross-platform framework like Avalonia, is to avoid platform-specific issues. In principle, testing changes out on one platform should be enough. Of course, that's not always the case, but it may be better given the difficulties, to just assume that it holds true until an OS-specific issue appears.

**Comment by Benny121221** [comment]
>  It may be nice to isolate that logic into a GUI-platform-independent module so we can solve the problem once and all controls benefit from it.

Agreed, such a module would make porting much easier

**Comment by swharden** [comment]
> Agreed, such a module would make porting much easier

Sounds like we're both in favor! I guess that means **the next step toward supporting Avalonia is creating a `ScottPlot.Control` module in the .NET Standard library**. Such a module would probably have... methods for mouse actions like move and click, getting the thing under the cursor (grid coordinate, plottable, or nearest point of a plottable), and perhaps keyboard flags to set/clear when the user presses/releases shift, alt, and ctrl?

I'll probably toy with this sooner than later unless you want to take a stab at the architecture! Regardless of which of us make the first move here, outlining function signatures and/or creating a UML diagram seems like the best place to start before jumping into coding it all up so we can look at it and see if does what we'd like it to 🤔

**Comment by Benny121221** [comment]
I have refactored the Avalonia user control in my branch. I haven't touched the WPF or WinForms, because I don't know if you have any suggestions for adjusting the structure? That way we avoid refactoring again. Let me know what you think.

**Comment by Benny121221** [comment]
> I think using double for all value types makes sense, because while lots of graphics libraries only support int or float coordinates it would be nice to future-proof this module, and the down-casting can be done at the level of the controls themselves (e.g., int for WinForms and float for WPF).

Oh, I didn't see that. I use `System.Drawing.PointF` everywhere and there's a method to convert from `Avalonia.Point` which the mouse event handlers use.

`PointF` uses FP32, but that should be fine. Quake used float for mouse settings like sensitivity[[1](https://github.com/id-Software/Quake/blob/master/WinQuake/cvar.h#L56:L64)], and that game's a masterpiece. If John Carmack doesn't need more than 7 digits of precision then we should be fine. I'm not exactly hitting flickshots or 40% LG in a plotting window. Plus, we save 8 whole bytes per coordinate using FP32 instead of FP64.

**Comment by swharden** [comment]
Mouse actions are pretty infrequent (think about refresh rates) so there's not really a performance consideration here.

The reason I got weary about `float` is because the difference in precision between `float` and `double` actually makes a big difference when you work with `DateTime.ToOADate()` values at time scales on the order of seconds and milliseconds. This broke before in #351 for this reason. If we're careful we can pass `float` into mouse operations, as long as scales are carefully zoomed and panned using `double` mathematics under the hood 🤔 

That was my line of thinking there!

https://github.com/Benny121221/ScottPlot/blob/avalonia/src/ScottPlot.Control/ControlBackend.cs is looking pretty good on first pass inspection, though I'll definitely want to study this in greater detail when I have a little more time to work on it. I suspect this module can live inside the ScottPlot project, and not require a separate project or NuGet package. Do you agree?

I want to put some high quality focused time into this, but I'm a bit overwhelmed with work-related stuff for the next few days, so progress may be slow for a bit. I'm excited to study this further though! Thanks for all your work on this!

**Comment by Benny121221** [comment]
> Mouse actions are pretty infrequent (think about refresh rates) so there's not really a performance consideration here.

Yeah I was being facetious

> The reason I got weary about float is because the difference in precision between float and double actually makes a big difference when you work with DateTime.ToOADate() values at time scales on the order of seconds and milliseconds.

Fair enough, I assumed OLE dates were normal (i.e. Unix dates that start in 1900 instead of 1970)

> I suspect this module can live inside the ScottPlot project, and not require a separate project or NuGet package. Do you agree?

My thinking was that it would be in a separate project, and a user control which referenced it would include it when built. That's nice in that it avoids a redundant NuGet package, but it's probably inconvenient if someone else wanted to come around and build a control without needing to build it from source. In hindsight it probably should be in the ScottPlot project, it's just one class, it's not quite worthy of its own turf.

> I want to put some high quality focused time into this, but I'm a bit overwhelmed with work-related stuff for the next few days, so progress may be slow for a bit. I'm excited to study this further though! Thanks for all your work on this!

No problem, take all the time you need. Let me know if you have any ideas for changes or when I should put in a PR.

**Comment by Benny121221** [comment]
I moved `ControlBackend` into the main ScottPlot project

**Comment by swharden** [comment]
Hey @Benny121221 thanks again for your work on this! 

Now that all active ScottPlot issues have been cleared out and the development of new features has started to settle down I can start work toward significantly refactoring how the user controls achieve interactivity using a back-end module similar to the one you created.

It seems like this may be ready for a PR! Is ControlBackend.cs the only modified file outside the ScottPlot.Avalonia folder? If so, and the PR doesn't modify any existing files, it seems like a low-cost extension to ScottPlot, and even if development on the Avalonia control lags behind the WinForms and WPF controls for a bit there's probably no disadvantage to including it as a separate package.

**Comment by Benny121221** [comment]
> It seems like this may be ready for a PR! Is ControlBackend.cs the only modified file outside the ScottPlot.Avalonia folder?

Yes it is, and I opened a PR #503 

> If so, and the PR doesn't modify any existing files, it seems like a low-cost extension to ScottPlot, and even if development on the Avalonia control lags behind the WinForms and WPF controls for a bit there's probably no disadvantage to including it as a separate package.

Ja, that was my thinking. The only thing I was wondering, is would it be worth it to create a demo for Avalonia?

**Comment by swharden** [comment]
> would it be worth it to create a demo for Avalonia?

Yeah, want to create a minimal-case quickstart using the ScottPlot.Avalonia project in `/src/ScottPlot.Demo.Avalonia`?

**Comment by Benny121221** [comment]
> Yeah, want to create a minimal-case quickstart using the ScottPlot.Avalonia project in /src/ScottPlot.Demo.Avalonia?

Something like the demos for WPF or WinForms? Or just something small?

**Comment by swharden** [comment]
What do you think about something super simple like the examples on https://swharden.com/scottplot/quickstart ?

**Comment by Benny121221** [comment]
c16103b58f8c6a265988923deefa34020739473e Yes chef

**Comment by swharden** [comment]
Thanks @Benny121221, This is looking great! I merged #503 and just uploaded a multi-framework NuGet package which should become available in a few minutes. It'll be interesting to see if the package works as expected!

https://www.nuget.org/packages/ScottPlot.Avalonia/

**Comment by swharden** [comment]
A couple notes related to https://github.com/swharden/ScottPlot/commit/3a0d3beb0e0b3fc3053494f0ba4df1d9593977c8#commitcomment-41456572

### managing NuGet dependencies

The Avalonia control's dependencies are managed like the other two controls. When the NuGet package is created, version information from the `ScottPlot` package from the provided path is used to define the version required by the control, then when a user goes to install a package everything is pulled from NuGet. This allows NuGet packages to have version-matched dependencies without having to specify required versions in the csproj file. It also allows you to compile the whole project in one swoop and upload the packages (as opposed to compiling scottplot, uploading it, referencing it, then compiling all the packages that depend on it and uploading those later). Does this description of events adequately address your concern?

https://github.com/swharden/ScottPlot/blob/edf517ede5ae92b369f6f9123ee879bc44b395c2/src/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj#L31-L35

https://github.com/swharden/ScottPlot/blob/edf517ede5ae92b369f6f9123ee879bc44b395c2/src/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj#L32-L37

https://github.com/swharden/ScottPlot/blob/edf517ede5ae92b369f6f9123ee879bc44b395c2/src/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj#L30-L37

### refactoring user controls

The [ControlBackend.cs](https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot.Avalonia/ControlBackend.cs) is great, and I would like to use it for all of the user controls! A good time for this refactor would be during the switch from version 4.0 to 4.1, which I anticipate will occur shortly. Some recent chatter about that is in #504. My goal over the last few weeks is to glide ScottPlot (and its controls) toward maximal stability so I don't have to be distracted with fixes/updates while I work on the new version. Because of this I'm hesitant to make large refactoring changes to version 4.0 at this time. This is why I was excited about Alvonia support, but preferred for code changes to be isolated in their own folder. Once the transition to 4.1 begins, I'll be changing names, namespaces, file paths, and move ControlBackend.cs somewhere different 👍

I'm still working out these details, and will update the roadmap (which is admittedly outdated presently) when I have my sequence of events and timeline figured out. Thanks for being flexible with this one! It's really cool to see the the Avalonia package on NuGet now. Let me know if you have additional questions or suggestions, or if you think there's something here I could do better - I appreciate your feedback!

**Comment by Benny121221** [comment]
Ok, I was under the impression that the ScottPlot project was being bundled with the Avalonia package at compile-time, I didn't know that NuGet could turn csproj references into NuGet references. And I now see that the ScottPlot package is a NuGet dependency of the Avalonia project on nuget.org

I had thought that the `ScottPlot.Interactivity` namespace was still in the `ScottPlot` project but I now see that it was moved in 911373809b4e32108ef862896707fe3a4a7ba5d0, which was a large part of why I was confused. I thought it couldn't be using the NuGet version as `ScottPlot.Interactivity` doesn't exist in ScottPlot 4.0.39.

**Comment by swharden** [comment]
> Ok, I was under the impression that the ScottPlot project was being bundled with the Avalonia package at compile-time, I didn't know that NuGet could turn csproj references into NuGet references. And I now see that the ScottPlot package is a NuGet dependency of the Avalonia project on nuget.org

Getting NuGet packages figured out took a lot of fiddling with, but it seems this is the case! Just looking at the csproj file code I wouldn't have predicted this behavior, but it seems to work so I'm sticking with it 🙃 

> I had thought that the ScottPlot.Interactivity namespace was still in the ScottPlot project but I now see that it was moved in 9113738, which was a large part of why I was confused. I thought it couldn't be using the NuGet version as ScottPlot.Interactivity doesn't exist in ScottPlot 4.0.39.

Ah, I see the concern now. Since the Avalonia control was able to be released without modifying ScottPlot, I was able to publish it without actually requiring a version increase. This turned out to be pretty cool! I think the project landed in a good spot 👍 thanks again for all your work on this!
