### ISSUE TITLE
don't display null labels in legend

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#50]
It would be great if the legend didn't show null plot labels. 

@Padanian do you want to fix this one since you're the legend expert?

```cs
var plt = new ScottPlot.Plot(width, height);
plt.PlotScatter(dataXs, dataSin);
plt.PlotScatter(dataXs, dataCos, label: "cos");
plt.PlotVLine(20);
plt.Legend();
```
![58_StyleDefault](https://user-images.githubusercontent.com/4165489/61835089-68c30380-ae48-11e9-97d9-ba92aa5cd70a.png)

**Comment by Padanian** [comment]
taking it with pleasure! 

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Wed, 24 Jul 2019 23:23:44 +0000 (UTC)
Oggetto:[swharden/ScottPlot] don't display null labels in legend (#50)

	It would be great if the legend didn't show null plot labels. 

	@Padanian [1] do you want to fix this one since you're the legend
expert? var plt = new ScottPlot.Plot(width, height);
plt.PlotScatter(dataXs, dataSin);
plt.PlotScatter(dataXs, dataCos, label: "cos");
plt.PlotVLine(20);
plt.Legend(); 

	 [2] 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [3], or mute the
thread [4]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/50?email_source=notificationsu0026email_token=AB3I2BCX6MS7MPSFKSYTD53QBDP7RA5CNFSM4IGVRYY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBLHKRA",
"url":
"https://github.com/swharden/ScottPlot/issues/50?email_source=notificationsu0026email_token=AB3I2BCX6MS7MPSFKSYTD53QBDP7RA5CNFSM4IGVRYY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBLHKRA",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/Padanian
[2]
https://user-images.githubusercontent.com/4165489/61835089-68c30380-ae48-11e9-97d9-ba92aa5cd70a.png
[3]
https://github.com/swharden/ScottPlot/issues/50?email_source=notifications&amp;email_token=AB3I2BCX6MS7MPSFKSYTD53QBDP7RA5CNFSM4IGVRYY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBLHKRA
[4]

**Comment by swharden** [comment]
Thanks @Padanian !
