### ISSUE TITLE
Create option for fixed marker size in signal plots

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#507]
**Describe the bug**
I am not sure if this is a bug, but it is not convenient for me. I would like to see fixed sizes markers not depending on the number of data points.

**To Reproduce**
Test with this code, Winform. If you set the number of data points from 50 to 500, the marker size drops, I cannot properly see the tiny dots.

```
Random rand = new Random(0);
            double[] ys = DataGen.RandomWalk(rand, 50);
            
            formsPlot1.plt.PlotSignal(ys, lineWidth: 0, markerSize: 10);

            formsPlot1.plt.AntiAlias(true, true);
            formsPlot1.Render();
```

**Comment by StendProg** [comment]
HI @bukkideme 
> I would like to see fixed sizes markers not depending on the number of data points.

You can plot with PlotScatter(xs, ys..). It always draws markers and always the same size.

PlottableSignal have 2 different mode:
- Low density close to `Scatter` behavior
- High density mode, then there is more then 1 point per pixel width.

In High density mode it makes no sense to draw all points and markers, instead, a special optimized for speed is used,
and markers are not used at all in this mode. 
To smooth the transition from non-use of markers to their sudden appearance. As the transition from high to low density mode, they gradually increase in size from 0 to the specified.
You just got into the area close to the transition to the High densigy mode in your test.
Since this moment has caused you some difficulty, it may make sense to make a setting for the `PlottableSignal` in some form, something like (bool fixedMarkerSize). But in any case, there will be no markers in high density mode, and in low density mode close to it, full-size markers often overlap ugly.

**Comment by swharden** [comment]
Hi @bukkideme, @StendProg gave an excellent answer. `PlotScatter` gives you much more control over marker size and shape than `PlotSignal`. Signal plots are designed to display high density data where there are more data points than pixels, so drawing markers for these types of plots will typically not look good.

However, I like @StendProg's suggestion of adding an option to make automatic marker resizing optional in signal plots. I'll leave this issue open to track progress on this front, and can add this feature in as I work on improvements related to #505

**Comment by bukkideme** [comment]
Hi!

Thanks for the explanation, now it makes sense :)
Actually the workaround was easy: I use a non zero line width beside the markers. In this way, when there are not many data points, or when the user zooms in to a smaller area, the markers are nicely visible. In high density cases, the lines make the plot visible, and the line width does not change.

**Comment by swharden** [comment]
After looking at this after a few days, I think I'll leave the code as it is. It makes sense for signal plot to have markers that slowly fade into view (auto-sized), or no markers (marker size = 0), but I don't think there's a good use case to require fixed marker size for low density mode. Doing so would make markers suddenly appear when zooming in interactively, and if markers are really desired a Scatter plot is the way to go here (as discussed above).

@bukkideme I'm glad you found a good solution that works for you, and @StendProg thanks again for your helpful input!
