### ISSUE TITLE
Animation options

### ISSUE THREAD

**Issue by AlexFsmn** [swharden/ScottPlot#532]
**What can we do to make ScottPlot better?**
Would be cool if some animations was added to this library.

One example:
When using the signal plots you can pretty easily connect this to a live stream of data which works great.
However, it would be awesome if you would have the possibility to add animations to this to make i look a bit smoother when updated.
Of course this would all be optional by setting a property like enableAnimations = true.

Thoughts? :)

**Comment by swharden** [comment]
Hi @AlexFsmn, 

At this time I don't think animations are consistent with the core design philosophy of ScottPlot. The primary goal for ScottPlot is to serve as a dependency-free .NET Standard application which lets anyone create plots from console applications (especially in server environments). A secondary goal is to provide containing user controls to allow some interaction with the mouse. 

Rich animation experiences and control-centric MVVM designs (#494) are probably outside the scope of what this repository seeks to achieve. That said, somebody could create a WPF control that uses data binding and animations to achieve this functionality (harnessing ScottPlot's plotting system), but that control would be so large in complexity that I probably wouldn't want to be the one to maintain it at this time. It's worth noting that development of ScottPlot5 has begun (#521), and its improved rendering system probably supports a renderer which draws with native WPF objects, making animations (with DirectX acceleration) feasible.

Related, there is a plotting library called LiveCharts which aims to produce highly animated WPF controls. Due to the way everything is animated, it is not very performant. Unfortunately I suspect it is abandonware, as its front page pitches a big release will come out in September 2018 (two years ago). https://github.com/Live-Charts/Live-Charts

Thanks for asking this question though!
