### ISSUE TITLE
[New plot] Doughnut plots

### ISSUE THREAD

**Issue by AlexFsmn** [swharden/ScottPlot#533]
**What can we do to make ScottPlot better?**
Pie plots are available, but what about doughnut plots?

Is there any plan on adding these?

**Comment by swharden** [comment]
I like this idea! It would be nice if this effect could be achieved like
```cs
double[] values = { 778, 283, 184, 76, 43 };
var pie = plt.PlotPie(values);
pie.explode = true;
pie.donut = true;
``` 

![image](https://user-images.githubusercontent.com/4165489/92335486-4b112780-f065-11ea-8e98-c65f3d861305.png)

The various labeling options are already in the pie plottable class, so this would probably be pretty easy.
https://swharden.com/scottplot/cookbooks/4.0.38/#plottypes-pie-show-everything

@Benny121221 recently created the pie chart (#423) so they might want to add this functionality, but if not @AlexFsmn I'd be happy to review a PR. Extra points if the donut can be achieved using clipping instead of drawing an opaque circle on top of the plot (to accomodate transparent plot backgrounds).

**Comment by swharden** [comment]
This is in a pretty good place now! This feature (and a new cookbook) will be be packaged with the next release on NuGet 👍
