### ISSUE TITLE
Value indicator on hover

### ISSUE THREAD

**Issue by AlexFsmn** [swharden/ScottPlot#535]
**What can we do to make ScottPlot better?**
I'm sorry if this already exists but I couldn't find it.
I have a lot of signal plots in a project of mine that has multiple lines. It would be useful if you could hover on a specific X value in the graph to get an indicator on what Y-value all lines on the current X-value has.

Also, is it possible to get on-hover values from any graph? If yes it would be helpful showing in the cookbook. If no maybe consider adding to multiple existing graphs?

**Comment by swharden** [comment]
Hey @AlexFsmn, 

It's not super obvious, but all cookbook examples are designed for console applications. Most of the work in ScottPlot does not involve GUI programming. The few GUI-specific tasks that are supported can be found in the demo program, and there are separate demo programs for WinForms and WPF. Click-to-run demos can be downloaded from https://swharden.com/scottplot/demo and source code is in this repository.

Regarding finding the ***coordinate under*** the cursor, check out the "mouse tracker" demo. The key fact is that controls have a method you can call any time to find the position (in graph units) under the mouse.

```cs
(double coordinateX, double coordinateY) = formsPlot1.GetMouseCoordinates();
```

![image](https://user-images.githubusercontent.com/4165489/93027688-ac447800-f5dc-11ea-928b-b85b9015ca71.png)

Regarding finding the ***data point nearest*** the cursor, check out the "show value under mouse" demo. There is a special type of scatter plot that supports this, but signal plots do not, so it is not recommended for data sets larger than a few hundred points.

![image](https://user-images.githubusercontent.com/4165489/93027662-67204600-f5dc-11ea-9e17-178670d25ca2.png)

Since the user controls are essentially thin wrappers for a Bitmap generator, options for mouse interactivity beyond pan/zoom are somewhat limited. Users wanting to customize mouse interactivity are encouraged to write their own user control.

Hope it helps! --Scott
