### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#536]
**What can we do to make ScottPlot better?**
Currently, the font of all text is decided like this:
1. The plottable (or axis, legend, etc) decides if they want a Serif, Sans Serif, or Monospace font name
2. The `ScottPlot.Config.Fonts` class has a list of fonts of each type and returns the name of the first installed font of that type
    2.1 If there are no installed fonts of that type it returns the name of the system default font name

I'm conflicted as to what the best alternative would be. The most obvious option is for every piece of text to receive an optional parameter to choose a different font, but that is overkill, a lot of time to implement, and not a good user experience, as they may have to change **every** font on every plottable/axis/legend/etc just to fit with their theme.

So my suggestion is to allow the user to call something like `Config.Fonts.SetSansSerifFontName(string fontName)` which adds the font to the beginning of the sans serif (or serif or monspace) list of fonts. Then it will be used (if the specified font is installed) everywhere there is sans serif text.

Worth noting that currently `Config.Fonts.GetDefaultFontName()` returns the first valid Sans Serif font, which should probably be changed. If the user wants to set comic sans as the font for their plottables it probably shouldn't affect the axis in my opinion. Your opinion may differ. Lots of plottables use this method, when they probably should use `GetSansFontName`.

Does your proposed feature allow users to do new things in source code? If so, show us how you'd like to be able to use the new feature:

```cs
Config.SetSansFontName(string "Comic Sans MS");
```

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by Benny121221** [comment]
Perhaps separate methods `GetPlottableFont` and `GetFrameFont`, where the plottables can more use a different font than the axis labels and legend?

**Comment by swharden** [comment]
Hey @Benny121221, you raised some excellent points here! Not only would it be great to be able to define a global default font, but it would also be extremely helpful to be able to define a global font size (or size multiplier?) to help compensate for display scaling. You also correctly identified how sticky this can get. Many plottables have several different fonts...

Since adding this feature is so far-reaching I'm inclined to tackle it in ScottPlot5 (#505, #521). There, everything (axis labels, plottables, ticks) implements `IRenderable`, and perhaps methods could be added to the interface to allow customization of font styling 🤔 I'll continue to think about this one!

I added this topic to the list of features I want to implement #412, but it's lower on the priority list than some others so I'll close this issue for now. Thank you for the suggestion!
