### ISSUE TITLE
ticks display very large and very small numbers poorly

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#54]
We often need to plot very large or very small numbers. ScottPlot's recent version is not able to render such plots. If we use large numbers, it starts to consume up GBs of RAM, eventually crashing the app. 
`double[] xs = new double[] { 1, 2, 3, 4, 5 };`
`double[] ys = new double[] { 1E15, 4E15, 9E15, 16E15, 25E15 };`
`scottPlotUC1.plt.PlotScatter(xs, ys);`         
`scottPlotUC1.Render();`
If we try to display very small numbers, it works, but not showing the numbers at the axis ticks. Could this be fixed somehow? I think the fix should contain adding new features to the package, we could call it like "AxisScaling". Here we could set the formatting of the axis numbers (number of digits, precision, scientific/engineering/normal/... number formats )...
What do you think?

edit: my temporary workaround is that, I divide the large array by 1E15, then name the axis as "1E15 unit".

**Comment by Padanian** [comment]
Why don't you just divide everything by 1e15 and plot the mantissa?
If you'd like to participate in the development of ScottPlot, feel
free to do so.

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Subscribed" 
Inviato:Fri, 26 Jul 2019 11:44:22 +0000 (UTC)
Oggetto:[swharden/ScottPlot] Unable to Render plot with very
large/small numbers (#54)

	We often need to plot very large or very small numbers. ScottPlot's
recent version is not able to render such plots. If we use large
numbers, it starts to consume up GBs of RAM, eventually crashing the
app.
double[] xs = new double[] { 1, 2, 3, 4, 5 };
double[] ys = new double[] { 1E15, 4E15, 9E15, 16E15, 25E15 };
scottPlotUC1.plt.PlotScatter(xs, ys);
scottPlotUC1.Render();
 If we try to display very small numbers, it works, but not showing
the numbers at the axis ticks. Could this be fixed somehow? I think
the fix should contain adding new features to the package, we could
call it like "AxisScaling". Here we could set the formatting of the
axis numbers (number of digits, precision,
scientific/engineering/normal/... number formats )...
 What do you think? 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/54?email_source=notificationsu0026email_token=AB3I2BAF3GHXQXOXPNOFMR3QBLPQ5A5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBWIQXQ",
"url":
"https://github.com/swharden/ScottPlot/issues/54?email_source=notificationsu0026email_token=AB3I2BAF3GHXQXOXPNOFMR3QBLPQ5A5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBWIQXQ",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1]
https://github.com/swharden/ScottPlot/issues/54?email_source=notifications&amp;email_token=AB3I2BAF3GHXQXOXPNOFMR3QBLPQ5A5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBWIQXQ
[2]

**Comment by bukkideme** [comment]
@Padanian Just directly after posting, I edited it with this obvious workaround. However, I think it could be a basic feature of ScottPlot to be able to handle very large/small numbers...
> my temporary workaround is that, I divide the large array by 1E15, then name the axis as "1E15 unit".

Thanks for inviting me to contribute, but my C# skills are still very beginner. If you do not want me, who is just a simple user, to report found issues, you can tell me directly ;)
Do not misunderstand me, I am very grateful for those who contribute to this package by coding, unfortunately I can now only give ideas and report findings as a simple user...

**Comment by Padanian** [comment]
Sorry if I sound unpolite, but most of the issues you reported have
workarounds or can be faced with alternative approach.
i'm a beginner too, and Scott is great in polishing the code up after
me.it helps me improving my c#.So don't be shy.

----- Messaggio Originale -----
Da: "swharden/ScottPlot" 
A:"swharden/ScottPlot" 
Cc:"Alessandro Mandelli" , "Mention" 
Inviato:Fri, 26 Jul 2019 12:02:40 +0000 (UTC)
Oggetto:Re: [swharden/ScottPlot] Unable to Render plot with very
large/small numbers (#54)

	@Padanian [1] Just directly after posting, I edited it with this
obvious workaround. However, I think it could be a basic feature of
ScottPlot to be able to handle very large/small numbers...  

	my temporary workaround is that, I divide the large array by 1E15,
then name the axis as "1E15 unit".  

	Thanks for inviting me to contribute, but my C# skills are still very
beginner. If you do not want me, who is just a simple user, to report
found issues, you can tell me directly ;)
 Do not misunderstand me, I am very grateful for those who contribute
to this package by coding, unfortunately I can now only give ideas and
report findings as a simple user... 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [2], or mute the
thread [3]. [ { "@context": "http://schema.org", "@type":
"EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
"https://github.com/swharden/ScottPlot/issues/54?email_source=notificationsu0026email_token=AB3I2BCF3XRCQNTSBKAGYFDQBLRVTA5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24MEPI#issuecomment-515424829",
"url":
"https://github.com/swharden/ScottPlot/issues/54?email_source=notificationsu0026email_token=AB3I2BCF3XRCQNTSBKAGYFDQBLRVTA5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24MEPI#issuecomment-515424829",
"name": "View Issue" }, "description": "View this Issue on GitHub",
"publisher": { "@type": "Organization", "name": "GitHub", "url":
"https://github.com" } } ]

Links:
------
[1] https://github.com/Padanian
[2]
https://github.com/swharden/ScottPlot/issues/54?email_source=notifications&amp;email_token=AB3I2BCF3XRCQNTSBKAGYFDQBLRVTA5CNFSM4IHDC4F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24MEPI#issuecomment-515424829
[3]

**Comment by bukkideme** [comment]
@Padanian I will try to find some time soon to look into the source, actually I am interested how it operates under the hood. I will see in which way I could contribute...

**Comment by bukkideme** [comment]
Actually this one is related:
#3

**Comment by Padanian** [comment]
I traced this back to the routine where the number of ticks is calculated. For your graph, the Y axis is so wide that it ends up having approx 550'000 ticks.
You can solve the issue in the meantime by setting the axis manually.
I am committing a fix right now.

**Comment by Padanian** [comment]
![immagine](https://user-images.githubusercontent.com/7769348/61955267-e4dd5880-afba-11e9-9926-b728fe669bc7.png)

**Comment by swharden** [comment]
@Padanian and @bukkideme what do you think about how matplotlib handles this issue? I kind of like it because it means the axis ticks are always simple...

## small numbers
```python
import matplotlib.pyplot as plt
import numpy as np

pointCount = 100
xs = np.arange(pointCount)
ys = np.sin(xs/pointCount*np.pi*2)

plt.grid()
plt.plot(xs, ys, '.-')
plt.show()
```

![small](https://user-images.githubusercontent.com/4165489/61955664-8055d580-af89-11e9-9c5b-c24f9df669cd.png)

## big numbers
```python
import matplotlib.pyplot as plt
import numpy as np

pointCount = 100
xs = np.arange(pointCount)
ys = np.sin(xs/pointCount*np.pi*2)

plt.grid()
plt.plot(xs * 1e20, ys * 1e20, '.-')
plt.show()
```

![large](https://user-images.githubusercontent.com/4165489/61955692-92d00f00-af89-11e9-82ac-506d18270b03.png)

**Comment by bukkideme** [comment]
I like the idea! It just gives the required info in a simple way. If you want to keep this package simple, I guess better to skip adding special number formatting features to the axis ticks, which is never an easy and short work...

**Comment by Padanian** [comment]
I traced it back to a bug in Renderer.cs line 141. It should be a `while` not a `for`

**Comment by bukkideme** [comment]
@swharden @Padanian  what do you think of the location of the multiplier "1e22" at the x-axis? I would feel it more natural at the outer edge of the "Y2-axis" bottom. In this way the "bounding box" or outer size of the diagram grows both in X and Y directions, not only Y...

**Comment by swharden** [comment]
closed by accident

**Comment by swharden** [comment]
this issue will be corrected when the tick module is refactored (issue #57)
