### ISSUE TITLE
scrollwheel is slow in winforms control

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#543]
Not sure why. It wasn't always this way. Most evident in the "Display data density" Signal plot example.

**Comment by swharden** [comment]
I think this is 2 reasons:

* The mouse wheel isn't passing `lowQuality: lowQualityWhileDragging` into the `Render` method. A timer should automatically render a high quality version a few hundred milliseconds after a mouse wheel event.

* Render is recalculating the layout on every mouse wheel which is slow. The Render loop should know not to calculate layout if low quality mode is enabled.

**Comment by StendProg** [comment]
It was present in #93. Apparently lost as a result of numerous changes.

**Comment by StendProg** [comment]
We can create a render requests queue and handle it in a special way. For example, if request count more then 1 at the end of current `Render` - run only the last one. We can also attach a timer here, or even better, a `HighQuality` render immediately launched when the queue is empty, but instantly canceled when a new request arrives.
I'll try to see what I can do the other day.

**Comment by StendProg** [comment]
Found it. Each new demo on load call `Control->Reset()`, `Reset` call `InitializeScottPlot`, `InitializeScottPlot` make new subscribe to `PbPlot_MouseWheel` without correct unsubscribe from previous handler.
Thus, as a result of wandering through the demo, it was possible to get a dozen handlers that were all called on the single mouse wheel scroll.
This fix solves most of the problems and the latency is now comparable to the HighQuality render time. (10-500 ms instead of seconds, which led to confusion). Anyway i want to take additional time to make the another improvements.

**Comment by swharden** [comment]
Fixed in #545, thanks @StendProg!
