### ISSUE TITLE
UpdateHover() does not work with Signal Plot

### ISSUE THREAD

**Issue by FadyDev** [swharden/ScottPlot#548]
Hello,

first of all, thanks a lot for your quick replies and the help you always offer.

I implemented the SignalXY Plot and I had already in my implementations the UpdateHover function, with which, the Data of each Point on the chart appears on MouseOver. However, the UpdateHover works only with the Step and the Line charts and not with SignalXY.

Is there any possibility to refactor the UpdateHover to work with SignalXY Chart? Or any out of the box solution for showing the coordinates data on a chart on hover?

Thanks in Advance for your help.

**Comment by swharden** [comment]
Hey @FadyDev, 

The quickest thing you can do now is get the coordinates under the mouse:
```cs
(double coordinateX, double coordinateY) = formsPlot1.GetMouseCoordinates();
```
Then you can find the nearest data point _on your end_ and display that result or highlight it on the plot somehow.

### Scatter Highlight

There is a special plottable which makes it easy to show the value nearest the cursor. The demo is under the "show value under mouse" button. A related thread is #535

![show-value-on-hover](https://user-images.githubusercontent.com/4165489/93349414-7209ef00-f805-11ea-9e8a-1ea9a8baba60.gif)

### Adding _Show Value Nearest Cursor_ Functionality to Signal Plots

"Show value under cursor" seems to be a popular use case, so I'd love to do a better job at supporting it. However, this is very computationally intense because on every mouse move (many times a second) you have to triangulate the distance between the cursor position and the position of every point displayed, find the closest point, and re-render the graph to highlight it. As such this feature is currently only recommended for small datasets.

It may be possible to use some mathematical optimizations to make this a little faster for Signal plots (including SignalXY), but I haven't explored this thoroughly. There are some other higher-priority goals for me at the moment (support for OpenGL, multiple Y axes, etc.) so I don't plan to explore this soon, but if you want to have a go at it you can use `PlottableScatterHighlight` as a reference. Notice it implements `IHighlightable`, so perhaps the solution could be as easy as implementing `IHighlightable` in the `PlottableSignalBase` class...

Hope it helps!
Scott
