### ISSUE TITLE
How to update a signal plot with a new data array

### ISSUE THREAD

**Issue by HowardWhile** [swharden/ScottPlot#557]
Hi 

In fact, I use below method to achieve growing data display. 
```c#
// initial
ScottPlot.PlottableSignal my_plt;
System.Random my_rand = new Random();
List<double> data_growing = new List<double>();
private void formsPlot1_Load(object sender, EventArgs e)
{
    this.data_growing = ScottPlot.DataGen.Random(my_rand, 10).ToList();
    this.my_plt = this.formsPlot1.plt.PlotSignal(data_growing.ToArray());
    this.formsPlot1.Render();
}

// growing
private void button1_Click(object sender, EventArgs e)
{
    data_growing.AddRange(ScottPlot.DataGen.Random(my_rand, 5).ToList());
    this.my_plt.ys = this.data_growing.ToArray();
    this.my_plt.maxRenderIndex = this.my_plt.ys.Length - 1;
    this.formsPlot1.plt.AxisAuto();
    this.formsPlot1.Render();
}
```
![21](https://user-images.githubusercontent.com/18715360/93748752-59497100-fc2b-11ea-85cf-77dbe85f469a.gif)

But I encountered a problem when I updated from 4.0.39 to 4.0.40. It will report the error `IndexOutOfRangeException`.

Because the data array `my_plt.ys` is not synchronized with the array `my_plt.minmaxSearchStrategy.SourceArray`

**Here's an example of what I'd like to do:**
Maybe can modify the PlottableSignalBase.updateData program like this
![image](https://user-images.githubusercontent.com/18715360/93750052-7ed77a00-fc2d-11ea-8382-389ba197c5e2.png)

```c#
public void updateData(T[] newData)
{
    //updateData(0, newData.Length, newData);
    this.ys = newData;
    this.maxRenderIndex = this.ys.Length - 1;
    this.minmaxSearchStrategy.SourceArray = newData;
}
```
Then I can update `ys` and `SourceArray` by updateData function at the same time.
```c#
private void button1_Click(object sender, EventArgs e)
{
    data_growing.AddRange(ScottPlot.DataGen.Random(my_rand, 5).ToList());
    //this.my_plt.ys = this.data_growing.ToArray();
    //this.my_plt.maxRenderIndex = this.my_plt.ys.Length - 1;
    this.my_plt.updateData(this.data_growing.ToArray()); // Replace the old method
    this.formsPlot1.plt.AxisAuto();
    this.formsPlot1.Render();
}
```

**Comment by StendProg** [comment]
Hi @HowardWhile, thanks for reporting.
Yes, you're right, now we need keep in sync `ys` and `minmaxSearchStrategy. SourseArray`. I proceeded from the assumption that the user cannot change the source array itself after creating the plot, only update its elements. The growing data demo uses this approach, it is proposed to initially set a deliberately large array, write new data to clean areas and shift the render border `maxRenderIndex`. You are taking a slightly different approach, this poses potential problems, especially in multithreading. Your solution used to work, but now it doesn't, let's decide something.

It is nothing difficult to implement the synchronization of these arrays when updating the `ys`, the only problem is in choosing the appropriate API method for this. `updateData` you pointed came from `SignalСonst` (`Signal` does not really need it) and in fact it does not change the is array itself, but overwrites element by element with new data. If implemented as you suggested, it will create confusion in `updateData` behavior of `Signal` and `SignalConst`.

If we are going to allow modification of the original array, then we need to do it in a controlled way through the property:
```c#
private double[] _ys;
public double[] ys 
{
  get => _ys;
  set 
  {
   // new value check for null and another can be added
    _ys = value;
   minmaxSearchStrategy.SourceArray = value;
  }
}
```
This code should work, but due to its good properties it should be named with a capital letter  `Ys`, and this will already be the API breaking change.

Another option would be to extend `Signal` interface by adding 1 more method, something like `ChangeSource(double[] newSource)` with code you provided for `updateData`.

If we make a more radical decision and prohibit the user from changing the original `ys` array, then we can simply mark it readonly.

@HowardWhile sorry for the inconvenience, with nuget you can easily roll back to the previous version until the problem will be solved.
I'm ready to do one of the above, just wait until Scott (@swharden ) makes a decision as best.

**Comment by swharden** [comment]
Hi @HowardWhile, thanks for posting this issue! Thanks @StendProg for your input too. 

### Fixing the bug that happens if you replace `ys`

I recognize that replacing `ys` with another array breaks the `minmaxSearchStrategy`, but this topic is a bit advanced so I want to take some more time to consider it deeply before deciding how to proceed. The rest of this response will help you solve the problem now with the library you have.

### Solution 1: clear and replot

Since you are creating a new array every time you add one data point, you could just `plt.Clear()` and `plt.PlotSignal(newData)` when the array changes.

### Solution 2: plot a sub-portion of a large array

A better solution, like @StendProg suggested, is to create a large array one time, then fill its values as you get new data points and update `maxRenderIndex` accordingly. This is the method used by the "growing data" [ScottPlot Demo](https://swharden.com/scottplot/demo) application. 

![growing](https://user-images.githubusercontent.com/4165489/93786069-db6e7100-fbfc-11ea-96a0-55ea24445f1e.gif)

Those tips should help you get un-stuck for now, and I'll provide a more detailed response when I have some more time explore this topic further 👍

**Comment by swharden** [comment]
@StendProg 

> I proceeded from the assumption that the user cannot change the source array itself after creating the plot, only update its elements

What do you think if I make `Ys` in signal plots `readonly`? This would make it harder to use Signal plots incorrectly, and users would know to use the `maxRenderIndex` technique or clear/replot every time their array changes. This might be a good idea for all plots which accept arrays...

Implementing this would be a good time to go from 4.0 to 4.1

> it should be named with a capital letter Ys, and this will already be the API breaking change.

I have been wanting to do this for a long time too. I think I can start using capitol public properties, and leave the old lowercase ones there (using get/set to point to the new ones) and mark them as obsolete. This way it will not be a breaking change.

**Comment by HowardWhile** [comment]
Hi @swharden @StendProg 

Thanks for your suggestions. I will follow **Solution 2** and make some adjustments to my program to adapt to the new version.

I look forward to the next version and glad to see the outcome.

**Comment by swharden** [comment]
@HowardWhile I'm glad we arrived at a solution that works for you!

Good discussion remains about how to improve plottable properties (capitalizing them, making them read-only, etc.), but that's outside the scope of this issue so I'll go ahead and close it
