### ISSUE TITLE
Candlestick plot Y Axis resolution issue

### ISSUE THREAD

**Issue by ozgur640** [swharden/ScottPlot#568]
Hi, I cannot make the Y axis show very small numbers on the candle stick chat. It plots the candles without an issue but the y axis does not show the values such as 0.0000001d. Is it a bug or is there a setting which I could not find?

            var plt = new ScottPlot.Plot(600, 400);
            OHLC[] ohlcs = new OHLC[3];
            ohlcs[0] = new OHLC(0.00000001d, 0.00000003d, 0.00000001d, 0.00000002d,1.0d,1);
            ohlcs[1] = new OHLC(0.00000001d, 0.00000003d, 0.00000001d, 0.00000002d, 2.0d, 1);
            ohlcs[2] = new OHLC(0.00000001d, 0.00000003d, 0.00000001d, 0.00000002d, 3.0d, 1);
            plt.Title("Ten Minute Candlestick Chart");
            plt.YLabel("Stock Price (USD)");
            plt.PlotCandlestick(ohlcs);
            plt.Ticks(dateTimeX: false,numericFormatStringY:"F12");

![PlotTypes_Finance_Candle](https://user-images.githubusercontent.com/44930071/94404611-f77f8e80-0177-11eb-9d64-4a76c35c9651.png)
 
Thanks.

**Comment by StendProg** [comment]
Hi @ozgur640, 
It looks like the problem is in this line:
https://github.com/swharden/ScottPlot/blob/15b8b0e822e7ab6bb593789e0cff3a928538ac5a/src/ScottPlot/Config/TickCollection.cs#L219-L221
Axis values always rounded to 5 significant digit.

You can try use `MultiplierNotation` it works for me, but it may not be what you want.
```c#
  plt.Ticks(useMultiplierNotation: true);;
```

**Comment by ozgur640** [comment]
Thanks for the explanation @StendProg, multiplier notation seems to work for now. Best Regards

**Comment by swharden** [comment]
@ozgur640 thank you for raising this issue! This problem seems to affect all plots, not just candlesticks, so I'm happy to be addressing it. I'm glad you were able to find a solution, and thanks @StendProg for your helpful answer. However, I'd like to improve ScottPlot by fixing this issue completely...

## Root Problem

That rounding exists because a "close to zero, but not zero" tick often appears due to a floating point rounding error when calculating tick positions. This is easiest to demonstrate by commenting-out this line and zooming around the origin (0, 0) in the user control. I agree that simply rounding the number like this is not the best solution, but I haven't figured out yet what the best way is to solve this issue...

![image](https://user-images.githubusercontent.com/4165489/94483679-3974f880-01a9-11eb-9bf3-c2d8f7779fa9.png)

## Partial Fix

It seems the erroneous tick is usually `E-17` or smaller, so a partial fix can be achieved by changing `maximumDecimalPlaces` from `5` to `15`. That produces output like this:

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.Title("Moderately Small (e-8)");
double[] xs = { 1e-8, 2e-8, 3e-8, 4e-8 };
double[] ys = { 1e-8, 4e-8, 3e-8, 6e-8 };
plt.PlotScatter(xs, ys);
TestTools.SaveFig(plt);
```

![image](https://user-images.githubusercontent.com/4165489/94485536-1730aa00-01ac-11eb-81e4-aca819828f6c.png)

## Remaining problem

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.Title("Extremely Small (e-20)");
double[] xs = { 1e-20, 2e-20, 3e-20, 4e-20 };
double[] ys = { 1e-20, 4e-20, 3e-20, 6e-20 };
plt.PlotScatter(xs, ys);
```

![image](https://user-images.githubusercontent.com/4165489/94485540-1a2b9a80-01ac-11eb-92cd-3f0b363155ec.png)

Numbers smaller than E-15 still can't be properly labeled if they are rounded this way. The true fix here is to identify which tick is the "zero tick" and force its value to be 0. Interestingly this does not seem easy...

Perhaps `maximumDecimalPlaces` could be dynamically set to two decimal places more than the number needed to represent the distance between each tick? Alternative strategies which are a bit smarter and can actually identify the zero tick could be implemented in the new tick modules. @StendProg I'd be interested in your input here because you have a lot of recent experience with the tick system

**Comment by ozgur640** [comment]
@swharden again thanks for the support, I have downloaded the source code and changed maximumDecimalPlaces =15 and It also works. Best regards.
Özgür

**Comment by swharden** [comment]
@StendProg following-up, I think I found a permanent solution... By using multiplication instead of addition, floating point errors do not accumulate. LINQ looks prettier here too.

### Old Method

https://github.com/swharden/ScottPlot/blob/01809457304170b31f40c71a2c275183fb0ef8a6/src/ScottPlot/Config/TickCollection.cs#L152-L162

### New Method

https://github.com/swharden/ScottPlot/blob/10eef4c4e0035720544de4d5d9b014d3575eb946/src/ScottPlot/Config/TickCollection.cs#L152-L159

**Comment by StendProg** [comment]
> By using multiplication instead of addition, floating point errors do not accumulate

Yes, the values of numeric labels can always be calculated without brute-force through addition, in contrast to the `DateTime`.
You loose `count > 999` check, but I think it will never play.
