### ISSUE TITLE
Broken labelX

### ISSUE THREAD

**Issue by Bajkman** [swharden/ScottPlot#579]
HI,
After moving graph , the graph redraws but the dateTimeX labels are drawn over the labelX.
I attached the recording of the issue.

Best regards,
Greg
[Form1 2020-10-02 09-58-06.zip](https://github.com/swharden/ScottPlot/files/5325427/Form1.2020-10-02.09-58-06.zip)

**Comment by swharden** [comment]
Hi @Bajkman,

After you manually adjust the layout (padding, etc) and the plot looks good, but after interacting with the plot using the mouse your changes to the layout are reset. This occurs because the layout is automatically recalculated every time the plot axis limits are changed to accomodate tick labels which often change length as users zoom in and out.

Customized Layout | After Mouse Interaction
---|---
![image](https://user-images.githubusercontent.com/4165489/95085645-826b0680-06ed-11eb-9bc4-7d7a2bab63a9.png)|![image](https://user-images.githubusercontent.com/4165489/95085658-85fe8d80-06ed-11eb-96e5-d365e45fc32f.png)



Since you customized your layout you don't want it reset on every mouse interaction, so you can disable this behavior with:

```cs
formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
```

Let me know if this doesn't do the trick!
Scott

**Comment by Bajkman** [comment]
hi @swharden,
> 
> Let me know if this doesn't do the trick!
> 

it works. Thanks!

Best regards,
Grega
