### ISSUE TITLE
PlotFill Function to change fill color, if one curve cuts the other one

### ISSUE THREAD

**Issue by ozgur640** [swharden/ScottPlot#583]
Hi,
I tried to find a way to draw make a fill using PlotFill() like below:
![image](https://user-images.githubusercontent.com/44930071/95338528-b3009b00-08bb-11eb-860c-4c1013fb40b5.png)
I checked the plotfill function but It uses polygon method to create the the fill and as far as I understood there is one polygon created. What I tried to do then is to find the curve crossings and create new PlotFill for every segment. In this approach the crossing point which are usually in between a data points becomes a problem. For that I plan to add an interpolation and uneven time array and crossing points in the plot but it seems the will become messy. Is there an easy way to do it with the library? Thanks in advance...

**Comment by swharden** [comment]
Hi @ozgur640, this is an interesting idea. 

It seems possible to create a variant of the polygon plot type that could render shapes like this. I'd probably call such a plottable a `ShadedDifference` plot type. This plot type would accept data (`xs`, `ys1`, `ys2`), line styles (`lineColor1`, `lineColor2`), and fill styles (`fillColor1`, `fillColor2`). There would be logic inside this plot type that would create the necessary polygons, and the render method could draw everything properly. 

Creating a plot type to do this seems possible, but currently there is not an easy way to do this with the existing plot types. We'd welcome a contribution from the user community though, since it seems possible. I added this idea to the list on #412 so it may be revisited one day...
