### ISSUE TITLE
Add option to set preserveY to false in Configure() Method

### ISSUE THREAD

**Issue by biehlermi** [swharden/ScottPlot#587]
In my configuration I enabled the option for EqualAxes, but I want `preserveY` to be false.
Is it possible to add this parameter to the configuration method?

**Comment by StendProg** [comment]
Hi @biehlermi ,
Please note that there is an alternative way of specifying the equal axes at the `Plot` rather than `Control` level.

You can find example in `Cookbok->Customize->Axis->PolarAxis` demo. Or check in your project, setup it with 1 line
```c#
plt.EqualAxis = true;
```
Since they are arranged differently, they have different behaviors, and it may immediately suit your goals.
For example, calling `AxisAuto()` or pressing the middle mouse button causes the entire `Plottable` to remain visible, and the discrepancies in the scales are filled with empty space. (Auto select preserve flag in terms of this issue).

**Comment by biehlermi** [comment]
Thank you - it solved my problem!
