### ISSUE TITLE
horizontal tick label alignment fails when rotated >90º

### ISSUE THREAD

**Issue by el-aasi** [swharden/ScottPlot#590]
So, I was trying to achieve a static top X-axis for my graph, and after looking through a few things, the best workaround was to create a second graph with the desired axis and then overlap with the main graph. For the overlapping to work properly so that I have a top-axis that goes from  0 to the right, I need to first invert the values (with the negative offset), get rid of the bg, and grid and frame, etc. rotate the xTicks 90 degrees, and rotate the image 180 degrees. So I end up with an image like this: 
![image](https://user-images.githubusercontent.com/27493937/95549226-29f67a80-0a07-11eb-8277-c977edc95348.png)
and a graph like this:
![image](https://user-images.githubusercontent.com/27493937/95549261-37ac0000-0a07-11eb-900c-7754517f804a.png)
but as you can see the ticks in a 90-degree position occupy quite some space, not leaving space for the title. And yes increasing the title hight could solve the issue, but it would require adding a lot of padding, that would be wasted because the title is centered. As you can see in here: 
![image](https://user-images.githubusercontent.com/27493937/95549471-a5582c00-0a07-11eb-897c-1547c48425d4.png)
The obvious solution would be to rotate the ticks all the way to 180 degrees to have them in a horizontal position, but unfortunately, this is where the bug occurs, as in the image: 
![image](https://user-images.githubusercontent.com/27493937/95549624-e4867d00-0a07-11eb-9b57-bf1108d56e4b.png)

Now in addition to this bug, an easier way to achieve the same result would be to put the desired values on the Y axes, rotate the image 90 degrees clockwise, and rotate the ticks 90 degrees counterclockwise. Which will not require inverting the X-axis. But unfortunately, there isn't a yTickRotation (similar to xTickRotation) :(

**Comment by swharden** [comment]
Hi @el-aasi,

First, I'm very impressed with what you've been able to achieve with image rotation! Although it's not meeting all your needs, I am surprised it works as well as it does.

ScottPlot 5 is in `/dev/ScottPlot5` and it supports many axis improvements, including multiple axes and optional ticks on the top. I am working very hard to add this functionality to ScottPlot4 (in a way that does not break the current API). This will probably fully solve your problem.

![](https://user-images.githubusercontent.com/4165489/91741604-f52f1200-eb82-11ea-9361-17641d9f2b96.gif)

There are a few steps that must be achieved first, but I hope to achieve this functionality soon. (https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) Until then there may be not much I can suggest to improve your current situation, and I wouldn't consider this a bug because rotating and overlaying plots is pretty far outside the intended use of this library. The best solution is simply for multiple axis support to be fully implemented...

> not leaving space for the title

It looks like you are creating a WinForms application. What if you make your title a `Label` and place it above the plot?

**Comment by swharden** [comment]
I figured a way to better demonstrate this issue as a bug: ***horizontal tick label alignment fails when rotated >90º.***

I can probably fix this by the weekend, which will also solve your current problem

```cs
var plt = new ScottPlot.Plot(400, 300);
double[] xs = { 1, 2, 3 };
double[] ys = { 1, 4, 9 };
string[] labels = { "alpha", "beta", "gamma" };

plt.PlotBar(xs, ys);
plt.XTicks(xs, labels);
plt.Ticks(xTickRotation: 150);

plt.XLabel("Horizontal Label");
plt.YLabel("Vertical Label");
plt.SaveFig("test.png");
```

![image](https://user-images.githubusercontent.com/4165489/95590560-333a1400-0a14-11eb-91d8-2c5cea190186.png)

**Comment by swharden** [comment]
I haven't tried this yet, but if I had to guess you _might_ be able to fix this by adding logic here to use `settings.misc.sfSouthEast` if rotation > 90

https://github.com/swharden/ScottPlot/blob/bf49026c1c0d12697159d7f6934a34c57620ab6e/src/ScottPlot/Renderer.cs#L256

**Comment by el-aasi** [comment]
Works like a charm: 
![image](https://user-images.githubusercontent.com/27493937/95724503-be1a4900-0c76-11eb-8ac9-b5dc1b95a909.png)
tho I used SouthEast, anyhow, thanks a lot, can't wait for the v5 :)

**Comment by el-aasi** [comment]
@swharden hey Scott will the rotation issue be fixed in the next releases? Should this issue be closed?

**Comment by swharden** [comment]
Hi @el-aasi, I've solely been on #578 and have noticed new issues collecting as I've been working on it. I'm almost done with it though, and once that's closed I plan to clear out the rest of the open issues including this one then push an update to NuGet. We can leave this issue open, and I should get to it pretty soon 👍

**Comment by swharden** [comment]
If you want to give it a go before I can take a closer look, this block does the rendering for ticks (when rotation is not used):

https://github.com/swharden/ScottPlot/blob/02fb5530798543cdc54d7dfa671c52b2f78ab054/src/ScottPlot/Renderer.cs#L247-L250

You might be able to tweak your string rendering by drawing the string at a slightly different position, or changing the string format alignment (currently hard-coded as `sfNorth`, but you may want `sfSouth`)

**Comment by swharden** [comment]
ScottPlot 4.1 now supports ticks on the top (optionally displaying data with a whole different X axes) so this issue is no longer an issue! I added a cookbook example for the rotated ticks to remind me to get this right before releasing the first version of 4.1

With 4.1 we now get deep support for multiple X and/or multiple Y axes, so you will no longer have to do the weird rendering trick. I'm working on the docs for how to add multiple axes (including how to have the bottom X axis and top X axis display the same coordinate space, which should work for your application). Mouse interactions aren't working as well as I want yet and I'm still deciding on the best API for axis manipulation, but this is strongly on the way to being fully supported so I'll close this issue 👍
