### ISSUE TITLE
WpfPlot layout automatically resets

### ISSUE THREAD

**Issue by Ddoupal** [swharden/ScottPlot#591]
I try to change xScaleHeight of layout, because when i use own ticks labels and rotate them, then they are cut off. But the scale doesn't move.

![Graph](https://user-images.githubusercontent.com/72607479/95577891-414b5d00-0a33-11eb-9ca7-b7133743827d.png)

```xaml
<WpfPlot Name="WpfPlot"/>
```
```cs
WpfPlot.plt.PlotBar(g.XValues.ToArray(), g.YValues.ToArray(), showValues: true);
WpfPlot.plt.XTicks(g.XValues.ToArray(), g.Labels);
WpfPlot.plt.Ticks(xTickRotation: 45);
WpfPlot.plt.Legend();
WpfPlot.plt.XLabel(g.TitleX);
WpfPlot.plt.YLabel(g.TitleY);
WpfPlot.plt.Layout(xScaleHeight: 100);
WpfPlot.Render();
```

**Comment by swharden** [comment]
Hi @Ddoupal, your code works properly in a console application. I think the custom layout is getting reset upon mouse interactions and resize events. I think you can disable this behavior with

```cs
wpfPlot1.Configure(recalculateLayoutOnMouseUp = false);
```

Let me know if this solves your issue!

### Improved Cookbook Recipe

However, I also notice there is not a good demonstration of this in the cookbook. I'll add something like this example to make this issue more easily discoverable because it comes up from time to time.

```cs
var plt = new ScottPlot.Plot(400, 300);
double[] xs = { 1, 2, 3 };
double[] ys = { 1, 4, 9 };
string[] labels = { "alpha", "beta", "gamma" };

plt.PlotBar(xs, ys);
plt.XTicks(xs, labels);
plt.Ticks(xTickRotation: 45);

plt.XLabel("Horizontal Label");
plt.YLabel("Vertical Label");
plt.Layout(xScaleHeight: 100); // <-- additional padding for rotated ticks
plt.SaveFig("test.png");
```

**Comment by Ddoupal** [comment]
Thanks for reply.
My initial problem was a little different. Problem was that i render graph on backrgound and that show window swith the graph. But when i show window and than render the graph it works as it should. So this was solved.
But now my problem is that i have UniformGrid and inside show graphs.  And when i do this the problem is the same as before.
```xaml
<ScrollViewer x:Name="ScrollViewer" Grid.Row="1">
       <UniformGrid x:Name="UniformGrid"/>
</ScrollViewer>
```
```c#
var WpfPlot = new WpfPlot();

WpfPlot.plt.PlotBar(g.XValues.ToArray(), g.YValues.ToArray(), showValues: true);
WpfPlot.plt.XTicks(g.XValues.ToArray(), g.Labels);
WpfPlot.plt.Ticks(xTickRotation: 30);
WpfPlot.plt.Legend();
WpfPlot.plt.XLabel(g.TitleX);
WpfPlot.plt.YLabel(g.TitleY);
WpfPlot.plt.Layout(xScaleHeight: 100);
WpfPlot.Render();
WpfPlot.Configure(recalculateLayoutOnMouseUp: false);

UniformGrid.Children.Add(WpfPlot);
```
But outside uniform grid like this:
```xaml
<WpfPlot Name="WpfPlot" Grid.Row="1"/>
```
It works good.
I want to show more graphs in one window, so UniformGrid looks like the best option.

**Comment by Ddoupal** [comment]
Same problem with graphs is in stackpanel, dockpanel, etc... 
The layout settings is working right only outside of these.

**Comment by swharden** [comment]
Hi @Ddoupal, I'm sorry it took me so long to get to this! 

In 2cdeb10 I improved automatic size detection for rotated ticks, so that part should be working as expected.

Regarding using ScottPlot deep inside WPF components, it seems to work well for me. I tested it with `UniformGrid` instead of `StackPanel` and it seems to work well too.

```xaml
<ScrollViewer>
    <StackPanel>
        <ScottPlot:WpfPlot x:Name="WpfPlot1" Height="300"/>
        <ScottPlot:WpfPlot x:Name="WpfPlot2" Height="300"/>
        <ScottPlot:WpfPlot x:Name="WpfPlot3" Height="300"/>
    </StackPanel>
</ScrollViewer>
```

```cs
Random rand = new Random();

public MainWindow()
{
    InitializeComponent();
    PlotRandomBars(WpfPlot1.plt);
    PlotRandomBars(WpfPlot2.plt);
    PlotRandomBars(WpfPlot3.plt);
}

private void PlotRandomBars(ScottPlot.Plot plt, int count = 10)
{
    double[] values = ScottPlot.DataGen.Random(rand, count);
    string[] labels = Enumerable.Range(1, count).Select(x => $"bar number {x}").ToArray();
    plt.AddBar(values);
    plt.XTicks(labels);
    plt.XAxis.TickLabelStyle(rotation: 45);
    plt.SetAxisLimits(yMin: 0);
}
```

![stack](https://user-images.githubusercontent.com/4165489/102698423-15a2db00-420b-11eb-8172-0ca9029dab2c.gif)

There is an issue where the mouse scroll wheel both scrolls the scroll viewer and zooms the plot, but scroll wheel zoom can be disabled `using wpfPlot1.Configure()`
