### ISSUE TITLE
Scatter Plot Multi-color line

### ISSUE THREAD

**Issue by dmarchant** [swharden/ScottPlot#595]
Is it possible to do a scatter plot with a multi-colored line? A screenshot of a similar TradingView graph with multi-colored lines is below. If I understand the code correctly, it looks like the color isn't defined as an array so you would have to modify the code at the line below to accept a different color for each connecting line?

https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot/plottables/PlottableScatter.cs#L199

![image](https://user-images.githubusercontent.com/1421030/96074987-465f4080-0e67-11eb-9d0d-d504b3f4413e.png)

**Comment by riquich** [comment]
Hi Scott, I am facing the same issue aswell. I have to plot 20~25 signalconst each having up to millions of points. If the color is fixed for each plot it is not a problem, but I have to mark specific regions of each plot to different colors just like dmarchant sketched above. The problem is, to do that I could only come up with a solution which requires dissecting each signalconst into smaller signalconsts tied end to end, which increases the plot count from 20~25 to much much more plots, like 500~1000, depending on number of segments, which significantly drops FPS, even though number of points drawn are the same. Is there a workaround to colorize individual points in a scatterplot?
Thanks in advance !

**Comment by swharden** [comment]
Hi @dmarchant and @riquich, thanks for raising this issue. This is certainly an interesting use case, and one I hadn't considered before.

After thinking about it, **I think this may be possible for scatter plots but, is probably not possible for signal plots.** Fundamentally, System.Drawing is optimized to draw a large number of lines all as one color. Signal and SignalConst leverage this fact to render data quickly by drawing a single line. Different colors means different lines, impairing performance, so it really only makes sense to try to implement this with scatter plots since those are already not performant (although this feature would reduce their performance even more).

**What determines the color of a line segment?** A user-defined array of colors equal in length to the number of data points?

**Comment by swharden** [comment]
> I have to plot 20-25 signalconst each having up to millions of points

> a solution which requires dissecting each signalconst into smaller signalconsts tied end to end

@riquich addressing your use case more specifically, it sounds like you're doing the best thing you can given the current abilities of ScottPlot and the limitations of System.Drawing. The "trick" of signal plots is that they are drawn as a single line, and the more lines you draw the more System.Drawing gets slow. Requiring multiple colors requires drawing multiple lines which is probably what accounts for the performance drop here. Unfortunately I don't have a better suggestion for you! It sounds like you're already doing the best thing you can...

**Comment by riquich** [comment]
@swharden Oh I understand. Thank you so much for your quick reply. As for how to determine color of a line segment, I guess what you suggest sounds good. Thanks again !

**Comment by swharden** [comment]
> > What determines the color of a line segment? A user-defined array of colors equal in length to the number of data points?

> I guess what you suggest sounds good

I'm not sure if this will turn out to be viable, but I'll explore the idea and see what I come up with. This would probably be a new plot type, a `ScatterMultiColor`, requiring the user to define 3 arrays: `xs`, `ys`, and `colors`. I'm pretty busy with #578 presently, but when I have time to explore this idea I'll update this issue with what I find 👍

**Comment by dmarchant** [comment]
@swharden Thanks so much for the reply and creating this awesome library! In my use-case, I am calculating an indicator on a financial time series. I want to turn the line green in an uptrend, red in a downtrend, and yellow in a sideways trend. In TradingView Pine Script the plotting code looks like this:
```javascript
plot(HMA, color= indicator[1] == -1 ? HMA > HMA[1] ? color.orange : color.red : HMA < HMA[1] ? color.green : color.lime, style=plot.style_line, linewidth=2, transp=0 )
```
The `ScatterMultiColor` with 3 arrays should work great!

**Comment by StendProg** [comment]
Hi everyone, 
As @swharden has already pointed out, the key difference between `ScottPlot` and many others libraries (imho) is the shift in focus towards interactivity (performance). For this purpose, many sacrifices have to be made.

If you develop this problem with adjusting each point separately, then color adjustments are clearly not enough. Tomorrow someone wants to have different markers for each point, and the day after tomorrow to indicate different line widths, etc.
The standard approach is to create a separate `DataPoint` structure that contains, in addition to data, all the style settings for each point. And pass an array of such structures to `PlotScatterCustomizable`. 
But only when you implement all this, it becomes clear that large plots with thousands of points are Rendered for more than a second.
It is quite a lot of work to implement all this, and it has already been done in other libraries at its best...

**Comment by swharden** [comment]
Hi @StendProg, you share an excellent perspective!

> It is quite a lot of work to implement all this

> Tomorrow someone will want to support different markers for each point

This is very true 🤣 

I think the best long term solution is to make it as easy as possible for users to _create their own plot types_ to meet their obscure use cases. Right now this is technically possible, but it is not very easy (it requires inspecting source code, inheriting `Plottable`, and overriding methods). In #578 I'm trying to strangle this design so all plot types will just inherit `IPlottable`. After this I will write documentation for how to create a custom plot type, and I hope this task will become much easier for users.

This way tomorrow when someone asks how to make a scatter plot with emojis at each point, it will be easier to encourage them to make their own plot type for their application rather than require a new plot type be added to ScottPlot.

**Comment by StendProg** [comment]
> I think the best long term solution is to make it as easy as possible for users to create their own plot types to meet their obscure use cases. Right now this is technically possible, but it is not very easy (it requires inspecting source code, inheriting Plottable, and overriding methods). In #578 I'm trying to strangle this design so all plot types will just inherit IPlottable. After this I will write documentation for how to create a custom plot type, and I hope this task will become much easier for users.
This way tomorrow when someone asks how to make a scatter plot with emojis at each point, it will be easier to encourage them to make their own plot type for their application rather than require a new plot type be added to ScottPlot.

Yes, it is always difficult to refuse, but in conditions of limited resources, this is a forced decision.
I think that no one wants to implement an interface from scratch. Most people will want to inherit from the existing `Plottable` and change only a couple of lines in the existing behavior. Designing `Plottables` taking into account such possibilities is also not an easy task... Here, too, there will not be an ideal solution, unfortunately. 
Nevertheless, your proposal is the best option.

**Comment by swharden** [comment]
Following-up, this is not currently supported since scatter plots and signal plots only display a single, continuous line. The best solution (similar to #618) is to create multiple scatter plots individually colored as desired. 

A custom plot type could be created for this purpose, and the best way to explore that option is to look at the existing scatter plot object and copy or extend it to add this functionality. 

Hope it helps! 👍 
Scott
