### ISSUE TITLE
Exception thrown if data changed while plotting in another thread

### ISSUE THREAD

**Issue by ZTaiIT1025** [swharden/ScottPlot#609]
Describe the bug and how we can reproduce it.

```cs
// a code sample may improve communication
```System.InvalidOperationException: 对象当前正在其他地方使用。
   在 System.Drawing.Image.get_FrameDimensionsList()
   在 System.Drawing.ImageAnimator.CanAnimate(Image image)
   在 System.Drawing.ImageAnimator.ImageInfo..ctor(Image image)
   在 System.Drawing.ImageAnimator.Animate(Image image, EventHandler onFrameChangedHandler)
   在 System.Windows.Forms.PictureBox.Animate(Boolean animate)
   在 System.Windows.Forms.PictureBox.Animate()
   在 System.Windows.Forms.PictureBox.InstallNewImage(Image value, ImageInstallationType installationType)
   在 System.Windows.Forms.PictureBox.set_Image(Image value)
   在 ScottPlot.FormsPlot.Render(Boolean skipIfCurrentlyRendering, Boolean lowQuality, Boolean recalculateLayout) 
位置 E:\\AcquisitionFrame\ScottPlot-master\src\ScottPlot.WinForms\FormsPlot.cs:行号 108
   在 AcquisitionFrame.View.Panels.OP1130_P10.tPlot(AutoResetEvent& Stop)

**Comment by swharden** [comment]
Hi @ZTaiIT1025, thank you for reporting this!

I think `对象当前正在其他地方使用` means `Object is currently being used elsewhere`. Can you share the WinForms code that reproduces this error?

My guess is that you are _replacing_ the `xs` or `ys` field of a `ScatterPlot`. This is not recommended because it is not thread safe (you could be plotting a variable in one thread, then replace it in another). If you are doing this, a better solution is to replace the _elements_ inside an array instead of replacing the array itself.

**Comment by ZTaiIT1025** [comment]
My array is growing and updated in real time on another thread

**Comment by StendProg** [comment]
Hi @ZTaiIT1025,
Code you provided running on UI Thread?
This line:
```c#
  formsPlot1.Render(skipIfCurrentlyRendering: true);
```
must be invoked on UI tread, and exception  looks like you try to update UI from another thread.

Try to replace this line with:
```c#
formsPlot1.Invoke((MethodInvoker)delegate {
    // Running on the UI thread
    formsPlot1.Render(skipIfCurrentlyRendering: true);
});
```

**Comment by ZTaiIT1025** [comment]
I'll try，But Does this block the UI thread？

**Comment by swharden** [comment]
### Defining the Issue

I don't have a great solution yet, but this is what I learned while investigating this:

* The `Render()` method makes many calls to the list of plottables. An `InvalidOperationException` is thrown when the list of plottabes is modified in the middle of a render.

* This means plottables can not be added or removed while rendering may be occurring in another thread. It is not easy to control when rendering happens because mouse interactions and window resizing can trigger rendering at unpredictable times. 

* One way to fix this is to only add or remove plottables in your UI thread. Since both operations block the UI thread, they won't occur simultaneously. Note that this does not have to be slow because you can do your _logic_ in another thread, but at the end when it's time to call `PlotScatter()` you could do that in your UI thread.

### Recreating the Issue

I recreated this issue (or a similar one) with a unit test that fails on my system ~90% of the time.

```cs
[Test]
public void Test_Concurrent_ModifyPlottablesWhileRendering()
{
	var plt = new ScottPlot.Plot();
	var bmp = new System.Drawing.Bitmap(300, 200);

	// update plottables continuously in the background
	Thread updateThread = new Thread(new ParameterizedThreadStart(ContinuouslyModifyPlottables));
	updateThread.Start(plt);

	// render repeatedly while the plottalbles are being modified
	var sw = Stopwatch.StartNew();
	while (sw.ElapsedMilliseconds < 5000)
	{
		plt.Render(bmp);
	}

	ContinueModifyingPlottables = false;
	updateThread.Join();

	Console.WriteLine("Test complete");
	Assert.Pass();
}
```

```cs
public static bool ContinueModifyingPlottables = true;
public static void ContinuouslyModifyPlottables(object data)
{
	ScottPlot.Plot plt = (ScottPlot.Plot)data;
	while (ContinueModifyingPlottables)
	{
		plt.Clear();
		plt.PlotSignal(new double[] { 1, 2, 3 });
	}
	Debug.WriteLine("Modification thread shutting down...");
	Thread.Sleep(100);
}
```

```
  Message: 
    System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
  Stack Trace: 
    Enumerator.MoveNextRare()
    WhereSelectListIterator`2.MoveNext()
    WhereSelectEnumerableIterator`2.ToArray()
    Settings.AxisAutoX(Int32 xAxisIndex, Double margin, Boolean expandOnly) line 203
    Settings.AxisAutoUnsetAxes() line 171
    Plot.Render(Bitmap bmp, Boolean lowQuality) line 35
    ConcurrencyTests.Test_Concurrent_ModifyPlottablesWhileRendering() line 38
```

### Solution?

I don't have a great solution yet, but these are some ideas:

Perhaps copying the list of plottables before a render would help. Technically this is not perfect because other things (like axes) could be modified mid-render. The the whole settings module could be deeply copied on every render, but that seems burdensome and slow.

Perhaps some type of lock mechanism could be used to prevent plottables or axes from being added until a render finishes. 

```cs
while (formsPlot1.plt.IsRendering) { /* wait */ }
formsPlot1.plt.Clear();
formsPlot1.plt.PlotScatter(newXs, newYs);
```

**Comment by swharden** [comment]
I added a `Plot.IsRendering` field (5a8ba5c), and I found that waiting for it to go `false` before (quickly) modifying the plot seems to fix this issue!

Note that my change just now is in the master branch which is currently a pre-release version of ScottPlot 4.1. If you want to make a similar change to the 4.0 source code you can obtain that from https://github.com/swharden/ScottPlot/releases

An alternative (and perhaps more thorough) option is to modify the user control code and wrap the contents of `Render()` with a try/catch block. This way you can ensure the user control never throws a render error.

**Comment by swharden** [comment]
@ZTaiIT1025 and @StendProg I created a system which I think solves this issue... but I'm interested in your input. I'll release this on NuGet tonight in version 4.0.45

If you want to modify the plot from another thread you can call `RenderLock()` and this will wait for the current render to finish, then prevent future renders from occurring. This lets you make your plot modifications in another thread (e.g., replacing a data array). After your modifications are done, call `RenderUnlock()` to allow renders to proceed. If a render was requested while the lock was enabled, it will resume immediately after the lock is released.

I think `RenderLock()` is a dangerous function because it could freeze your application if called from the wrong thread... However, I think its name looks dangerous, and together with and a descriptive XML doc this is enough to ensure it does not get used by accident.

I created a little WinForms app to test it and I think it's working properly:

https://github.com/swharden/ScottPlot/blob/e4d5c87751bba3352fce62cea42828d0787702cb/dev/FormsPlotSandbox/FormSandbox.cs#L14-L57

**Comment by ZTaiIT1025** [comment]
Thanks
