### ISSUE TITLE
Selecting point

### ISSUE THREAD

**Issue by percramer** [swharden/ScottPlot#615]
Hi,

great chart control, let me start with that. I am trying to switch from a DevExpress chart to this one. Most functionality is present, but I was wondering it it is somehow possible to select a range of points. In my old chart setup I can either zoom or select a certain area based on a mouse window and a key press. 

So shift + mouse selection window = zoom to that area and CTRL + mouse is select the points in the area.

Regards,

Per

**Comment by swharden** [comment]
Hi @percramer, I'm happy you enjoy ScottPlot!

If you haven't already, check out the demo application https://swharden.com/scottplot/demo there is a "mouse tracker" and "highlight point near mouse cursor" demo. Source code for the demo application is in this repo, and together those resources may help you get closer to where you're trying to go.

> I was wondering it it is somehow possible to select a range of points

It sounds like you want the user to be able to draw a box over a portion of the plot and for the points inside that box to become highlighted or something? Can you define your goal a bit more, perhaps even with a picture? This functionality is not currently supported, but you could probably modify the code slightly so that the middle-click-drag window selects points of a "PlottableScatterHighlight" instead of changing the zoom.

**Comment by swharden** [comment]
Hey @percramer, 

I haven't heard back in a bit so I'll close this issue but feel free to follow-up if you have more questions!

Scott
