### ISSUE TITLE
No demos or cookbook links for 4.0.44

### ISSUE THREAD

**Issue by Benny121221** [swharden/ScottPlot#625]
The latest demo link is for 4.0.42, and the latest cookbook for 4.0.40. There have been changes to both in 4.0.44.

Also, I know the demos are only WPF, but it might be worth including Avalonia in there because it's cross-platform (I only initially put the effort in for an Avalonia control because I needed Linux support). And given that it's probably not much more effort to include WinForms, if you were so inclined.

~~Also, I'm wondering where the code for generating the cookbook has gone in 4.1?~~ nvm I found it.

**Comment by swharden** [comment]
Hey @Benny121221, thanks for pointing that out! I updated the cookbook and demo website.

### Multi-Framework Demo

I added compiled demos for all 3 graphical frameworks to the demo zip. Hopefully it will be the last 4.0 demo I upload 🤞 

### Cookbook / Website

The cookbook started as ~10 code samples that produced images and generated a readme.md to display on GitHub showing how to use ScottPot. Back then, a cookbook generator that created a single page markdown file made sense.

Over time the cookbook grew and I didn't want to commit those images to the git history, so I moved it to a website (but it still generated markdown, then PHP translates it to HTML). 

Now the cookbook has grown _huge_ and a single page doesn't make sense anymore. It's hard to navigate, and it's rough on mobile and slower connections. I'm thinking about moving to a multi-page static HTML site (which can be viewed locally, or uploaded) instead of markdown... but I haven't figured the best strategy for that yet. It would be nice to do this at the same time we create a FAQ section #572 but I'm still working that out 🤔
