### ISSUE TITLE
Highlight on PlottableSignalConst

### ISSUE THREAD

**Issue by Hori-Leon** [swharden/ScottPlot#632]
Hi.
First, Thank you for sharing remarkable works for others. It helps me a lot too.
It may be shameful that write this article as s a reward. I hope it can be helpful.

# Goal
I wanted to use "Highlight" feature in PlottableSignalConst too. But Scottplot only offers this feature in PlottableScatterHighlight.
But, i must use PlottableSignalConst because now i'm using 4 DAQs and they get 5000000 samples per each.
When i use PlottableScatterHighlight to describe Tooltips for over 1000000+ samples, Rendering performances got severely bottleneck'ed.

# How
This example was written in MVVM way,

Bind an event with a command,
**[!]** it needs Interactivty library so you must download that from NuGet.

![(01)](https://user-images.githubusercontent.com/74895590/100411385-f8b83380-30b4-11eb-8c96-e82369b8e8c0.PNG)

Initialize tooltip UIs,

![(10)](https://user-images.githubusercontent.com/74895590/100411530-62d0d880-30b5-11eb-8e20-94d457e3b102.PNG)

Write what a command will do in detail,

![(1)](https://user-images.githubusercontent.com/74895590/100411758-fefadf80-30b5-11eb-9ee7-7649e09c0375.PNG)

You can ignore "BaseCommand" or whatnot if you do not use MVVM.

# Result

![1](https://user-images.githubusercontent.com/74895590/100411975-9ceeaa00-30b6-11eb-9cb0-6cb6f6ae5645.PNG)

If you have better ideas than mine, plz forget it :d

Cheers,
Horie

**Comment by StendProg** [comment]
Hi @Hori-Leon,

I checked your example. Yes, you found a beautiful solution, but let's think about what can be transferred to ScottPlot.
How exactly to highlight the graphs is far beyond the library and can be left to the discretion of the user. 
But it is quite possible to entrust `ScottPlot` to simplify the calculation of the coordinates.

A good solution would be to implement `IHighlightable` for `Signal`, `SignalConst`, `SignalXY`, `SignalXYConst`.
In particular only these methods:
```c#
        (double x, double y, int index) GetPointNearestX(double x);
        (double x, double y, int index) GetPointNearestY(double y);
        (double x, double y, int index) GetPointNearest(double x, double y);
```
It would simplify your example (First method). Two others can be very costly in terms of performance if we approach them honestly. But we can try to cheat and search for the nearest points already by the min / max array instead of the full source array.

But I'm a bit busy right now. And as far as I understand, now is not the best time for any additions (until 4.1 came out)

**Comment by swharden** [comment]
Hi @Hori-Leon and @StendProg, thanks for posting! Many people have asked how to determine the value of the point under the cursor. This seems to be a common task, so solutions that support signal plots (not just scatter plots) are worth exploring!

### Interfaces

> How exactly to highlight the graphs is far beyond the library and can be left to the discretion of the user

> But it is quite possible to entrust ScottPlot to simplify the calculation of the coordinates.

This makes me think we can segregate these functions into two interfaces:

```cs
interface IHasPoints
{
	(double x, double y, int index) GetPointNearestX(double x);
	(double x, double y, int index) GetPointNearestY(double y);
	(double x, double y, int index) GetPointNearest(double x, double y);
}
```

```cs
interface IHasHighlightablePoints
{
	(double x, double y, int index) HighlightPoint(int index);
	(double x, double y, int index) HighlightPointNearestX(double x);
	(double x, double y, int index) HighlightPointNearestY(double y);
	(double x, double y, int index) HighlightPointNearest(double x, double y);
	void HighlightClear();
}
```

Then we can implement `IHasPoints` in signal plots.

I'll probably delete the ScatterPlotHighlight plot type, implement `IHasPoints` in the regular scatter plot, and leave it to the user to determine how to highlight points.

### Performance in Signal plots

`GetPointNearestX()` can be implemented in a way that yields high performance. @Hori-Leon's code example demonstrates this. For signal plots this type of mouse interaction is probably what most people are interested in.

The other two methods could throw an exception (or be marked obsolete) to indicate they are not performant and probably not be used.

### When to implement this

> But I'm a bit busy right now. And as far as I understand, now is not the best time for any new features (until 4.1 came out)

Remaining work for 4.1 mostly relates to improving multi-axis support by editing the `Axis` and `Plot` modules, and Plottables are mostly stable now. I'll try implementing some of this over the next few days and follow-up here when I have made progress 👍

**Comment by swharden** [comment]
I implemented this in a way that I think makes sense, but I welcome input! I added this code to SignalPlotBase so it now works in Signal and SignalConst:

https://github.com/swharden/ScottPlot/blob/aa03d44aad118413a842279999176f5645ce8ed7/src/ScottPlot/Plottable/SignalPlotBase.cs#L689-L701

Then I wrote a WinForms app to test it out:

https://github.com/swharden/ScottPlot/blob/ef20d5c48bdb91b894bceedbd1907ea79e1c920e/src/sandbox/WinFormsFrameworkApp/Form1.cs#L17-L47

It seems to work! It is very fast.

![sigmouse](https://user-images.githubusercontent.com/4165489/100494315-93912c00-310e-11eb-86ae-5dc8174a756d.gif)

This is pretty good, but not perfect because adding a call to `Render()` in a new MouseMove event handler means `Render()` is getting called _twice_ every time the mouse moves while panning or zooming. A potential solution is to use a timer-based render system like FormsPlotExperimental. This is an active area of development, so I won't try to solve this problem in this issue.

I think this fully resolves this issue!

**Comment by Hori-Leon** [comment]
Thank you for sharing your ideas! @swharden @StendProg 

Since i need to find out impulsive signals among 32 channels of signal I/O, I use 4 DAQ devices for 8 channels per each and they individually store 62500 samples per every seconds for precise checking. So there was no choice except that i should use PlottableSignalConst because of high perfomances.

And i used     

(double x, double y, int index) GetPointNearest(double x, double y);

Before. But in my experiences, i thought its accuracy is quite low when a plot has highly dense samples. That's why i implemented tracking points feature like that 🤔 

Anyway, thank you for helping. i owe you a lot.


Cheers,
Horie
