### ISSUE TITLE
MVVM pattern.

### ISSUE THREAD

**Issue by FoxTes** [swharden/ScottPlot#633]
Hi Scott.
Thanks a lot for your charts. I like their functionality and simplicity.

I know that version 5 is coming out soon. I would like to know if it will be possible to use MVVM in the future?

At the moment, I cannot use your product because of this.

**Comment by swharden** [comment]
Hi @FoxTes, I'm glad you enjoy using this library! 

MVVM is a commonly used pattern for GUI environments, but ScottPlot was is designed to plot data onto bitmap images in console applications, so it does not use MVVM. User controls respond to mouse interactions and generate new bitmaps (giving the appearance of interactivity) but since the core of ScottPlot does not use MVVM, neither do the controls. This is a common question though so I'll add it to the FAQ I'm working on (#572) - thanks for raising it!

What type of data are you trying to display in your application? I would be surprised to learn that there is something you cannot do because the ScottPlot controls do not use MVVM pattern. The demo application https://swharden.com/scottplot/demo shows how to display live updating data interactively, and its source code is in this repository.

I'll close this issue for now, but feel free to respond or open it again if you have further questions! 👍

**Comment by FoxTes** [comment]
I am using an application building with Prism.
It uses a ViewModel, which makes it easier to use MVVM.

Of course, you can use behind code, but it will be more difficult.

**Comment by swharden** [comment]
> you can use behind code, but it will be more difficult

This is a good summary of the current situation!

It is possible to create a MVVM control for ScottPlot (and not use the control provided by the `ScottPlot.WPF` package).
Such a control would probably be highly specific to your particular application. Therefore, I think it makes sense for application developers to implement their own MVVM controls to suit their use case if use of that pattern is required 👍

**Comment by FoxTes** [comment]
> Можно создать элемент управления MVVM для ScottPlot (и не использовать элемент управления, предоставляемый ScottPlot.WPFпакетом).

Can you show an example?

> Therefore, I think it makes sense for application developers to implement their own MVVM controls to suit their use case if use of that pattern is required.

I do not quite understand your idea.

**Comment by swharden** [comment]
> > It is possible to create a MVVM control for ScottPlot (and not use the control provided by the ScottPlot.WPF package)

> I do not quite understand your idea.

The code below is a WinForms control for an interactive ScottPlot (the WPF control is similar). It is simple, only about 150 lines. My suggestion is that, if you really want a control that uses MVVM pattern, you can create one using this as a starting point.

https://github.com/swharden/ScottPlot/blob/abc444d049f9e915080a86726de476bdef29f309/src/controls/ScottPlot.WinForms/FormsPlotExperimental.cs#L1-L152

> Can you show an example?

I do not have an example, but I'll consider adding an example to the FAQ (#572, #412) because this is a common question 👍

**Comment by FoxTes** [comment]
It's worked. Thank for example!

**Comment by StendProg** [comment]
Hi all,

Sorry for the belated comment, but I think it might still be helpful.
This question already discussed in #494.
I use the solution described in https://github.com/swharden/ScottPlot/issues/494#issuecomment-665236518 and find it quite convenient.
