### ISSUE TITLE
Xticks custom positions and labels 

### ISSUE THREAD

**Issue by bukkideme** [swharden/ScottPlot#648]
I wonder what would be the best approach for the following scenario.
I need to plot bars (PlotBar) sometimes with non-equidistant values, and I do not want to show empty gaps. So I just use Xticks along with artificial position values and labels as strings. In one of my prev post I showed an example:
https://github.com/swharden/ScottPlot/issues/640

Now my question is that, what about if I have many labels, so after a while they start to overlap. Is it possible now, or as a future feature to have an automatic label handling, avoiding drawing overlapping labels?
For an example, I show below a bar plot when the custom labels overlap, and how it looks like when I am zoomed in, and labels do not overlap anymore.
Thanks for info!

![custom_labels3](https://user-images.githubusercontent.com/51174971/101638680-a240e280-3a2e-11eb-8adb-2dddce94a723.PNG)

![custom_labels2](https://user-images.githubusercontent.com/51174971/101638418-555d0c00-3a2e-11eb-9a32-365dd1b85ba0.PNG)

**Comment by swharden** [comment]
Hi @bukkideme, interestingly this issue is similar to that raised in #644. As you've discovered, manually defining tick positions/labels looks bad when you zoom out. I don't think there's a straightforward way to get around this, and a real fix would involve heavily modifying the tick system which is a can of worms and I probably won't open that until some other tasks are settled. I added this topic to the triage list in #651 so I might be able to look back to it later.

For an immediate fix though, notice that `FormsPlot` has an `AxesChanged` event. Every time that's called you could do a little math to determine the ideal density of manual ticks to display.

![tick density](https://user-images.githubusercontent.com/4165489/102703288-f7ed6a00-423a-11eb-9276-8e8ae9e6ca55.gif)

```cs
public string[] seriesLabels;

public Form1()
{
    InitializeComponent();

    // generate capacitor values
    List<double> values = new List<double>();
    double[] mults = { 10, 11, 12, 13, 15, 16, 18, 20, 22, 24, 27, 30, 33, 36, 39, 43, 47, 51, 56, 62, 68, 75, 82, 91 };
    double[] scales = { .1, 1, 10, 100, 1000 };
    foreach (double scale in scales)
        foreach (double mult in mults)
            values.Add(scale * mult);
    seriesLabels = values.Select(x => x.ToString()).ToArray();

    // generate fake deviation data
    Random rand = new Random();
    double[] ys = values.Select(x => Math.Sqrt(rand.NextDouble() * x)).ToArray();

    // plot the data
    formsPlot1.plt.PlotBar(null, ys);
    formsPlot1.plt.YLabel("Deviation from nominal (pF)");
    formsPlot1.plt.XLabel("Nominal Capacity (pF)");
    formsPlot1_AxesChanged(null, null);
}

private void formsPlot1_AxesChanged(object sender, EventArgs e)
{
    // determine how dense the ticks are and what that N should be
    double pixelsApart = formsPlot1.plt.CoordinateToPixel(1, 0).X - formsPlot1.plt.CoordinateToPixel(0, 0).X;
    double labelSeparationPixels = 50;
    int skip = Math.Max((int)(labelSeparationPixels / pixelsApart), 1);
    int[] indexes = Enumerable.Range(0, seriesLabels.Length / skip).Select(x => x * skip).ToArray();

    // plot every Nth label
    double[] xs = indexes.Select(x => (double)x).ToArray();
    string[] labels = indexes.Select(x => seriesLabels[x]).ToArray();
    formsPlot1.plt.XTicks(xs, labels);
    formsPlot1.Render();
}
```

**Comment by bukkideme** [comment]
Thanks for the example!
Best Regards,
