### ISSUE TITLE
Package installation failed.

### ISSUE THREAD

**Issue by FoxTes** [swharden/ScottPlot#659]
Hi Scott. I am using VS 2015. While installing the package, I get the following error:

```
Severity Code Description Project File String Suppression status
Error Failed to install package "ScottPlot 4.0.47". You are trying to install this package in a project that requires ".NETFramework, Version = v4.8" for the platform version, but the package does not have assembly references or content files that are compatible with that framework.
For more information, contact the author of the package.
```

If using VS 2019, then this error does not occur.
What is the possible reason?

**Comment by swharden** [comment]
Hi @FoxTes, I think we've seen something similar before in #261 and the core issue is a NuGet installer issue with VS215 (not a necessarily a ScottPlot issue)

Things to try are: 

* **Download ScottPlot source code** and reference that project instead of using NuGet to install it. Instructions are [here](https://github.com/swharden/ScottPlot/tree/master/src#build-scottplot-from-source-code) and you should probably download a ZIP of the non-beta source from the [releases page](https://github.com/swharden/ScottPlot/releases)

* **Install an old version of ScottPlot** (try 3.1.6)

I'll close this issue, but feel free to open it up again if you have more questions.

If you figure it out, I'd love to hear what worked for you! Write a follow-up comment on this issue so the next person with the same problem can have their question answered too.

**Comment by FoxTes** [comment]
Well. The problem was solved simply. I opened `VS 2019`. Installed the `Nuget` package. Then I opened it in `VS 2015`. After that the problems disappeared.
