### ISSUE TITLE
Colormap scalebar Bitmap generation should be abstracted

### ISSUE THREAD

**Issue by swharden** [swharden/ScottPlot#678]
It may be useful to allow colormaps to generate their own scalebars as standalone bitmaps. Colormap-scalebar-generating code should be removed out of the heatmap module and placed elsewhere...

This refactoring can be performed in parallel with #677 and #675

**Comment by Benny121221** [comment]
It may be useful to model this off of the `Renderable.Legend`, or if you want it to be an `IPlottable` then `Plottable.ScaleBar` might make sense. Conceptually they are similar, although getting the colours could be interesting. `ScaleBar` gets passed in `width` and `height` explicitly, while `Legend` has its items updated on every [render](https://github.com/swharden/ScottPlot/blob/3bf13aa5a64b2d7cbdeb1e27c73bb245b9cc07d3/src/ScottPlot/Plot/Plot.Render.cs#L88).

I think getting the colourmap information in the same way that `Legend` does is better as it's much more convenient from a user perspective, although it does introduce extra coupling.

**Comment by swharden** [comment]
@Benny121221 thanks for the idea! I think a standalone plot type for this would be excellent. I'll call it a `Colorbar`, borrowing the term from matplotlib. This plot type (with its own methods for getting the bitmap with/without labels) will indeed help solve this issue, while also removing a bit of complexity from the heatmap module. I'll explore this idea shortly...

I just finished refactoring the heatmap module a bit and adding recipes to the 4.1 cookbook. (#679) I'm curious if you think the "Scale Limits" example is working as expected. The cookbook is generated whenever the tests are run, but I'm attaching the heatmap page in case you don't want to fire that up: [Cookbook: Plottable Heatmap.zip](https://github.com/swharden/ScottPlot/files/5740598/Cookbook_.Plottable_.Heatmap.zip)

It might benefit from refactoring so _styling_ options are public fields but options which affect the data are passed in as arguments to the `Update()` function 🤔

**Comment by Benny121221** [comment]
>  I'm curious if you think the "Scale Limits" example is working as expected.

Yep, it looks right. It does look a little strange because you're clipping half the range, but that's what I would expect it to look like.

> It might benefit from refactoring so styling options are public fields but options which affect the data are passed in as arguments to the Update() function 🤔

I would prefer this route, however, I think for some styling options are potentially expensive to compute on every render (e.g. scaleMin/scaleMax requires renormalization, or changing the colourmap requires recomputing colours and recreating the bitmap). You can get around this to a certain extent by having public properties with a non-trivial setter. I don't know what the right balance is, and I don't know how often such styling things are likely to be changed.

There are some minor tweaks I have but all in all this looks good! I made a small PR to address those concerns. Most of it is just wording of a demo, and there's an aesthetic thing: #680

**Comment by swharden** [comment]
FWIW, I am reminded that you can get a colormap bitmap already using a helper method in the Colormap module:

```cs
var cm = ScottPlot.Drawing.Colormap.Turbo;
Bitmap bmp = ScottPlot.Drawing.Colormap.Colorbar(cm, width: 600, height: 50, vertical: false);
bmp.Save("colormap.png", System.Drawing.Imaging.ImageFormat.Png);
```


![colormap](https://user-images.githubusercontent.com/4165489/103139465-6ce0f980-46aa-11eb-8156-b85526ecd79d.png)

**Comment by swharden** [comment]
This is accomplished now and a new Colorbar plot type has been made.

I'll publish a new package and cookbook demonstrating this today
